"""Companies the news feed follows beyond the hand-made COMPANY_MAP in
fetch_news.py: the 500 largest Nasdaq and NYSE listings in SEC's ticker list
(www.sec.gov/files/company_tickers_exchange.json) as of 2026-10-02 that the
map didn't have, minus two that would double a parent's headlines. One-off,
not regenerated: edit entries by hand like COMPANY_MAP's.

Each entry has the same keys as a COMPANY_MAP entry, plus "label", the name
the site's pages show. Names were cleaned from SEC's legal names and checked
by hand against the headline archive: everyday words, surnames and other
companies' brands left out; banks quoted as analysts carry an "exclude" so
"Barclays raises its target on X" doesn't tag Barclays. A sector is the
site's own, chosen from the SEC industry code.
"""


# a bank or ratings agency that is also quoted as an analyst house: its name
# in "Barclays raises its target on X" is about X, not about the bank
def analyst_house(*names):
    alt = "|".join(n.replace(".", r"\.").replace(" ", r"\s+") for n in names)
    verbs = (r"analysts?|strategists?|economists?|research|says|said|sees|saw|expects|expected|raises|raised|"
             r"lifts|lifted|cuts|lowers|lowered|upgrades?|upgraded|downgrades?|downgraded|initiates?|initiated|"
             r"reiterates?|reiterated|maintains?|maintained|keeps|kept|predicts|predicted|forecasts|names|named|"
             r"bumps|bumped|boosts|boosted|trims|trimmed|slashes|slashed|hikes|hiked|affirms|affirmed|rates|rated|"
             r"places|placed|assigns|assigned|sets|starts|started|resumes|resumed|reaffirms|reaffirmed|backs|"
             r"likes|prefers|warns|warned|notes|noted|thinks|believes|estimates|estimated|told|tells|calls|called")
    return (rf"(?i)\b(?:{alt})(?:'s|')?\s+(?:Capital Markets\s+|Capital\s+|Securities\s+|Global Research\s+|"
            rf"Ratings\s+|Investors Service\s+|Analytics\s+|Research\s+)?(?:{verbs})\b"
            rf"|(?i:\b(?:analysts?|strategists?|economists?)\s+(?:at|from)\s+(?:{alt}))\b"
            rf"|(?i:\baccording to\s+(?:{alt}))\b"
            rf"|(?i:\bby\s+(?:{alt}))\b")  # "outlook raised by Moody's"


SEC_COMPANIES = [
    {"ticker": "ABBV", "label": "AbbVie", "sector": "Healthcare", "names": ["AbbVie"]},
    {"ticker": "CSCO", "label": "Cisco Systems", "sector": "Tech Hardware", "names": ["Cisco Systems", "Cisco"]},
    {"ticker": "LRCX", "label": "Lam Research", "sector": "Semiconductors", "names": ["Lam Research"]},
    {"ticker": "HSBC", "label": "HSBC", "sector": "Banking & Finance", "names": ["HSBC"], "exclude": analyst_house("HSBC")},
    {"ticker": "SMFG", "label": "Sumitomo Mitsui", "sector": "Banking & Finance", "names": ["Sumitomo Mitsui", "SMBC"]},
    {"ticker": "PM", "label": "Philip Morris", "sector": "Consumer Goods", "names": ["Philip Morris"], "match_ticker": False},
    {"ticker": "HD", "label": "Home Depot", "sector": "Consumer Goods", "names": ["Home Depot"], "match_ticker": False},
    {"ticker": "RY", "label": "Royal Bank of Canada", "sector": "Banking & Finance", "names": ["Royal Bank of Canada"], "match_ticker": False, "exclude": analyst_house("RBC", "Royal Bank of Canada")},
    {"ticker": "MUFG", "label": "Mitsubishi UFJ", "sector": "Banking & Finance", "names": ["Mitsubishi UFJ", "MUFG"], "exclude": analyst_house("MUFG")},
    {"ticker": "TXN", "label": "Texas Instruments", "sector": "Semiconductors", "names": ["Texas Instruments"]},
    {"ticker": "ANET", "label": "Arista Networks", "sector": "Tech Hardware", "names": ["Arista Networks", "Arista"]},
    {"ticker": "GEV", "label": "GE Vernova", "sector": "Industrials", "names": ["GE Vernova"]},
    {"ticker": "KLAC", "label": "KLA", "sector": "Semiconductors", "names": ["KLA"]},
    {"ticker": "TMO", "label": "Thermo Fisher", "sector": "Healthcare", "names": ["Thermo Fisher"]},
    {"ticker": "SAP", "label": "SAP", "sector": "Software / Cloud", "names": ["SAP"]},
    {"ticker": "C", "label": "Citigroup", "sector": "Banking & Finance", "names": ["Citigroup"], "match_ticker": False, "exclude": analyst_house("Citi", "Citigroup")},
    {"ticker": "LIN", "label": "Linde", "sector": "Chemicals & Materials", "names": ["Linde"]},
    {"ticker": "APH", "label": "Amphenol", "sector": "Tech Hardware", "names": ["Amphenol"]},
    {"ticker": "IBM", "label": "IBM", "sector": "Software / Cloud", "names": ["IBM", "International Business Machines"]},
    {"ticker": "STX", "label": "Seagate Technology", "sector": "Tech Hardware", "names": ["Seagate Technology", "Seagate"]},
    {"ticker": "AXP", "label": "American Express", "sector": "Payments / Fintech", "names": ["American Express", "Amex"]},
    {"ticker": "SAN", "label": "Santander", "sector": "Banking & Finance", "names": ["Santander"]},
    {"ticker": "TD", "label": "TD Bank", "sector": "Banking & Finance", "names": ["TD Bank", "Toronto-Dominion"], "match_ticker": False},
    {"ticker": "TTE", "label": "TotalEnergies", "sector": "Oil & Gas", "names": ["TotalEnergies"]},
    {"ticker": "ADI", "label": "Analog Devices", "sector": "Semiconductors", "names": ["Analog Devices"]},
    {"ticker": "SHOP", "label": "Shopify", "sector": "Software / Cloud", "names": ["Shopify"]},
    {"ticker": "DE", "label": "Deere", "sector": "Industrials", "names": ["Deere", "John Deere"], "match_ticker": False},
    {"ticker": "TMUS", "label": "T-Mobile", "sector": "Telecom", "names": ["T-Mobile"]},
    {"ticker": "BLK", "label": "BlackRock", "sector": "Banking & Finance", "names": ["BlackRock"]},
    {"ticker": "ABT", "label": "Abbott Laboratories", "sector": "Healthcare", "names": ["Abbott Laboratories", "Abbott"]},
    {"ticker": "SCCO", "label": "Southern Copper", "sector": "Metals & Mining", "names": ["Southern Copper"]},
    {"ticker": "SCHW", "label": "Charles Schwab", "sector": "Banking & Finance", "names": ["Charles Schwab", "Schwab"]},
    {"ticker": "ETN", "label": "Eaton", "sector": "Industrials", "names": ["Eaton"]},
    {"ticker": "WELL", "label": "Welltower", "sector": "Real Estate / Homebuilders", "names": ["Welltower"]},
    {"ticker": "WDC", "label": "Western Digital", "sector": "Tech Hardware", "names": ["Western Digital"]},
    {"ticker": "UNP", "label": "Union Pacific", "sector": "Industrials", "names": ["Union Pacific"]},
    {"ticker": "DHR", "label": "Danaher", "sector": "Healthcare", "names": ["Danaher"]},
    {"ticker": "BBVA", "label": "BBVA", "sector": "Banking & Finance", "names": ["BBVA", "Banco Bilbao Vizcaya Argentaria"]},
    {"ticker": "IBKR", "label": "Interactive Brokers", "sector": "Banking & Finance", "names": ["Interactive Brokers"]},
    {"ticker": "TJX", "label": "TJX", "sector": "Consumer Goods", "names": ["TJX"]},
    {"ticker": "ISRG", "label": "Intuitive Surgical", "sector": "Healthcare", "names": ["Intuitive Surgical"]},
    {"ticker": "BUD", "label": "Anheuser-Busch", "sector": "Consumer Goods", "names": ["Anheuser-Busch", "AB InBev"]},
    {"ticker": "GLW", "label": "Corning", "sector": "Tech Hardware", "names": ["Corning"]},
    {"ticker": "SONY", "label": "Sony", "sector": "Tech Hardware", "names": ["Sony"]},
    {"ticker": "BX", "label": "Blackstone", "sector": "Banking & Finance", "names": ["Blackstone"], "match_ticker": False},
    {"ticker": "VRTX", "label": "Vertex Pharmaceuticals", "sector": "Healthcare", "names": ["Vertex Pharmaceuticals"]},
    {"ticker": "MFG", "label": "Mizuho Financial", "sector": "Banking & Finance", "names": ["Mizuho Financial"], "exclude": analyst_house("Mizuho")},
    {"ticker": "PBR", "label": "Petrobras", "sector": "Oil & Gas", "names": ["Petrobras"]},
    {"ticker": "UL", "label": "Unilever", "sector": "Consumer Goods", "names": ["Unilever"], "match_ticker": False},
    {"ticker": "BMY", "label": "Bristol Myers Squibb", "sector": "Healthcare", "names": ["Bristol Myers Squibb", "Bristol-Myers Squibb", "Bristol Myers"]},
    {"ticker": "PLD", "label": "Prologis", "sector": "Real Estate / Homebuilders", "names": ["Prologis"]},
    {"ticker": "CB", "label": "Chubb", "sector": "Banking & Finance", "names": ["Chubb"], "match_ticker": False},
    {"ticker": "BKNG", "label": "Booking Holdings", "sector": "Airlines / Travel", "names": ["Booking Holdings", "Booking.com"]},
    {"ticker": "PH", "label": "Parker-Hannifin", "sector": "Industrials", "names": ["Parker-Hannifin", "Parker Hannifin"], "match_ticker": False},
    {"ticker": "PGR", "label": "Progressive Corp", "sector": "Banking & Finance", "names": ["Progressive Corp", "Progressive Insurance"]},
    {"ticker": "COF", "label": "Capital One", "sector": "Banking & Finance", "names": ["Capital One"]},
    {"ticker": "ASX", "label": "ASE Technology", "sector": "Semiconductors", "names": ["ASE Technology"]},
    {"ticker": "BMO", "label": "Bank of Montreal", "sector": "Banking & Finance", "names": ["Bank of Montreal"], "match_ticker": False, "exclude": analyst_house("BMO", "Bank of Montreal")},
    {"ticker": "BTI", "label": "British American Tobacco", "sector": "Consumer Goods", "names": ["British American Tobacco"]},
    {"ticker": "HDB", "label": "HDFC Bank", "sector": "Banking & Finance", "names": ["HDFC Bank"]},
    {"ticker": "MO", "label": "Altria", "sector": "Consumer Goods", "names": ["Altria"], "match_ticker": False},
    {"ticker": "BNS", "label": "Bank of Nova Scotia", "sector": "Banking & Finance", "names": ["Bank of Nova Scotia", "Scotiabank"], "exclude": analyst_house("Scotiabank")},
    {"ticker": "MDT", "label": "Medtronic", "sector": "Healthcare", "names": ["Medtronic"]},
    {"ticker": "VLO", "label": "Valero Energy", "sector": "Oil & Gas", "names": ["Valero Energy", "Valero"]},
    {"ticker": "CVS", "label": "CVS Health", "sector": "Healthcare", "names": ["CVS Health", "CVS"]},
    {"ticker": "PDD", "label": "PDD Holdings", "sector": "Consumer Goods", "names": ["PDD Holdings", "Pinduoduo", "Temu"]},
    {"ticker": "MPC", "label": "Marathon Petroleum", "sector": "Oil & Gas", "names": ["Marathon Petroleum"]},
    {"ticker": "ACN", "label": "Accenture", "sector": "Software / Cloud", "names": ["Accenture"]},
    {"ticker": "SYK", "label": "Stryker", "sector": "Healthcare", "names": ["Stryker"]},
    {"ticker": "LOW", "label": "Lowe's", "sector": "Consumer Goods", "names": ["Lowe's", "Lowes"], "match_ticker": False},
    {"ticker": "ENB", "label": "Enbridge", "sector": "Oil & Gas", "names": ["Enbridge"]},
    {"ticker": "ADP", "label": "Automatic Data Processing", "sector": "Software / Cloud", "names": ["Automatic Data Processing"], "match_ticker": False},
    {"ticker": "APP", "label": "AppLovin", "sector": "Software / Cloud", "names": ["AppLovin"]},
    {"ticker": "ING", "label": "ING Groep", "sector": "Banking & Finance", "names": ["ING Groep", "ING Group"], "exclude": analyst_house("ING")},
    {"ticker": "SPOT", "label": "Spotify Technology", "sector": "Media / Entertainment", "names": ["Spotify Technology", "Spotify"]},
    {"ticker": "CM", "label": "CIBC", "sector": "Banking & Finance", "names": ["CIBC", "Canadian Imperial Bank of Commerce"], "match_ticker": False, "exclude": analyst_house("CIBC")},
    {"ticker": "PSX", "label": "Phillips 66", "sector": "Oil & Gas", "names": ["Phillips 66"]},
    {"ticker": "BNY", "label": "BNY Mellon", "sector": "Banking & Finance", "names": ["BNY Mellon", "Bank of New York Mellon", "BNY"]},
    {"ticker": "TT", "label": "Trane Technologies", "sector": "Industrials", "names": ["Trane Technologies", "Trane"], "match_ticker": False},
    {"ticker": "EQIX", "label": "Equinix", "sector": "Real Estate / Homebuilders", "names": ["Equinix"]},
    {"ticker": "MCK", "label": "McKesson", "sector": "Healthcare", "names": ["McKesson"]},
    {"ticker": "GSK", "label": "GSK", "sector": "Healthcare", "names": ["GSK"]},
    {"ticker": "PWR", "label": "Quanta Services", "sector": "Industrials", "names": ["Quanta Services"]},
    {"ticker": "EQNR", "label": "Equinor", "sector": "Oil & Gas", "names": ["Equinor"]},
    {"ticker": "IBN", "label": "ICICI Bank", "sector": "Banking & Finance", "names": ["ICICI Bank"]},
    {"ticker": "SNY", "label": "Sanofi", "sector": "Healthcare", "names": ["Sanofi"]},
    {"ticker": "CNQ", "label": "Canadian Natural Resources", "sector": "Oil & Gas", "names": ["Canadian Natural Resources", "Canadian Natural"]},
    {"ticker": "DDOG", "label": "Datadog", "sector": "Software / Cloud", "names": ["Datadog"]},
    {"ticker": "SO", "label": "Southern Company", "sector": "Utilities", "names": ["Southern Company", "Southern Co"], "match_ticker": False},
    {"ticker": "VRT", "label": "Vertiv", "sector": "AI Infrastructure", "names": ["Vertiv"]},
    {"ticker": "CME", "label": "CME Group", "sector": "Banking & Finance", "names": ["CME Group"], "match_ticker": False},
    {"ticker": "MAR", "label": "Marriott International", "sector": "Airlines / Travel", "names": ["Marriott International", "Marriott"]},
    {"ticker": "AEM", "label": "Agnico Eagle", "sector": "Metals & Mining", "names": ["Agnico Eagle"]},
    {"ticker": "CEG", "label": "Constellation Energy", "sector": "Utilities", "names": ["Constellation Energy"]},
    {"ticker": "HCA", "label": "HCA Healthcare", "sector": "Healthcare", "names": ["HCA Healthcare"]},
    {"ticker": "HWM", "label": "Howmet", "sector": "Defense", "names": ["Howmet"]},
    {"ticker": "JCI", "label": "Johnson Controls", "sector": "Industrials", "names": ["Johnson Controls"]},
    {"ticker": "USB", "label": "U.S. Bancorp", "sector": "Banking & Finance", "names": ["U.S. Bancorp", "US Bancorp"]},
    {"ticker": "GD", "label": "General Dynamics", "sector": "Defense", "names": ["General Dynamics"], "match_ticker": False},
    {"ticker": "DUK", "label": "Duke Energy", "sector": "Utilities", "names": ["Duke Energy"]},
    {"ticker": "ITUB", "label": "Itau Unibanco", "sector": "Banking & Finance", "names": ["Itau Unibanco"]},
    {"ticker": "CDNS", "label": "Cadence Design Systems", "sector": "Software / Cloud", "names": ["Cadence Design Systems", "Cadence Design"]},
    {"ticker": "PNC", "label": "PNC Financial", "sector": "Banking & Finance", "names": ["PNC Financial"]},
    {"ticker": "EMR", "label": "Emerson Electric", "sector": "Industrials", "names": ["Emerson Electric"]},
    {"ticker": "MELI", "label": "MercadoLibre", "sector": "Consumer Goods", "names": ["MercadoLibre", "Mercado Libre"]},
    {"ticker": "MMM", "label": "3M", "sector": "Industrials", "names": ["3M"], "exclude": r"[$€£]\s?3M\b"},
    {"ticker": "CSX", "label": "CSX", "sector": "Industrials", "names": []},
    {"ticker": "KKR", "label": "KKR", "sector": "Banking & Finance", "names": []},
    {"ticker": "ICE", "label": "Intercontinental Exchange", "sector": "Banking & Finance", "names": ["Intercontinental Exchange"], "match_ticker": False},
    {"ticker": "ELV", "label": "Elevance Health", "sector": "Healthcare", "names": ["Elevance Health", "Elevance"]},
    {"ticker": "WMB", "label": "Williams Companies", "sector": "Oil & Gas", "names": ["Williams Companies"]},
    {"ticker": "WM", "label": "Waste Management", "sector": "Industrials", "names": ["Waste Management"], "match_ticker": False},
    {"ticker": "MNST", "label": "Monster Beverage", "sector": "Consumer Goods", "names": ["Monster Beverage"]},
    {"ticker": "LYG", "label": "Lloyds Banking", "sector": "Banking & Finance", "names": ["Lloyds Banking", "Lloyds Bank"]},
    {"ticker": "HPE", "label": "Hewlett Packard Enterprise", "sector": "Tech Hardware", "names": ["Hewlett Packard Enterprise", "HPE"]},
    {"ticker": "BCS", "label": "Barclays", "sector": "Banking & Finance", "names": ["Barclays"], "exclude": analyst_house("Barclays")},
    {"ticker": "MRSH", "label": "Marsh McLennan", "sector": "Banking & Finance", "names": ["Marsh McLennan", "Marsh & McLennan"]},
    {"ticker": "BN", "label": "Brookfield Corp", "sector": "Real Estate / Homebuilders", "names": ["Brookfield Corp"], "match_ticker": False},
    {"ticker": "DASH", "label": "DoorDash", "sector": "Consumer Goods", "names": ["DoorDash"]},
    {"ticker": "UPS", "label": "United Parcel Service", "sector": "Industrials", "names": ["United Parcel Service"]},
    {"ticker": "SHW", "label": "Sherwin-Williams", "sector": "Chemicals & Materials", "names": ["Sherwin-Williams", "Sherwin Williams"]},
    {"ticker": "SU", "label": "Suncor", "sector": "Oil & Gas", "names": ["Suncor"], "match_ticker": False},
    {"ticker": "CTAS", "label": "Cintas", "sector": "Industrials", "names": ["Cintas"]},
    {"ticker": "MCO", "label": "Moody's", "sector": "Banking & Finance", "names": ["Moody's"], "exclude": analyst_house("Moody's", "Moody's Analytics", "Moody's Ratings", "Moody's Investors Service")},
    {"ticker": "E", "label": "Eni", "sector": "Oil & Gas", "names": ["Eni"], "match_ticker": False},
    {"ticker": "EPD", "label": "Enterprise Products Partners", "sector": "Oil & Gas", "names": ["Enterprise Products Partners"]},
    {"ticker": "ECL", "label": "Ecolab", "sector": "Chemicals & Materials", "names": ["Ecolab"]},
    {"ticker": "NTES", "label": "NetEase", "sector": "Software / Cloud", "names": ["NetEase"]},
    {"ticker": "AMT", "label": "American Tower", "sector": "Real Estate / Homebuilders", "names": ["American Tower"]},
    {"ticker": "SPG", "label": "Simon Property", "sector": "Real Estate / Homebuilders", "names": ["Simon Property"]},
    {"ticker": "REGN", "label": "Regeneron", "sector": "Healthcare", "names": ["Regeneron"]},
    {"ticker": "CMCSA", "label": "Comcast", "sector": "Media / Entertainment", "names": ["Comcast"]},
    {"ticker": "ITW", "label": "Illinois Tool Works", "sector": "Industrials", "names": ["Illinois Tool Works"]},
    {"ticker": "CP", "label": "Canadian Pacific", "sector": "Industrials", "names": ["Canadian Pacific", "CPKC"], "match_ticker": False},
    {"ticker": "MDLZ", "label": "Mondelez", "sector": "Consumer Goods", "names": ["Mondelez"]},
    {"ticker": "TRV", "label": "Travelers Companies", "sector": "Banking & Finance", "names": ["Travelers Companies", "Travelers Cos"]},
    {"ticker": "ROST", "label": "Ross Stores", "sector": "Consumer Goods", "names": ["Ross Stores"]},
    {"ticker": "NGG", "label": "National Grid", "sector": "Utilities", "names": ["National Grid"]},
    {"ticker": "MSI", "label": "Motorola Solutions", "sector": "Tech Hardware", "names": ["Motorola Solutions"]},
    {"ticker": "SLB", "label": "SLB", "sector": "Oil & Gas", "names": ["SLB", "Schlumberger"]},
    {"ticker": "EOG", "label": "EOG Resources", "sector": "Oil & Gas", "names": ["EOG Resources"]},
    {"ticker": "CNI", "label": "Canadian National Railway", "sector": "Industrials", "names": ["Canadian National Railway", "Canadian National"]},
    {"ticker": "HLT", "label": "Hilton Worldwide", "sector": "Airlines / Travel", "names": ["Hilton Worldwide", "Hilton"]},
    {"ticker": "CI", "label": "Cigna", "sector": "Healthcare", "names": ["Cigna"], "match_ticker": False},
    {"ticker": "NWG", "label": "NatWest", "sector": "Banking & Finance", "names": ["NatWest"]},
    {"ticker": "CMI", "label": "Cummins", "sector": "Industrials", "names": ["Cummins"]},
    {"ticker": "BAM", "label": "Brookfield Asset Management", "sector": "Banking & Finance", "names": ["Brookfield Asset Management"]},
    {"ticker": "MFC", "label": "Manulife", "sector": "Banking & Finance", "names": ["Manulife"]},
    {"ticker": "INTU", "label": "Intuit", "sector": "Software / Cloud", "names": ["Intuit"]},
    {"ticker": "RACE", "label": "Ferrari", "sector": "Automotive / EV", "names": ["Ferrari"]},
    {"ticker": "CVNA", "label": "Carvana", "sector": "Automotive / EV", "names": ["Carvana"]},
    {"ticker": "NSC", "label": "Norfolk Southern", "sector": "Industrials", "names": ["Norfolk Southern"]},
    {"ticker": "RCL", "label": "Royal Caribbean", "sector": "Airlines / Travel", "names": ["Royal Caribbean"]},
    {"ticker": "ORLY", "label": "O'Reilly Automotive", "sector": "Automotive / EV", "names": ["O'Reilly Automotive", "O'Reilly Auto"]},
    {"ticker": "CL", "label": "Colgate-Palmolive", "sector": "Consumer Goods", "names": ["Colgate-Palmolive", "Colgate"], "match_ticker": False},
    {"ticker": "ET", "label": "Energy Transfer", "sector": "Oil & Gas", "names": ["Energy Transfer"], "match_ticker": False},
    {"ticker": "FDX", "label": "FedEx", "sector": "Industrials", "names": ["FedEx"]},
    {"ticker": "DB", "label": "Deutsche Bank", "sector": "Banking & Finance", "names": ["Deutsche Bank"], "match_ticker": False, "exclude": analyst_house("Deutsche Bank")},
    {"ticker": "KMI", "label": "Kinder Morgan", "sector": "Oil & Gas", "names": ["Kinder Morgan"]},
    {"ticker": "MPWR", "label": "Monolithic Power", "sector": "Semiconductors", "names": ["Monolithic Power"]},
    {"ticker": "DLR", "label": "Digital Realty", "sector": "Real Estate / Homebuilders", "names": ["Digital Realty"]},
    {"ticker": "AMX", "label": "America Movil", "sector": "Telecom", "names": ["America Movil", "América Móvil"]},
    {"ticker": "AEP", "label": "American Electric Power", "sector": "Utilities", "names": ["American Electric Power"]},
    {"ticker": "RSG", "label": "Republic Services", "sector": "Industrials", "names": ["Republic Services"]},
    {"ticker": "TER", "label": "Teradyne", "sector": "Semiconductors", "names": ["Teradyne"]},
    {"ticker": "URI", "label": "United Rentals", "sector": "Industrials", "names": ["United Rentals"]},
    {"ticker": "UMC", "label": "United Microelectronics", "sector": "Semiconductors", "names": ["United Microelectronics", "UMC"]},
    {"ticker": "APD", "label": "Air Products", "sector": "Chemicals & Materials", "names": ["Air Products"]},
    {"ticker": "TEL", "label": "TE Connectivity", "sector": "Tech Hardware", "names": ["TE Connectivity"]},
    {"ticker": "WPM", "label": "Wheaton Precious Metals", "sector": "Metals & Mining", "names": ["Wheaton Precious Metals"]},
    {"ticker": "KEYS", "label": "Keysight Technologies", "sector": "Tech Hardware", "names": ["Keysight Technologies", "Keysight"]},
    {"ticker": "SE", "label": "Sea Ltd", "sector": "Consumer Goods", "names": ["Sea Ltd", "Sea Limited", "Shopee"], "match_ticker": False},
    {"ticker": "TDG", "label": "TransDigm", "sector": "Defense", "names": ["TransDigm"]},
    {"ticker": "MET", "label": "MetLife", "sector": "Banking & Finance", "names": ["MetLife"]},
    {"ticker": "ARGX", "label": "argenx", "sector": "Healthcare", "names": ["argenx"]},
    {"ticker": "NU", "label": "Nu Holdings", "sector": "Payments / Fintech", "names": ["Nu Holdings", "Nubank"], "match_ticker": False},
    {"ticker": "NXPI", "label": "NXP Semiconductors", "sector": "Semiconductors", "names": ["NXP Semiconductors", "NXP"]},
    {"ticker": "NTRA", "label": "Natera", "sector": "Healthcare", "names": ["Natera"]},
    {"ticker": "TAK", "label": "Takeda", "sector": "Healthcare", "names": ["Takeda"]},
    {"ticker": "GWW", "label": "W.W. Grainger", "sector": "Industrials", "names": ["W.W. Grainger", "Grainger"]},
    {"ticker": "PCAR", "label": "Paccar", "sector": "Automotive / EV", "names": ["Paccar"]},
    {"ticker": "FIX", "label": "Comfort Systems", "sector": "Industrials", "names": ["Comfort Systems"], "match_ticker": False},
    {"ticker": "AJG", "label": "Arthur J. Gallagher", "sector": "Banking & Finance", "names": ["Arthur J. Gallagher"]},
    {"ticker": "TRGP", "label": "Targa Resources", "sector": "Oil & Gas", "names": ["Targa Resources"]},
    {"ticker": "NOK", "label": "Nokia", "sector": "Tech Hardware", "names": ["Nokia"]},
    {"ticker": "COR", "label": "Cencora", "sector": "Healthcare", "names": ["Cencora"]},
    {"ticker": "AON", "label": "Aon", "sector": "Banking & Finance", "names": ["Aon"]},
    {"ticker": "AME", "label": "Ametek", "sector": "Industrials", "names": ["Ametek"]},
    {"ticker": "MPLX", "label": "Mplx", "sector": "Oil & Gas", "names": ["Mplx"]},
    {"ticker": "RELX", "label": "RELX", "sector": "Media / Entertainment", "names": ["RELX"]},
    {"ticker": "FAST", "label": "Fastenal", "sector": "Industrials", "names": ["Fastenal"]},
    {"ticker": "COHR", "label": "Coherent Corp", "sector": "AI Infrastructure", "names": ["Coherent Corp"]},
    {"ticker": "CVE", "label": "Cenovus", "sector": "Oil & Gas", "names": ["Cenovus"]},
    {"ticker": "ALL", "label": "Allstate", "sector": "Banking & Finance", "names": ["Allstate"], "match_ticker": False},
    {"ticker": "AFL", "label": "Aflac", "sector": "Banking & Finance", "names": ["Aflac"]},
    {"ticker": "VALE", "label": "Vale", "sector": "Metals & Mining", "names": ["Vale"]},
    {"ticker": "TFC", "label": "Truist", "sector": "Banking & Finance", "names": ["Truist"], "exclude": analyst_house("Truist", "Truist Securities")},
    {"ticker": "GRMN", "label": "Garmin", "sector": "Tech Hardware", "names": ["Garmin"]},
    {"ticker": "CRH", "label": "CRH", "sector": "Chemicals & Materials", "names": ["CRH"]},
    {"ticker": "BKR", "label": "Baker Hughes", "sector": "Oil & Gas", "names": ["Baker Hughes"]},
    {"ticker": "LNG", "label": "Cheniere Energy", "sector": "Oil & Gas", "names": ["Cheniere Energy"], "match_ticker": False},
    {"ticker": "OXY", "label": "Occidental Petroleum", "sector": "Oil & Gas", "names": ["Occidental Petroleum", "Occidental"]},
    {"ticker": "OKE", "label": "ONEOK", "sector": "Oil & Gas", "names": ["ONEOK"]},
    {"ticker": "NUE", "label": "Nucor", "sector": "Metals & Mining", "names": ["Nucor"]},
    {"ticker": "PSA", "label": "Public Storage", "sector": "Real Estate / Homebuilders", "names": ["Public Storage"]},
    {"ticker": "D", "label": "Dominion Energy", "sector": "Utilities", "names": ["Dominion Energy"], "match_ticker": False},
    {"ticker": "O", "label": "Realty Income", "sector": "Real Estate / Homebuilders", "names": ["Realty Income"], "match_ticker": False},
    {"ticker": "CTVA", "label": "Corteva", "sector": "Chemicals & Materials", "names": ["Corteva"]},
    {"ticker": "CAH", "label": "Cardinal Health", "sector": "Healthcare", "names": ["Cardinal Health"]},
    {"ticker": "NDAQ", "label": "Nasdaq Inc", "sector": "Banking & Finance", "names": ["Nasdaq Inc", "Nasdaq Inc."]},
    {"ticker": "FANG", "label": "Diamondback Energy", "sector": "Oil & Gas", "names": ["Diamondback Energy"]},
    {"ticker": "MT", "label": "ArcelorMittal", "sector": "Metals & Mining", "names": ["ArcelorMittal"], "match_ticker": False},
    {"ticker": "SRE", "label": "Sempra", "sector": "Utilities", "names": ["Sempra"]},
    {"ticker": "DVN", "label": "Devon Energy", "sector": "Oil & Gas", "names": ["Devon Energy"]},
    {"ticker": "EW", "label": "Edwards Lifesciences", "sector": "Healthcare", "names": ["Edwards Lifesciences"], "match_ticker": False},
    {"ticker": "BDX", "label": "Becton Dickinson", "sector": "Healthcare", "names": ["Becton Dickinson"]},
    {"ticker": "CIEN", "label": "Ciena", "sector": "Tech Hardware", "names": ["Ciena"]},
    {"ticker": "A", "label": "Agilent", "sector": "Healthcare", "names": ["Agilent"], "match_ticker": False},
    {"ticker": "HONA", "label": "Honeywell Aerospace", "sector": "Defense", "names": ["Honeywell Aerospace"]},
    {"ticker": "WAB", "label": "Wabtec", "sector": "Industrials", "names": ["Wabtec", "Westinghouse Air Brake"]},
    {"ticker": "STT", "label": "State Street", "sector": "Banking & Finance", "names": ["State Street"], "exclude": r"(?i)State Street(?:'s)?\s+(?:Global Advisors|Investment Management)|State Street\s+[^.;:()]{0,60}?(?:SPDR|ETF)\b|SPDR[^.;:]{0,60}"},
    {"ticker": "FNV", "label": "Franco-Nevada", "sector": "Metals & Mining", "names": ["Franco-Nevada", "Franco Nevada"]},
    {"ticker": "ROK", "label": "Rockwell Automation", "sector": "Industrials", "names": ["Rockwell Automation"]},
    {"ticker": "AU", "label": "AngloGold Ashanti", "sector": "Metals & Mining", "names": ["AngloGold Ashanti", "AngloGold"], "match_ticker": False},
    {"ticker": "CBRS", "label": "Cerebras Systems", "sector": "Semiconductors", "names": ["Cerebras Systems", "Cerebras"]},
    {"ticker": "STM", "label": "STMicroelectronics", "sector": "Semiconductors", "names": ["STMicroelectronics", "STMicro"]},
    {"ticker": "VST", "label": "Vistra", "sector": "Utilities", "names": ["Vistra"]},
    {"ticker": "ETR", "label": "Entergy", "sector": "Utilities", "names": ["Entergy"]},
    {"ticker": "VMRK", "label": "Vivmark Residential", "sector": "Real Estate / Homebuilders", "names": ["Vivmark Residential", "Vivmark"]},
    {"ticker": "DEO", "label": "Diageo", "sector": "Consumer Goods", "names": ["Diageo"]},
    {"ticker": "EBAY", "label": "eBay", "sector": "Consumer Goods", "names": ["eBay"]},
    {"ticker": "MDLN", "label": "Medline", "sector": "Healthcare", "names": ["Medline"]},
    {"ticker": "TEVA", "label": "Teva", "sector": "Healthcare", "names": ["Teva"]},
    {"ticker": "HUM", "label": "Humana", "sector": "Healthcare", "names": ["Humana"]},
    {"ticker": "CLS", "label": "Celestica", "sector": "Tech Hardware", "names": ["Celestica"]},
    {"ticker": "FITB", "label": "Fifth Third", "sector": "Banking & Finance", "names": ["Fifth Third"]},
    {"ticker": "AZO", "label": "AutoZone", "sector": "Automotive / EV", "names": ["AutoZone"]},
    {"ticker": "CARR", "label": "Carrier Global", "sector": "Industrials", "names": ["Carrier Global"]},
    {"ticker": "WDAY", "label": "Workday", "sector": "Software / Cloud", "names": ["Workday"]},
    {"ticker": "CCEP", "label": "Coca-Cola Europacific", "sector": "Consumer Goods", "names": ["Coca-Cola Europacific"]},
    {"ticker": "RKLB", "label": "Rocket Lab", "sector": "Space", "names": ["Rocket Lab"]},
    {"ticker": "VEEV", "label": "Veeva Systems", "sector": "Software / Cloud", "names": ["Veeva Systems", "Veeva"]},
    {"ticker": "KB", "label": "KB Financial", "sector": "Banking & Finance", "names": ["KB Financial"], "match_ticker": False},
    {"ticker": "XYZ", "label": "Block Inc", "sector": "Payments / Fintech", "names": ["Block Inc", "Cash App"]},
    {"ticker": "ABEV", "label": "Ambev", "sector": "Consumer Goods", "names": ["Ambev"]},
    {"ticker": "IQV", "label": "Iqvia", "sector": "Healthcare", "names": ["Iqvia"]},
    {"ticker": "VTR", "label": "Ventas", "sector": "Real Estate / Homebuilders", "names": ["Ventas"]},
    {"ticker": "TWLO", "label": "Twilio", "sector": "Software / Cloud", "names": ["Twilio"]},
    {"ticker": "XEL", "label": "Xcel Energy", "sector": "Utilities", "names": ["Xcel Energy"]},
    {"ticker": "AMP", "label": "Ameriprise", "sector": "Banking & Finance", "names": ["Ameriprise"]},
    {"ticker": "TEAM", "label": "Atlassian", "sector": "Software / Cloud", "names": ["Atlassian"]},
    {"ticker": "SLF", "label": "Sun Life", "sector": "Banking & Finance", "names": ["Sun Life"]},
    {"ticker": "WAT", "label": "Waters Corp", "sector": "Healthcare", "names": ["Waters Corp"]},
    {"ticker": "FERG", "label": "Ferguson Enterprises", "sector": "Consumer Goods", "names": ["Ferguson Enterprises"]},
    {"ticker": "MCHP", "label": "Microchip Technology", "sector": "Semiconductors", "names": ["Microchip Technology"]},
    {"ticker": "HEI", "label": "Heico", "sector": "Defense", "names": ["Heico"]},
    {"ticker": "INFY", "label": "Infosys", "sector": "Software / Cloud", "names": ["Infosys"]},
    {"ticker": "KDP", "label": "Keurig Dr Pepper", "sector": "Consumer Goods", "names": ["Keurig Dr Pepper", "Keurig"]},
    {"ticker": "IDXX", "label": "Idexx", "sector": "Healthcare", "names": ["Idexx"]},
    {"ticker": "ADSK", "label": "Autodesk", "sector": "Software / Cloud", "names": ["Autodesk"]},
    {"ticker": "FLEX", "label": "Flex Ltd", "sector": "Tech Hardware", "names": ["Flex Ltd"]},
    {"ticker": "HMC", "label": "Honda", "sector": "Automotive / EV", "names": ["Honda"]},
    {"ticker": "EXC", "label": "Exelon", "sector": "Utilities", "names": ["Exelon"]},
    {"ticker": "ONC", "label": "BeOne Medicines", "sector": "Healthcare", "names": ["BeOne Medicines", "BeiGene"]},
    {"ticker": "TRI", "label": "Thomson Reuters", "sector": "Media / Entertainment", "names": ["Thomson Reuters"]},
    {"ticker": "ILMN", "label": "Illumina", "sector": "Healthcare", "names": ["Illumina"]},
    {"ticker": "NTAP", "label": "NetApp", "sector": "Tech Hardware", "names": ["NetApp"]},
    {"ticker": "CMG", "label": "Chipotle", "sector": "Consumer Goods", "names": ["Chipotle"]},
    {"ticker": "FMX", "label": "FEMSA", "sector": "Consumer Goods", "names": ["FEMSA", "Fomento Economico Mexicano"]},
    {"ticker": "LYV", "label": "Live Nation", "sector": "Media / Entertainment", "names": ["Live Nation"]},
    {"ticker": "PRU", "label": "Prudential Financial", "sector": "Banking & Finance", "names": ["Prudential Financial"]},
    {"ticker": "HLN", "label": "Haleon", "sector": "Consumer Goods", "names": ["Haleon"]},
    {"ticker": "IX", "label": "ORIX", "sector": "Banking & Finance", "names": ["ORIX"], "match_ticker": False},
    {"ticker": "ARES", "label": "Ares Management", "sector": "Banking & Finance", "names": ["Ares Management"]},
    {"ticker": "AIG", "label": "AIG", "sector": "Banking & Finance", "names": ["AIG", "American International Group"]},
    {"ticker": "FER", "label": "Ferrovial", "sector": "Industrials", "names": ["Ferrovial"]},
    {"ticker": "DHI", "label": "D.R. Horton", "sector": "Real Estate / Homebuilders", "names": ["D.R. Horton", "DR Horton"]},
    {"ticker": "WCN", "label": "Waste Connections", "sector": "Industrials", "names": ["Waste Connections"]},
    {"ticker": "MSCI", "label": "MSCI", "sector": "Banking & Finance", "names": ["MSCI"], "exclude": r"(?:iShares|Xtrackers|SPDR|Vanguard|Franklin|Invesco|Direxion|Daily|ProShares|Global X)\s[^.;:]{0,40}?MSCI\b|\bMSCI\s+(?:ACWI|EAFE|EM\b|Emerging|World|USA|Japan|China|India|Europe|All\s+Country|Frontier|Global|Kokusai|Min\s+Vol|South\s+Korea|Korea|Brazil|Taiwan|Mexico|Canada|Germany|UK|Pacific|Asia|ex-?US|Small|Value|Growth|Momentum|Quality|Dividend|ESG|Climate|Index|indices|indexes|ETF)"},
    {"ticker": "ADM", "label": "Archer-Daniels-Midland", "sector": "Consumer Goods", "names": ["Archer-Daniels-Midland", "Archer Daniels Midland"]},
    {"ticker": "SHG", "label": "Shinhan", "sector": "Banking & Finance", "names": ["Shinhan"]},
    {"ticker": "ED", "label": "Consolidated Edison", "sector": "Utilities", "names": ["Consolidated Edison", "Con Edison", "ConEd"], "match_ticker": False},
    {"ticker": "CCJ", "label": "Cameco", "sector": "Metals & Mining", "names": ["Cameco"]},
    {"ticker": "TTWO", "label": "Take-Two Interactive", "sector": "Media / Entertainment", "names": ["Take-Two Interactive", "Take-Two"]},
    {"ticker": "CBRE", "label": "CBRE", "sector": "Real Estate / Homebuilders", "names": ["CBRE"]},
    {"ticker": "VOD", "label": "Vodafone", "sector": "Telecom", "names": ["Vodafone"]},
    {"ticker": "SYY", "label": "Sysco", "sector": "Consumer Goods", "names": ["Sysco"]},
    {"ticker": "YUM", "label": "Yum Brands", "sector": "Consumer Goods", "names": ["Yum Brands", "Yum! Brands"]},
    {"ticker": "ODFL", "label": "Old Dominion Freight", "sector": "Industrials", "names": ["Old Dominion Freight"]},
    {"ticker": "CRDO", "label": "Credo Technology", "sector": "Semiconductors", "names": ["Credo Technology"]},
    {"ticker": "PCG", "label": "PG&E", "sector": "Utilities", "names": ["PG&E"]},
    {"ticker": "KR", "label": "Kroger", "sector": "Consumer Goods", "names": ["Kroger"], "match_ticker": False},
    {"ticker": "JD", "label": "JD.com", "sector": "Consumer Goods", "names": ["JD.com"], "match_ticker": False},
    {"ticker": "OKTA", "label": "Okta", "sector": "Cybersecurity", "names": ["Okta"]},
    {"ticker": "BBD", "label": "Bradesco", "sector": "Banking & Finance", "names": ["Bradesco"]},
    {"ticker": "VIK", "label": "Viking Holdings", "sector": "Airlines / Travel", "names": ["Viking Holdings", "Viking Cruises"]},
    {"ticker": "CHT", "label": "Chunghwa Telecom", "sector": "Telecom", "names": ["Chunghwa Telecom", "Chunghwa"]},
    {"ticker": "PAYX", "label": "Paychex", "sector": "Software / Cloud", "names": ["Paychex"]},
    {"ticker": "CCL", "label": "Carnival Corp", "sector": "Airlines / Travel", "names": ["Carnival Corp", "Carnival Cruise"]},
    {"ticker": "ROP", "label": "Roper Technologies", "sector": "Industrials", "names": ["Roper Technologies"]},
    {"ticker": "EL", "label": "Estee Lauder", "sector": "Consumer Goods", "names": ["Estee Lauder", "Estée Lauder"], "match_ticker": False},
    {"ticker": "KVUE", "label": "Kenvue", "sector": "Consumer Goods", "names": ["Kenvue"]},
    {"ticker": "NTR", "label": "Nutrien", "sector": "Chemicals & Materials", "names": ["Nutrien"]},
    {"ticker": "EC", "label": "Ecopetrol", "sector": "Oil & Gas", "names": ["Ecopetrol"], "match_ticker": False},
    {"ticker": "AXON", "label": "Axon Enterprise", "sector": "Defense", "names": ["Axon Enterprise", "Axon"]},
    {"ticker": "HIG", "label": "The Hartford", "sector": "Banking & Finance", "names": ["The Hartford", "Hartford Financial"]},
    {"ticker": "UI", "label": "Ubiquiti", "sector": "Tech Hardware", "names": ["Ubiquiti"], "match_ticker": False},
    {"ticker": "ALNY", "label": "Alnylam", "sector": "Healthcare", "names": ["Alnylam"]},
    {"ticker": "TKO", "label": "TKO Group", "sector": "Media / Entertainment", "names": ["TKO Group"]},
    {"ticker": "MLM", "label": "Martin Marietta Materials", "sector": "Metals & Mining", "names": ["Martin Marietta Materials"]},
    {"ticker": "RPRX", "label": "Royalty Pharma", "sector": "Healthcare", "names": ["Royalty Pharma"]},
    {"ticker": "PEG", "label": "PSEG", "sector": "Utilities", "names": ["PSEG", "Public Service Enterprise"]},
    {"ticker": "EME", "label": "EMCOR", "sector": "Industrials", "names": ["EMCOR"]},
    {"ticker": "BIIB", "label": "Biogen", "sector": "Healthcare", "names": ["Biogen"]},
    {"ticker": "WEC", "label": "WEC Energy", "sector": "Utilities", "names": ["WEC Energy"]},
    {"ticker": "RKT", "label": "Rocket Companies", "sector": "Banking & Finance", "names": ["Rocket Companies", "Rocket Mortgage"]},
    {"ticker": "JBL", "label": "Jabil", "sector": "Tech Hardware", "names": ["Jabil"]},
    {"ticker": "IRM", "label": "Iron Mountain", "sector": "Real Estate / Homebuilders", "names": ["Iron Mountain"]},
    {"ticker": "KMB", "label": "Kimberly-Clark", "sector": "Consumer Goods", "names": ["Kimberly-Clark", "Kimberly Clark"]},
    {"ticker": "ESLT", "label": "Elbit Systems", "sector": "Defense", "names": ["Elbit Systems", "Elbit"]},
    {"ticker": "QSR", "label": "Restaurant Brands International", "sector": "Consumer Goods", "names": ["Restaurant Brands International"]},
    {"ticker": "GFI", "label": "Gold Fields", "sector": "Metals & Mining", "names": ["Gold Fields"], "context": {"Gold Fields": "."}},
    {"ticker": "DXCM", "label": "Dexcom", "sector": "Healthcare", "names": ["Dexcom"]},
    {"ticker": "HSY", "label": "Hershey", "sector": "Consumer Goods", "names": ["Hershey"]},
    {"ticker": "ACGL", "label": "Arch Capital", "sector": "Banking & Finance", "names": ["Arch Capital"]},
    {"ticker": "ZS", "label": "Zscaler", "sector": "Cybersecurity", "names": ["Zscaler"], "match_ticker": False},
    {"ticker": "RMD", "label": "ResMed", "sector": "Healthcare", "names": ["ResMed"]},
    {"ticker": "TECK", "label": "Teck Resources", "sector": "Metals & Mining", "names": ["Teck Resources"]},
    {"ticker": "STLD", "label": "Steel Dynamics", "sector": "Metals & Mining", "names": ["Steel Dynamics"]},
    {"ticker": "EXPE", "label": "Expedia", "sector": "Airlines / Travel", "names": ["Expedia"]},
    {"ticker": "ALC", "label": "Alcon", "sector": "Healthcare", "names": ["Alcon"]},
    {"ticker": "MTB", "label": "M&T Bank", "sector": "Banking & Finance", "names": ["M&T Bank"]},
    {"ticker": "VMC", "label": "Vulcan Materials", "sector": "Metals & Mining", "names": ["Vulcan Materials"]},
    {"ticker": "PUK", "label": "Prudential plc", "sector": "Banking & Finance", "names": ["Prudential plc"]},
    {"ticker": "VG", "label": "Venture Global", "sector": "Utilities", "names": ["Venture Global"], "match_ticker": False},
    {"ticker": "HBAN", "label": "Huntington Bancshares", "sector": "Banking & Finance", "names": ["Huntington Bancshares", "Huntington Bank"]},
    {"ticker": "MTD", "label": "Mettler-Toledo", "sector": "Healthcare", "names": ["Mettler-Toledo", "Mettler Toledo"]},
    {"ticker": "BAP", "label": "Credicorp", "sector": "Banking & Finance", "names": ["Credicorp"]},
    {"ticker": "RJF", "label": "Raymond James", "sector": "Banking & Finance", "names": ["Raymond James"], "exclude": analyst_house("Raymond James")},
    {"ticker": "CNC", "label": "Centene", "sector": "Healthcare", "names": ["Centene"]},
    {"ticker": "EQT", "label": "EQT Corp", "sector": "Oil & Gas", "names": ["EQT Corp"], "match_ticker": False},
    {"ticker": "ERIC", "label": "Ericsson", "sector": "Tech Hardware", "names": ["Ericsson"]},
    {"ticker": "SUNB", "label": "Sunbelt Rentals", "sector": "Industrials", "names": ["Sunbelt Rentals"]},
    {"ticker": "GEHC", "label": "GE HealthCare", "sector": "Healthcare", "names": ["GE HealthCare"]},
    {"ticker": "IR", "label": "Ingersoll Rand", "sector": "Industrials", "names": ["Ingersoll Rand"], "match_ticker": False},
    {"ticker": "BIDU", "label": "Baidu", "sector": "Software / Cloud", "names": ["Baidu"]},
    {"ticker": "RBLX", "label": "Roblox", "sector": "Software / Cloud", "names": ["Roblox"]},
    {"ticker": "EXR", "label": "Extra Space Storage", "sector": "Real Estate / Homebuilders", "names": ["Extra Space Storage"]},
    {"ticker": "CCI", "label": "Crown Castle", "sector": "Real Estate / Homebuilders", "names": ["Crown Castle"]},
    {"ticker": "NMR", "label": "Nomura", "sector": "Banking & Finance", "names": ["Nomura"], "exclude": analyst_house("Nomura")},
    {"ticker": "KGC", "label": "Kinross", "sector": "Metals & Mining", "names": ["Kinross"]},
    {"ticker": "RYAAY", "label": "Ryanair", "sector": "Airlines / Travel", "names": ["Ryanair"]},
    {"ticker": "TDY", "label": "Teledyne", "sector": "Defense", "names": ["Teledyne"]},
    {"ticker": "TS", "label": "Tenaris", "sector": "Metals & Mining", "names": ["Tenaris"], "match_ticker": False},
    {"ticker": "KHC", "label": "Kraft Heinz", "sector": "Consumer Goods", "names": ["Kraft Heinz"]},
    {"ticker": "AEE", "label": "Ameren", "sector": "Utilities", "names": ["Ameren"]},
    {"ticker": "WSM", "label": "Williams-Sonoma", "sector": "Consumer Goods", "names": ["Williams-Sonoma", "Williams Sonoma"]},
    {"ticker": "DG", "label": "Dollar General", "sector": "Consumer Goods", "names": ["Dollar General"], "match_ticker": False},
    {"ticker": "FTS", "label": "Fortis Inc", "sector": "Utilities", "names": ["Fortis Inc"]},
    {"ticker": "CFG", "label": "Citizens Financial", "sector": "Banking & Finance", "names": ["Citizens Financial"], "exclude": analyst_house("Citizens", "Citizens JMP")},
    {"ticker": "FTI", "label": "TechnipFMC", "sector": "Oil & Gas", "names": ["TechnipFMC"]},
    {"ticker": "WTW", "label": "Willis Towers Watson", "sector": "Banking & Finance", "names": ["Willis Towers Watson", "WTW"]},
    {"ticker": "MDB", "label": "MongoDB", "sector": "Software / Cloud", "names": ["MongoDB"]},
    {"ticker": "ATO", "label": "Atmos Energy", "sector": "Utilities", "names": ["Atmos Energy"]},
    {"ticker": "GFS", "label": "GlobalFoundries", "sector": "Semiconductors", "names": ["GlobalFoundries"]},
    {"ticker": "TSEM", "label": "Tower Semiconductor", "sector": "Semiconductors", "names": ["Tower Semiconductor"]},
    {"ticker": "WST", "label": "West Pharmaceutical Services", "sector": "Healthcare", "names": ["West Pharmaceutical Services"]},
    {"ticker": "HAL", "label": "Halliburton", "sector": "Oil & Gas", "names": ["Halliburton"]},
    {"ticker": "FOXA", "label": "Fox Corp", "sector": "Media / Entertainment", "names": ["Fox Corp", "Fox Corporation"]},
    {"ticker": "Q", "label": "Qnity", "sector": "Semiconductors", "names": ["Qnity"], "match_ticker": False},
    {"ticker": "ECHO", "label": "EchoStar", "sector": "Telecom", "names": ["EchoStar"]},
    {"ticker": "NVT", "label": "nVent", "sector": "Industrials", "names": ["nVent"]},
    {"ticker": "ROIV", "label": "Roivant Sciences", "sector": "Healthcare", "names": ["Roivant Sciences", "Roivant"]},
    {"ticker": "AWK", "label": "American Water Works", "sector": "Utilities", "names": ["American Water Works"]},
    {"ticker": "CPAY", "label": "Corpay", "sector": "Payments / Fintech", "names": ["Corpay"]},
    {"ticker": "SN", "label": "SharkNinja", "sector": "Consumer Goods", "names": ["SharkNinja"], "match_ticker": False},
    {"ticker": "PBA", "label": "Pembina", "sector": "Oil & Gas", "names": ["Pembina"]},
    {"ticker": "DGX", "label": "Quest Diagnostics", "sector": "Healthcare", "names": ["Quest Diagnostics"]},
    {"ticker": "ZM", "label": "Zoom Communications", "sector": "Software / Cloud", "names": ["Zoom Communications", "Zoom Video"], "match_ticker": False},
    {"ticker": "ATI", "label": "ATI Inc", "sector": "Metals & Mining", "names": ["ATI Inc"]},
    {"ticker": "VICI", "label": "Vici Properties", "sector": "Real Estate / Homebuilders", "names": ["Vici Properties"]},
    {"ticker": "DOV", "label": "Dover Corp", "sector": "Industrials", "names": ["Dover Corp"]},
    {"ticker": "DTE", "label": "DTE Energy", "sector": "Utilities", "names": ["DTE Energy"]},
    {"ticker": "CTSH", "label": "Cognizant Technology Solutions", "sector": "Software / Cloud", "names": ["Cognizant Technology Solutions", "Cognizant"]},
    {"ticker": "VRSN", "label": "VeriSign", "sector": "Software / Cloud", "names": ["VeriSign"]},
    {"ticker": "INSM", "label": "Insmed", "sector": "Healthcare", "names": ["Insmed"]},
    {"ticker": "WRB", "label": "W. R. Berkley", "sector": "Banking & Finance", "names": ["W. R. Berkley", "W.R. Berkley"]},
    {"ticker": "SYM", "label": "Symbotic", "sector": "Industrials", "names": ["Symbotic"]},
    {"ticker": "FE", "label": "FirstEnergy", "sector": "Utilities", "names": ["FirstEnergy"], "match_ticker": False},
    {"ticker": "CPRT", "label": "Copart", "sector": "Automotive / EV", "names": ["Copart"]},
    {"ticker": "INCY", "label": "Incyte", "sector": "Healthcare", "names": ["Incyte"]},
    {"ticker": "LH", "label": "Labcorp", "sector": "Healthcare", "names": ["Labcorp"], "match_ticker": False},
    {"ticker": "FFIV", "label": "F5 Inc", "sector": "Tech Hardware", "names": ["F5 Inc", "F5 Networks"]},
    {"ticker": "CPNG", "label": "Coupang", "sector": "Consumer Goods", "names": ["Coupang"]},
    {"ticker": "OTIS", "label": "Otis Worldwide", "sector": "Industrials", "names": ["Otis Worldwide", "Otis Elevator"]},
    {"ticker": "BNTX", "label": "BioNTech", "sector": "Healthcare", "names": ["BioNTech"]},
    {"ticker": "CINF", "label": "Cincinnati Financial", "sector": "Banking & Finance", "names": ["Cincinnati Financial"]},
    {"ticker": "EXPD", "label": "Expeditors International", "sector": "Industrials", "names": ["Expeditors International", "Expeditors"]},
    {"ticker": "LPLA", "label": "LPL Financial", "sector": "Banking & Finance", "names": ["LPL Financial"]},
    {"ticker": "PPL", "label": "PPL Corp", "sector": "Utilities", "names": ["PPL Corp"]},
    {"ticker": "PFG", "label": "Principal Financial", "sector": "Banking & Finance", "names": ["Principal Financial"]},
    {"ticker": "CNP", "label": "CenterPoint Energy", "sector": "Utilities", "names": ["CenterPoint Energy"]},
    {"ticker": "HUBB", "label": "Hubbell", "sector": "Industrials", "names": ["Hubbell"]},
    {"ticker": "FISV", "label": "Fiserv", "sector": "Payments / Fintech", "names": ["Fiserv"]},
    {"ticker": "PHG", "label": "Philips", "sector": "Healthcare", "names": ["Philips"]},
    {"ticker": "ES", "label": "Eversource", "sector": "Utilities", "names": ["Eversource"], "match_ticker": False},
    {"ticker": "IHG", "label": "IHG Hotels", "sector": "Airlines / Travel", "names": ["IHG Hotels", "InterContinental Hotels"]},
    {"ticker": "ENTG", "label": "Entegris", "sector": "Semiconductors", "names": ["Entegris"]},
    {"ticker": "GH", "label": "Guardant Health", "sector": "Healthcare", "names": ["Guardant Health"], "match_ticker": False},
    {"ticker": "XYL", "label": "Xylem", "sector": "Industrials", "names": ["Xylem"]},
    {"ticker": "PPG", "label": "PPG Industries", "sector": "Chemicals & Materials", "names": ["PPG Industries"]},
    {"ticker": "ULTA", "label": "Ulta Beauty", "sector": "Consumer Goods", "names": ["Ulta Beauty"]},
    {"ticker": "VLTO", "label": "Veralto", "sector": "Industrials", "names": ["Veralto"]},
    {"ticker": "AFRM", "label": "Affirm", "sector": "Payments / Fintech", "names": ["Affirm"]},
    {"ticker": "RBRK", "label": "Rubrik", "sector": "Software / Cloud", "names": ["Rubrik"]},
    {"ticker": "FCNCA", "label": "First Citizens Bancshares", "sector": "Banking & Finance", "names": ["First Citizens Bancshares"]},
    {"ticker": "SYF", "label": "Synchrony", "sector": "Banking & Finance", "names": ["Synchrony"]},
    {"ticker": "SW", "label": "Smurfit Westrock", "sector": "Chemicals & Materials", "names": ["Smurfit Westrock", "Smurfit"], "match_ticker": False},
    {"ticker": "ASTS", "label": "AST SpaceMobile", "sector": "Space", "names": ["AST SpaceMobile"]},
    {"ticker": "RF", "label": "Regions Financial", "sector": "Banking & Finance", "names": ["Regions Financial"], "match_ticker": False},
    {"ticker": "AER", "label": "AerCap", "sector": "Industrials", "names": ["AerCap"]},
    {"ticker": "TPL", "label": "Texas Pacific Land", "sector": "Oil & Gas", "names": ["Texas Pacific Land"]},
    {"ticker": "CHD", "label": "Church & Dwight", "sector": "Consumer Goods", "names": ["Church & Dwight"]},
    {"ticker": "ROKU", "label": "Roku", "sector": "Media / Entertainment", "names": ["Roku"]},
    {"ticker": "PHM", "label": "PulteGroup", "sector": "Real Estate / Homebuilders", "names": ["PulteGroup"]},
    {"ticker": "TPR", "label": "Tapestry Inc", "sector": "Consumer Goods", "names": ["Tapestry Inc"]},
    {"ticker": "CASY", "label": "Casey's General Stores", "sector": "Consumer Goods", "names": ["Casey's General Stores", "Casey's"]},
    {"ticker": "TROW", "label": "T. Rowe Price", "sector": "Banking & Finance", "names": ["T. Rowe Price", "T Rowe Price"]},
    {"ticker": "CIB", "label": "Grupo Cibest", "sector": "Banking & Finance", "names": ["Grupo Cibest", "Bancolombia"]},
    {"ticker": "GPN", "label": "Global Payments", "sector": "Payments / Fintech", "names": ["Global Payments"]},
    {"ticker": "DRI", "label": "Darden Restaurants", "sector": "Consumer Goods", "names": ["Darden Restaurants", "Darden"]},
    {"ticker": "IOT", "label": "Samsara", "sector": "Software / Cloud", "names": ["Samsara"], "match_ticker": False},
    {"ticker": "GMAB", "label": "Genmab", "sector": "Healthcare", "names": ["Genmab"]},
    {"ticker": "IFF", "label": "International Flavors & Fragrances", "sector": "Chemicals & Materials", "names": ["International Flavors & Fragrances"]},
    {"ticker": "PS", "label": "Pershing Square", "sector": "Banking & Finance", "names": ["Pershing Square"], "match_ticker": False},
    {"ticker": "MTSI", "label": "MACOM", "sector": "Semiconductors", "names": ["MACOM"]},
    {"ticker": "TW", "label": "Tradeweb", "sector": "Banking & Finance", "names": ["Tradeweb"], "match_ticker": False},
    {"ticker": "L", "label": "Loews", "sector": "Banking & Finance", "names": ["Loews"], "match_ticker": False},
    {"ticker": "MKL", "label": "Markel", "sector": "Banking & Finance", "names": ["Markel"]},
    {"ticker": "KEY", "label": "KeyCorp", "sector": "Banking & Finance", "names": ["KeyCorp"], "match_ticker": False},
    {"ticker": "VRSK", "label": "Verisk", "sector": "Software / Cloud", "names": ["Verisk"]},
    {"ticker": "JBHT", "label": "J.B. Hunt", "sector": "Industrials", "names": ["J.B. Hunt", "JB Hunt"]},
    {"ticker": "FWONA", "label": "Liberty Media", "sector": "Media / Entertainment", "names": ["Liberty Media"]},
    {"ticker": "DLTR", "label": "Dollar Tree", "sector": "Consumer Goods", "names": ["Dollar Tree"]},
    {"ticker": "CNH", "label": "CNH Industrial", "sector": "Industrials", "names": ["CNH Industrial"]},
    {"ticker": "ARXS", "label": "Arxis", "sector": "Defense", "names": ["Arxis"]},
    {"ticker": "RL", "label": "Ralph Lauren", "sector": "Consumer Goods", "names": ["Ralph Lauren"], "match_ticker": False},
    {"ticker": "BG", "label": "Bunge", "sector": "Consumer Goods", "names": ["Bunge"], "match_ticker": False},
    {"ticker": "XPO", "label": "XPO", "sector": "Industrials", "names": ["XPO"]},
    {"ticker": "PKG", "label": "Packaging Corp of America", "sector": "Chemicals & Materials", "names": ["Packaging Corp of America"]},
    {"ticker": "BSP", "label": "Bending Spoons", "sector": "Software / Cloud", "names": ["Bending Spoons"]},
    {"ticker": "VTRS", "label": "Viatris", "sector": "Healthcare", "names": ["Viatris"]},
    {"ticker": "SOFI", "label": "SoFi", "sector": "Payments / Fintech", "names": ["SoFi"]},
    {"ticker": "AMRZ", "label": "Amrize", "sector": "Chemicals & Materials", "names": ["Amrize"]},
    {"ticker": "THC", "label": "Tenet Healthcare", "sector": "Healthcare", "names": ["Tenet Healthcare"]},
    {"ticker": "LUV", "label": "Southwest Airlines", "sector": "Airlines / Travel", "names": ["Southwest Airlines"]},
    {"ticker": "NRG", "label": "NRG Energy", "sector": "Utilities", "names": ["NRG Energy"]},
    {"ticker": "UTHR", "label": "United Therapeutics", "sector": "Healthcare", "names": ["United Therapeutics"]},
    {"ticker": "RGLD", "label": "Royal Gold", "sector": "Metals & Mining", "names": ["Royal Gold"]},
    {"ticker": "STE", "label": "Steris", "sector": "Healthcare", "names": ["Steris"]},
    {"ticker": "EIX", "label": "Edison International", "sector": "Utilities", "names": ["Edison International", "Southern California Edison"]},
    {"ticker": "BCH", "label": "Banco de Chile", "sector": "Banking & Finance", "names": ["Banco de Chile", "Bank of Chile"]},
    {"ticker": "OMC", "label": "Omnicom", "sector": "Media / Entertainment", "names": ["Omnicom"]},
    {"ticker": "BRO", "label": "Brown & Brown", "sector": "Banking & Finance", "names": ["Brown & Brown"]},
    {"ticker": "USFD", "label": "US Foods", "sector": "Consumer Goods", "names": ["US Foods"]},
    {"ticker": "DOW", "label": "Dow Inc", "sector": "Chemicals & Materials", "names": ["Dow Inc", "Dow Chemical"], "match_ticker": False},
    {"ticker": "CMS", "label": "CMS Energy", "sector": "Utilities", "names": ["CMS Energy"]},
    {"ticker": "RS", "label": "Reliance Steel", "sector": "Consumer Goods", "names": ["Reliance Steel"], "match_ticker": False},
    {"ticker": "CW", "label": "Curtiss-Wright", "sector": "Industrials", "names": ["Curtiss-Wright"], "match_ticker": False},
    {"ticker": "AMCR", "label": "Amcor", "sector": "Chemicals & Materials", "names": ["Amcor"]},
    {"ticker": "YPF", "label": "YPF Sociedad Anonima", "sector": "Oil & Gas", "names": ["YPF Sociedad Anonima"]},
    {"ticker": "SITM", "label": "SiTime", "sector": "Semiconductors", "names": ["SiTime"]},
    {"ticker": "HSAI", "label": "Hesai", "sector": "Industrials", "names": ["Hesai"]},
    {"ticker": "CRS", "label": "Carpenter Technology", "sector": "Metals & Mining", "names": ["Carpenter Technology"]},
    {"ticker": "WF", "label": "Woori Financial", "sector": "Banking & Finance", "names": ["Woori Financial"], "match_ticker": False},
    {"ticker": "WWD", "label": "Woodward Inc", "sector": "Industrials", "names": ["Woodward Inc"]},
    {"ticker": "EXE", "label": "Expand Energy", "sector": "Oil & Gas", "names": ["Expand Energy"]},
    {"ticker": "STZ", "label": "Constellation Brands", "sector": "Consumer Goods", "names": ["Constellation Brands"]},
    {"ticker": "PAAS", "label": "Pan American Silver", "sector": "Metals & Mining", "names": ["Pan American Silver"]},
    {"ticker": "SNA", "label": "Snap-on", "sector": "Industrials", "names": ["Snap-on"]},
    {"ticker": "BCE", "label": "BCE", "sector": "Telecom", "names": []},
    {"ticker": "DINO", "label": "HF Sinclair", "sector": "Oil & Gas", "names": ["HF Sinclair"]},
    {"ticker": "SQM", "label": "SQM", "sector": "Metals & Mining", "names": ["SQM", "Sociedad Quimica y Minera"]},
    {"ticker": "FSLR", "label": "First Solar", "sector": "Utilities", "names": ["First Solar"]},
    {"ticker": "NI", "label": "NiSource", "sector": "Utilities", "names": ["NiSource"], "match_ticker": False},
    {"ticker": "NTNX", "label": "Nutanix", "sector": "Software / Cloud", "names": ["Nutanix"]},
    {"ticker": "LYB", "label": "LyondellBasell Industries", "sector": "Chemicals & Materials", "names": ["LyondellBasell Industries", "LyondellBasell"]},
    {"ticker": "BBY", "label": "Best Buy", "sector": "Consumer Goods", "names": ["Best Buy"]},
    {"ticker": "WES", "label": "Western Midstream Partners", "sector": "Oil & Gas", "names": ["Western Midstream Partners"]},
    {"ticker": "ONTO", "label": "Onto Innovation", "sector": "Industrials", "names": ["Onto Innovation"]},
    {"ticker": "NDSN", "label": "Nordson", "sector": "Industrials", "names": ["Nordson"]},
    {"ticker": "BR", "label": "Broadridge", "sector": "Software / Cloud", "names": ["Broadridge"], "match_ticker": False},
    {"ticker": "BEKE", "label": "KE Holdings", "sector": "Real Estate / Homebuilders", "names": ["KE Holdings", "Beike"]},
    {"ticker": "CDE", "label": "Coeur Mining", "sector": "Metals & Mining", "names": ["Coeur Mining"]},
    {"ticker": "SBS", "label": "Sabesp", "sector": "Utilities", "names": ["Sabesp"]},
    {"ticker": "VIV", "label": "Telefonica Brasil", "sector": "Telecom", "names": ["Telefonica Brasil"]},
    {"ticker": "SSNC", "label": "SS&C Technologies", "sector": "Software / Cloud", "names": ["SS&C Technologies"]},
    {"ticker": "KSPI", "label": "Kaspi", "sector": "Payments / Fintech", "names": ["Kaspi"]},
]
