// This file is auto-generated by fetch_news.py — do not edit by hand
const NEWS_DATA = {
  "generated_at": "2026-09-28T20:40:05.590503+00:00",
  "generated_at_display": "28.09.2026 20:40",
  "summary": {
    "total": 80,
    "signal_total": 64,
    "macro_total": 16,
    "positive": 26,
    "negative": 26,
    "neutral": 12,
    "top_tickers": [
      {
        "ticker": "NVDA",
        "count": 5
      },
      {
        "ticker": "META",
        "count": 5
      },
      {
        "ticker": "DJI",
        "count": 3
      },
      {
        "ticker": "BTC",
        "count": 2
      },
      {
        "ticker": "UST10Y",
        "count": 2
      },
      {
        "ticker": "AVGO",
        "count": 2
      }
    ],
    "sectors": [
      "AI Infrastructure",
      "Automotive / EV",
      "Banking & Finance",
      "Big Tech",
      "Bonds / Macro",
      "Consumer Goods",
      "Cryptocurrencies",
      "Defense",
      "ETFs / Indices",
      "Media / Entertainment",
      "Oil & Gas",
      "Semiconductors",
      "Software / Cloud",
      "Space"
    ],
    "source_counts": {
      "CNBC": 22,
      "Yahoo Finance": 20,
      "Investing.com": 10,
      "Nasdaq": 15,
      "MarketWatch": 9,
      "CoinDesk": 3,
      "Mining.com": 1
    }
  },
  "indices": [
    {
      "name": "S&P 500",
      "symbol": "^GSPC",
      "unit": "index",
      "price": 7683.69,
      "change_abs": -81.01,
      "change_pct": -1.04,
      "spark": [
        7679.2798,
        7678.2598,
        7684.5,
        7683.3901,
        7716.9102,
        7699.54,
        7701.2402,
        7717.5298,
        7699.6699,
        7701.04,
        7702.3599,
        7703.7402,
        7698.5,
        7700.27,
        7698.98,
        7688.2402,
        7689.1099,
        7683.52,
        7684.5,
        7683.6899
      ]
    },
    {
      "name": "Dow Jones",
      "symbol": "^DJI",
      "unit": "index",
      "price": 51481.51,
      "change_abs": -567.32,
      "change_pct": -1.09,
      "spark": [
        51440.6797,
        51459.8789,
        51471.2383,
        51478.7812,
        51704.7305,
        51578.0781,
        51591.0508,
        51717.2617,
        51594.5703,
        51619.3711,
        51610.8398,
        51615.5195,
        51565.8711,
        51567.8711,
        51551.8281,
        51495.0898,
        51503.8008,
        51493.8789,
        51485.6406,
        51481.5117
      ]
    },
    {
      "name": "Nasdaq Composite",
      "symbol": "^IXIC",
      "unit": "index",
      "price": 26820.38,
      "change_abs": -301.71,
      "change_pct": -1.11,
      "spark": [
        26809.8672,
        26789.1543,
        26830.209,
        26820.668,
        26959.9902,
        26886.5781,
        26892.0273,
        26962.6133,
        26891.9355,
        26899.7812,
        26899.877,
        26909.8867,
        26891.8809,
        26900.4902,
        26899.334,
        26845.1523,
        26850.8262,
        26821.0449,
        26822.0938,
        26820.3809
      ]
    },
    {
      "name": "Russell 2000",
      "symbol": "^RUT",
      "unit": "index",
      "price": 2817.91,
      "change_abs": -57.45,
      "change_pct": -2.0,
      "spark": [
        2808.8796,
        2809.2083,
        2810.1489,
        2811.5383,
        2829.4668,
        2821.0896,
        2819.9241,
        2831.4543,
        2825.241,
        2823.8552,
        2824.822,
        2826.6111,
        2825.7686,
        2825.7874,
        2825.7886,
        2820.1587,
        2821.5459,
        2821.0208,
        2818.3816,
        2817.9124
      ]
    },
    {
      "name": "FTSE 100 (UK)",
      "symbol": "^FTSE",
      "unit": "index",
      "price": 10684.88,
      "change_abs": -54.12,
      "change_pct": -0.5,
      "spark": [
        10723.3799,
        10730.4102,
        10725.1904,
        10727.9902,
        10733.1299,
        10740.0898,
        10743.8799,
        10744.1104,
        10746.75,
        10738.5,
        10725.0098,
        10741.1396,
        10755.8701,
        10746.7803,
        10753.5596,
        10739.29,
        10722.3799,
        10709.6904,
        10700.4404,
        10684.8799
      ]
    },
    {
      "name": "DAX (Germany)",
      "symbol": "^GDAXI",
      "unit": "index",
      "price": 25374.42,
      "change_abs": -200.59,
      "change_pct": -0.78,
      "spark": [
        25378.5,
        25397.5605,
        25415.5508,
        25418.2305,
        25408.3496,
        25442.4199,
        25459.75,
        25475.9004,
        25511.3203,
        25481.2305,
        25457.1992,
        25492.6309,
        25543.5195,
        25530.5703,
        25550.2598,
        25490.3691,
        25448.0508,
        25415.6309,
        25404.3906,
        25374.4199
      ]
    },
    {
      "name": "Euro Stoxx 50",
      "symbol": "^STOXX50E",
      "unit": "index",
      "price": 6301.28,
      "change_abs": -23.44,
      "change_pct": -0.37,
      "spark": [
        6298.9399,
        6303.2202,
        6307.5801,
        6309.9502,
        6307.5801,
        6316.7798,
        6323.0098,
        6328.4502,
        6337.2798,
        6329.7998,
        6327.1001,
        6335.96,
        6345.7002,
        6336.4199,
        6338.8101,
        6324.7798,
        6314.9502,
        6310.0698,
        6308.1602,
        6301.2798
      ]
    },
    {
      "name": "Nikkei 225 (Japan)",
      "symbol": "^N225",
      "unit": "index",
      "price": 65877.62,
      "change_abs": 1741.37,
      "change_pct": 2.72,
      "spark": [
        66467.2969,
        66494.5781,
        66446.6328,
        66388.1797,
        66398.5391,
        66340.1562,
        66333.5312,
        66227.25,
        66244.7266,
        66379.1328,
        66360.5312,
        66328.7422,
        66301.8125,
        66321.2109,
        66244.3438,
        66175.0625,
        66264.7188,
        66168.4922,
        65995.7969,
        65877.6172
      ]
    },
    {
      "name": "Hang Seng (Hong Kong)",
      "symbol": "^HSI",
      "unit": "index",
      "price": 24642.51,
      "change_abs": -400.2,
      "change_pct": -1.6,
      "spark": [
        24678.6992,
        24681.9902,
        24694.2305,
        24702.2207,
        24690.5996,
        24667.2891,
        24666.0898,
        24689.6309,
        24675.7598,
        24642.9902,
        24662.9805,
        24699.8809,
        24695.2402,
        24687.6797,
        24686.0605,
        24654.6699,
        24647.7598,
        24639.9805,
        24659.7207,
        24642.5098
      ]
    },
    {
      "name": "Gold (futures)",
      "symbol": "GC=F",
      "unit": "index",
      "price": 4150.9,
      "change_abs": -167.5,
      "change_pct": -3.88,
      "spark": [
        4149.5,
        4176.0,
        4164.7998,
        4162.3999,
        4174.7998,
        4168.3999,
        4169.8999,
        4167.2998,
        4168.7002,
        4167.7002,
        4171.2002,
        4172.0,
        4165.8999,
        4167.0,
        4162.5,
        4156.2998,
        4154.6001,
        4150.7002,
        4151.0,
        4150.8999
      ]
    },
    {
      "name": "WTI Crude Oil (futures)",
      "symbol": "CL=F",
      "unit": "index",
      "price": 93.24,
      "change_abs": 1.08,
      "change_pct": 1.17,
      "spark": [
        94.51,
        92.27,
        93.14,
        93.1,
        91.29,
        92.84,
        92.68,
        92.78,
        92.28,
        92.56,
        92.4,
        92.55,
        92.8,
        92.92,
        92.77,
        93.23,
        92.92,
        93.23,
        93.29,
        93.24
      ]
    },
    {
      "name": "Bitcoin",
      "symbol": "BTC-USD",
      "unit": "index",
      "price": 83516.78,
      "change_abs": -862.28,
      "change_pct": -1.02,
      "spark": [
        83368.4375,
        83988.0625,
        83707.4531,
        83677.3906,
        84212.7969,
        83868.1172,
        83981.7812,
        83846.9531,
        83952.0234,
        83902.2109,
        83845.1484,
        84017.4297,
        83701.4375,
        83606.0234,
        83282.2734,
        83346.5312,
        83530.2266,
        83451.1562,
        83497.0391,
        83516.7812
      ]
    },
    {
      "name": "10-Year US Treasury Yield",
      "symbol": "^TNX",
      "unit": "yield_pct",
      "price": 0.52,
      "change_abs": 0.03,
      "change_pct": 5.48,
      "spark": [
        0.5232,
        0.5234,
        0.5259,
        0.5263,
        0.5257,
        0.5263,
        0.5266,
        0.5259,
        0.5255,
        0.5238,
        0.5249,
        0.5247,
        0.5234,
        0.5234,
        0.5232,
        0.5226,
        0.5238,
        0.5242,
        0.5238,
        0.524
      ]
    },
    {
      "name": "VIX (Fear Index)",
      "symbol": "^VIX",
      "unit": "index",
      "price": 16.07,
      "change_abs": 1.86,
      "change_pct": 13.09,
      "spark": [
        16.33,
        16.22,
        16.21,
        15.77,
        15.99,
        15.94,
        15.82,
        15.96,
        15.98,
        15.91,
        15.84,
        15.89,
        15.88,
        15.9,
        16.06,
        16.01,
        16.1,
        16.1,
        16.07,
        16.07
      ]
    }
  ],
  "items": [
    {
      "title": "OpenAI sparked Hugging Face bids with early investment offer ahead of Nvidia's $13 billion deal",
      "link": "https://www.cnbc.com/2026/09/28/openai-spark-hugging-face-bid-war-early-investment-bid-ahead-of-nvidia.html",
      "description": "Hugging Face saw a flurry of deal interest before Nvidia agreed to buy the open-source platform for roughly $13 billion, CNBC has learned.",
      "source": "CNBC",
      "image": "",
      "published": "2026-09-28T20:36:55+00:00",
      "published_display": "28.09 20:36",
      "sentiment": "positive",
      "tickers": [
        "NVDA"
      ],
      "sectors": [
        "Semiconductors"
      ],
      "importance": 45.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Bitcoin ETFs Are Seeing Their Biggest Inflows Since October 2025. Is Bitcoin Finally Back?",
      "link": "https://www.fool.com/investing/2026/09/28/bitcoin-etfs-are-seeing-their-biggest-inflows-sinc/?.tsrc=rss",
      "description": "The world's top cryptocurrency is attracting renewed attention from institutional investors.",
      "source": "Yahoo Finance",
      "image": "",
      "published": "2026-09-28T20:35:00+00:00",
      "published_display": "28.09 20:35",
      "sentiment": "positive",
      "tickers": [
        "BTC"
      ],
      "sectors": [
        "Cryptocurrencies"
      ],
      "importance": 35.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Stock Market Today: Dow Ends Lower But Nvidia Pops On This; Leisure Play Tests Entry, MongoDB Dives",
      "link": "https://finance.yahoo.com/m/6b34a52f-8642-3ca8-8589-c9e25040f485/stock-market-today%3A-dow-ends.html?.tsrc=rss",
      "description": "Stock Market Today: The Dow Jones index falls Monday as President Trump rejects Iran's bid to end Middle East fighting.",
      "source": "Yahoo Finance",
      "image": "",
      "published": "2026-09-28T20:34:25+00:00",
      "published_display": "28.09 20:34",
      "sentiment": "negative",
      "tickers": [
        "NVDA",
        "DJI"
      ],
      "sectors": [
        "ETFs / Indices",
        "Semiconductors"
      ],
      "importance": 25.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Elon Musk, SpaceXAI subpoenaed by NYC in AI safety investigation",
      "link": "https://www.cnbc.com/2026/09/28/elon-musk-spacexai-subpoenaed-by-nyc-in-ai-safety-investigation.html",
      "description": "The New York City Council issued a subpoena to Musk, requiring that he or another representative of SpaceXAI testify in an investigation concerning AI safety.",
      "source": "CNBC",
      "image": "",
      "published": "2026-09-28T20:33:56+00:00",
      "published_display": "28.09 20:33",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 15.0,
      "content_type": "macro_context",
      "llm_classified": true
    },
    {
      "title": "Treasury yields rise as march to multiyear highs continues",
      "link": "https://www.cnbc.com/2026/09/28/treasury-yields-bonds-selloff.html",
      "description": "Treasury yields edged higher on Monday as investors look ahead to fresh economic data releases this week.",
      "source": "CNBC",
      "image": "",
      "published": "2026-09-28T20:31:36+00:00",
      "published_display": "28.09 20:31",
      "sentiment": "negative",
      "tickers": [
        "UST10Y"
      ],
      "sectors": [
        "Bonds / Macro"
      ],
      "importance": 30.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Not Nvidia, Not AMD. Broadcom's Custom Silicon Business Is Quietly Becoming an AI Chip Powerhouse",
      "link": "https://www.fool.com/investing/2026/09/28/not-nvidia-not-amd-broadcoms-custom-silicon-busine/?.tsrc=rss",
      "description": "Broadcom's AI revenue growth trajectory suggests that it is becoming a major player in a lucrative market.",
      "source": "Yahoo Finance",
      "image": "",
      "published": "2026-09-28T20:31:00+00:00",
      "published_display": "28.09 20:31",
      "sentiment": "positive",
      "tickers": [
        "NVDA",
        "AVGO",
        "AMD"
      ],
      "sectors": [
        "Semiconductors"
      ],
      "importance": 30.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "U.S. stocks lower at close of trade; Dow Jones Industrial Average down 0.67%",
      "link": "https://www.investing.com/news/stock-market-news/us-stocks-lower-at-close-of-trade-dow-jones-industrial-average-down-067-4921160",
      "description": "",
      "source": "Investing.com",
      "image": "https://content-media.investing.com/news/LYNXMPEA6Q02Q_M.jpg",
      "published": "2026-09-28T20:31:00",
      "published_display": "28.09 20:31",
      "sentiment": "negative",
      "tickers": [
        "DJI"
      ],
      "sectors": [
        "ETFs / Indices"
      ],
      "importance": 15.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Canada stocks lower at close of trade; S&P/TSX Composite down 0.87%",
      "link": "https://www.investing.com/news/stock-market-news/canada-stocks-lower-at-close-of-trade-sptsx-composite-down-087-4921159",
      "description": "",
      "source": "Investing.com",
      "image": "https://content-media.investing.com/news/LYNXMPEM3E1BM_1200_L.jpg",
      "published": "2026-09-28T20:30:30",
      "published_display": "28.09 20:30",
      "sentiment": "negative",
      "tickers": [],
      "sectors": [],
      "importance": 10.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Moody’s cuts Dave & Buster’s outlook to negative on sales slump",
      "link": "https://www.investing.com/news/stock-market-news/moodys-cuts-dave--busters-outlook-to-negative-on-sales-slump-4921158",
      "description": "",
      "source": "Investing.com",
      "image": "https://content-media.investing.com/news/LYNXMPEM4R1OV_1200_L.jpg",
      "published": "2026-09-28T20:30:25",
      "published_display": "28.09 20:30",
      "sentiment": "negative",
      "tickers": [],
      "sectors": [],
      "importance": 25.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "AMD acquiring Fei-Fei Li's World Labs AI firm in deal worth $8.2 billion",
      "link": "https://www.cnbc.com/2026/09/28/amd-fei-fei-li-world-labs.html",
      "description": "The chipmaker had previously invested in World Labs.",
      "source": "CNBC",
      "image": "",
      "published": "2026-09-28T20:30:17+00:00",
      "published_display": "28.09 20:30",
      "sentiment": "positive",
      "tickers": [
        "AMD"
      ],
      "sectors": [
        "Semiconductors"
      ],
      "importance": 50.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Brazil stocks lower at close of trade; Bovespa down 0.26%",
      "link": "https://www.investing.com/news/stock-market-news/brazil-stocks-lower-at-close-of-trade-bovespa-down-026-4921146",
      "description": "",
      "source": "Investing.com",
      "image": "https://content-media.investing.com/news/BrazilStockMarketBovespa_800x533_L_1602506584.jpg",
      "published": "2026-09-28T20:30:04",
      "published_display": "28.09 20:30",
      "sentiment": "negative",
      "tickers": [],
      "sectors": [],
      "importance": 10.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Broadcom vs. Marvell Technology: Which Semiconductor Stock Is a Better Buy in 2026?",
      "link": "https://www.fool.com/coverage/better-buy/2026/09/28/broadcom-vs-marvell-technology-which-semiconductor-stock-is-a-better-buy-in-2026/?.tsrc=rss",
      "description": "Broadcom has locked-in AI revenue commitments from some of the most important companies in the industry. Marvell is growing faster but leans heavily on a small number of hyperscaler relationships.",
      "source": "Yahoo Finance",
      "image": "",
      "published": "2026-09-28T20:29:38+00:00",
      "published_display": "28.09 20:29",
      "sentiment": "neutral",
      "tickers": [
        "AVGO",
        "MRVL"
      ],
      "sectors": [
        "Semiconductors"
      ],
      "importance": 15.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "The warning signs your debt may be a problem, according to a credit counselor — and what to do first",
      "link": "https://www.cnbc.com/select/warning-signs-your-debt-is-a-problem-and-what-to-do-first/",
      "description": "There's no dollar amount that makes debt \"a problem.\" Here's what actually signals trouble.",
      "source": "CNBC",
      "image": "",
      "published": "2026-09-28T20:29:30+00:00",
      "published_display": "28.09 20:29",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 5.0,
      "content_type": "macro_context",
      "llm_classified": true
    },
    {
      "title": "A relief rally could be coming soon for these stocks getting hurt by higher rates, says Katie Stockton",
      "link": "https://www.cnbc.com/2026/09/28/a-relief-rally-could-be-coming-soon-for-these-stocks-getting-hurt-by-higher-rates-says-katie-stockton.html",
      "description": "The deeply oversold condition of the utilities sector increases the likelihood of a short-term relief rally over the coming weeks, says Stockton.",
      "source": "CNBC",
      "image": "",
      "published": "2026-09-28T20:26:41+00:00",
      "published_display": "28.09 20:26",
      "sentiment": "positive",
      "tickers": [],
      "sectors": [],
      "importance": 20.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "US says GM tech costs to drop by $20 billion through 2031 due to new emissions rules",
      "link": "https://www.investing.com/news/stock-market-news/us-says-gm-tech-costs-will-decline-by-204-billion-through-2031-because-of-lower-emissions-rules-4920738",
      "description": "",
      "source": "Investing.com",
      "image": "https://content-media.investing.com/trkd-images/LYNXMPEM8R19O_L.jpg",
      "published": "2026-09-28T20:25:52",
      "published_display": "28.09 20:25",
      "sentiment": "positive",
      "tickers": [],
      "sectors": [],
      "importance": 35.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Jefferies quarterly profit jumps on deal surge, equities trading strength",
      "link": "https://www.investing.com/news/stock-market-news/jefferies-quarterly-profit-jumps-on-deal-surge-equities-trading-strength-4921143",
      "description": "",
      "source": "Investing.com",
      "image": "https://content-media.investing.com/trkd-images/LYNXMPEM8R1OZ_L.jpg",
      "published": "2026-09-28T20:25:34",
      "published_display": "28.09 20:25",
      "sentiment": "positive",
      "tickers": [],
      "sectors": [],
      "importance": 35.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Trump-Iran Tensions Trigger Fresh Wall Street Selloff",
      "link": "https://finance.yahoo.com/markets/articles/trump-iran-tensions-trigger-fresh-202442782.html?.tsrc=rss",
      "description": "Oil and Treasury yields are creating a dangerous market mix",
      "source": "Yahoo Finance",
      "image": "",
      "published": "2026-09-28T20:24:42+00:00",
      "published_display": "28.09 20:24",
      "sentiment": "negative",
      "tickers": [
        "UST10Y"
      ],
      "sectors": [
        "Bonds / Macro"
      ],
      "importance": 45.0,
      "content_type": "macro_context",
      "llm_classified": true
    },
    {
      "title": "Pope Leo says concerns about AI doom are not ’fake news’",
      "link": "https://www.investing.com/news/stock-market-news/pope-leo-says-concerns-about-ai-doom-are-not-fake-news-4921104",
      "description": "",
      "source": "Investing.com",
      "image": "https://content-media.investing.com/trkd-images/LYNXMPEM8R1O4_L.jpg",
      "published": "2026-09-28T20:24:39",
      "published_display": "28.09 20:24",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 10.0,
      "content_type": "macro_context",
      "llm_classified": true
    },
    {
      "title": "Navitas Semiconductor stock surges 20% on U.S. defense contract",
      "link": "https://www.investing.com/news/stock-market-news/navitas-semiconductor-stock-surges-20-on-us-defense-contract-4921138",
      "description": "",
      "source": "Investing.com",
      "image": "https://content-media.investing.com/news/LYNXMPEM3S13F_1200_L.jpg",
      "published": "2026-09-28T20:23:25",
      "published_display": "28.09 20:23",
      "sentiment": "positive",
      "tickers": [],
      "sectors": [],
      "importance": 40.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Meta hires MongoDB CEO CJ Desai to lead enterprise unit. MongoDB shares crater",
      "link": "https://www.cnbc.com/2026/09/28/mongodb-meta-cj-desai.html",
      "description": "Desai will lead the new Meta Enterprise Platform unit and report to CEO Mark Zuckerberg.",
      "source": "CNBC",
      "image": "",
      "published": "2026-09-28T20:23:01+00:00",
      "published_display": "28.09 20:23",
      "sentiment": "negative",
      "tickers": [
        "META"
      ],
      "sectors": [
        "Big Tech"
      ],
      "importance": 30.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "TSX ends lower as telecoms and financials slide, energy stocks buck trend",
      "link": "https://www.investing.com/news/stock-market-news/canadian-stock-futures-slip-as-markets-gear-up-for-heavydata-week-4920037",
      "description": "",
      "source": "Investing.com",
      "image": "https://content-media.investing.com/news/LYNXNPEBAG0BO_M.jpg",
      "published": "2026-09-28T20:22:08",
      "published_display": "28.09 20:22",
      "sentiment": "negative",
      "tickers": [],
      "sectors": [],
      "importance": 20.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "SI-Bone stock gains after FDA clears spinal fusion system",
      "link": "https://www.investing.com/news/stock-market-news/sibone-stock-gains-after-fda-clears-spinal-fusion-system-4921136",
      "description": "",
      "source": "Investing.com",
      "image": "https://content-media.investing.com/news/LYNXMPEM1H1CM_1200_L.jpg",
      "published": "2026-09-28T20:21:32",
      "published_display": "28.09 20:21",
      "sentiment": "positive",
      "tickers": [],
      "sectors": [],
      "importance": 25.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Update: US Equity Indexes Fall as Iran Talks Stall, Fed Governor Points to Higher Rates, Inflation",
      "link": "https://finance.yahoo.com/markets/stocks/articles/us-equity-indexes-fall-iran-202125640.html?.tsrc=rss",
      "description": "(Updates with index/price action, macroeconomic data, corporate developments, company/geopolitical n",
      "source": "Yahoo Finance",
      "image": "",
      "published": "2026-09-28T20:21:25+00:00",
      "published_display": "28.09 20:21",
      "sentiment": "negative",
      "tickers": [],
      "sectors": [],
      "importance": 50.0,
      "content_type": "macro_context",
      "llm_classified": true
    },
    {
      "title": "Tesla Pushes Roadster Event To Oct. 15 After Storm Forecast, Says It ‘Can Only Be Held Outdoors’",
      "link": "https://stocktwits.com/news-articles/markets/equity/tesla-pushes-roadster-event-to-oct-15-after-storm-forecast-says-it-can-only-be-held-outdoors/cZMjdzSRBXB?.tsrc=rss",
      "description": "Tesla on Monday pushed back the date of unveiling its second-generation Roadster, citing weather conditions.",
      "source": "Yahoo Finance",
      "image": "",
      "published": "2026-09-28T20:20:25+00:00",
      "published_display": "28.09 20:20",
      "sentiment": "negative",
      "tickers": [
        "TSLA"
      ],
      "sectors": [
        "Automotive / EV"
      ],
      "importance": 15.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Why MongoDB Sank Today",
      "link": "https://www.fool.com/investing/2026/09/28/why-mongodb-sank-today/?.tsrc=rss",
      "description": "In a rather shocking move, MongoDB's CEO left the company to head Meta's new enterprise platform.",
      "source": "Yahoo Finance",
      "image": "",
      "published": "2026-09-28T20:20:18+00:00",
      "published_display": "28.09 20:20",
      "sentiment": "negative",
      "tickers": [
        "META"
      ],
      "sectors": [
        "Big Tech"
      ],
      "importance": 30.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Boeing 737 Max 10 certification delayed by software issue, FAA says",
      "link": "https://www.cnbc.com/2026/09/28/faa-boeing-737-max-10-certification-delay-software-issue.html",
      "description": "The FAA administrator said the Max 10 will be delayed until the agency can assess a software issue on the aircraft.",
      "source": "CNBC",
      "image": "",
      "published": "2026-09-28T20:16:04+00:00",
      "published_display": "28.09 20:16",
      "sentiment": "negative",
      "tickers": [
        "BA"
      ],
      "sectors": [
        "Defense"
      ],
      "importance": 30.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Cotton Trying to Push Higher on Monday",
      "link": "https://www.nasdaq.com/articles/cotton-trying-push-higher-monday",
      "description": "Cotton futures are trading with October down 60 points, with other contracts up 10 to 21 points. Crude oil is up 68 cents per barrel on the session, with the US dollar index $0.162 higher. Following last week’s US/China meeting, China…",
      "source": "Nasdaq",
      "image": "",
      "published": "2026-09-28T20:16:01+00:00",
      "published_display": "28.09 20:16",
      "sentiment": "positive",
      "tickers": [],
      "sectors": [],
      "importance": 15.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Cattle Slipping Back to Start the Week",
      "link": "https://www.nasdaq.com/articles/cattle-slipping-back-start-week",
      "description": "Live cattle futures are showing modest losses of 85 cents to $1.15 at midday. Cash trade was reported at $345-350 dressed in the North, with $222-223 live sales. Feeder cattle futures are falling $1.60 to $2.35 on Monday. The CME Feeder…",
      "source": "Nasdaq",
      "image": "",
      "published": "2026-09-28T20:16:01+00:00",
      "published_display": "28.09 20:16",
      "sentiment": "negative",
      "tickers": [],
      "sectors": [],
      "importance": 15.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Corn Getting Pressured Lower at Midday",
      "link": "https://www.nasdaq.com/articles/corn-getting-pressured-lower-midday",
      "description": "Corn futures are facing spillover weakness to start the week, with beans adding pressure. Contracts are down 6 to 7 cents in the front months, but off the early session highs. The CmdtyView national average Cash Corn price is down 6…",
      "source": "Nasdaq",
      "image": "",
      "published": "2026-09-28T20:16:01+00:00",
      "published_display": "28.09 20:16",
      "sentiment": "negative",
      "tickers": [],
      "sectors": [],
      "importance": 15.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Hogs Showing Steadier Trade on Monday",
      "link": "https://www.nasdaq.com/articles/hogs-showing-steadier-trade-monday",
      "description": "Lean hog futures are up 50 cents to 22 cents lower on Monday, showing mixed trade. USDA’s national base hog price was not reported on Monday morning due to thin volume. The CME Lean Hog Index was down another 44 cents on September 24 at…",
      "source": "Nasdaq",
      "image": "",
      "published": "2026-09-28T20:16:00+00:00",
      "published_display": "28.09 20:16",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 10.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Wheat Facing Early Monday Losses",
      "link": "https://www.nasdaq.com/articles/wheat-facing-early-monday-losses",
      "description": "Wheat is showing modest losses in Monday morning trade. The wheat complex saw some buying off the early lows on Friday but still faced weakness at the final bell. Chicago SRW was down 1 to 3 ¾ cents on the day, with December falling…",
      "source": "Nasdaq",
      "image": "",
      "published": "2026-09-28T20:16:00+00:00",
      "published_display": "28.09 20:16",
      "sentiment": "negative",
      "tickers": [],
      "sectors": [],
      "importance": 12.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "OpenAI DevDay: Can ‘O’ Take the Spotlight From Meta?",
      "link": "https://finance.yahoo.com/m/b98b6905-ff10-31ab-a2e2-c39a394f5ff2/openai-devday%3A-can-%E2%80%98o%E2%80%99-take.html?.tsrc=rss",
      "description": "OpenAI is expected to make some major announcements at its annual developer conference on Tuesday as competition heats up over AI agents and concerns intensify around cybersecurity. The 2026 DevDay will kick off with a keynote by CEO…",
      "source": "Yahoo Finance",
      "image": "",
      "published": "2026-09-28T20:14:00+00:00",
      "published_display": "28.09 20:14",
      "sentiment": "neutral",
      "tickers": [
        "META"
      ],
      "sectors": [
        "Big Tech"
      ],
      "importance": 18.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Supreme Court Justice Alito will not participate in big climate change case next week",
      "link": "https://www.cnbc.com/2026/09/28/supreme-court-justice-alito-recusal-climate-change-case.html",
      "description": "Environmental groups had called for Supreme Court Justice Samuel Alito to recuse himself from the case involving ExxonMobil and Suncor Energy.",
      "source": "CNBC",
      "image": "",
      "published": "2026-09-28T20:13:00+00:00",
      "published_display": "28.09 20:13",
      "sentiment": "neutral",
      "tickers": [
        "XOM"
      ],
      "sectors": [
        "Oil & Gas"
      ],
      "importance": 30.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "LeBron James is already boosting ticket and merchandise demand for Philadelphia 76ers",
      "link": "https://www.cnbc.com/2026/09/28/lebron-james-boosts-ticket-jersey-demand-for-nba-philadelphia-76ers.html",
      "description": "NBA star LeBron James is having a major financial impact on the Philadelphia 76ers and Philadelphia, boosting sponsorships, ticket sales, and economic activity",
      "source": "CNBC",
      "image": "",
      "published": "2026-09-28T20:12:18+00:00",
      "published_display": "28.09 20:12",
      "sentiment": "positive",
      "tickers": [],
      "sectors": [],
      "importance": 15.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Sugar Prices Settle Mixed as Crude Oil Erases an Early Rally",
      "link": "https://www.nasdaq.com/articles/sugar-prices-settle-mixed-crude-oil-erases-early-rally",
      "description": "October NY world sugar #11 (SBV26 ) closed down -0.04 (-0.23%) on Monday, and December London ICE white sugar #5 (SWZ26 ) closed up +1.50 (+0.30%). Sugar prices settled mixed on Monday. Sugar prices initially found support on Monday…",
      "source": "Nasdaq",
      "image": "",
      "published": "2026-09-28T20:10:29+00:00",
      "published_display": "28.09 20:10",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 10.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Cocoa Prices Pressured by Ample Ivory Coast Cocoa Supplies",
      "link": "https://www.nasdaq.com/articles/cocoa-prices-pressured-ample-ivory-coast-cocoa-supplies",
      "description": "December ICE NY cocoa (CCZ26 ) closed down -30 (-0.53%) on Monday, and December ICE London cocoa #7 (CAZ26 ) closed down -30 (-0.71%). Cocoa prices fell from 1-week highs on Monday and settled lower on signs of abundant cocoa supplies…",
      "source": "Nasdaq",
      "image": "",
      "published": "2026-09-28T20:10:28+00:00",
      "published_display": "28.09 20:10",
      "sentiment": "negative",
      "tickers": [],
      "sectors": [],
      "importance": 12.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Dry Weather Forecasts in Brazil Spark Short Covering in Coffee",
      "link": "https://www.nasdaq.com/articles/dry-weather-forecasts-brazil-spark-short-covering-coffee",
      "description": "December arabica coffee (KCZ26 ) closed up +10.15 (+3.64%) on Monday, and November ICE robusta coffee (RMX26 ) closed up +45 (+1.34%). Coffee prices rallied sharply on Monday, with arabica posting a 2-week high and robusta posting a…",
      "source": "Nasdaq",
      "image": "",
      "published": "2026-09-28T20:10:28+00:00",
      "published_display": "28.09 20:10",
      "sentiment": "positive",
      "tickers": [],
      "sectors": [],
      "importance": 22.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "What Meta 'really' has to do to succeed at the enterprise this time around",
      "link": "https://finance.yahoo.com/video/meta-really-succeed-enterprise-time-201018822.html?.tsrc=rss",
      "description": "WestEnd Capital Management senior equity analyst Ali Mogharabi sits down with Market Domination host Josh Lipton to discuss Meta's (META) recently announced enterprise unit.",
      "source": "Yahoo Finance",
      "image": "",
      "published": "2026-09-28T20:10:18+00:00",
      "published_display": "28.09 20:10",
      "sentiment": "neutral",
      "tickers": [
        "META"
      ],
      "sectors": [
        "Big Tech"
      ],
      "importance": 18.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "HMY Makes Notable Cross Below Critical Moving Average",
      "link": "https://www.nasdaq.com/articles/hmy-makes-notable-cross-below-critical-moving-average",
      "description": "In trading on Monday, shares of Harmony Gold Mining Co. Ltd. (Symbol: HMY) crossed below their 200 day moving average of $18.40, changing hands as low as $17.60 per share. Harmony Gold Mining Co. Ltd. shares are currently trading off…",
      "source": "Nasdaq",
      "image": "",
      "published": "2026-09-28T20:10:00+00:00",
      "published_display": "28.09 20:10",
      "sentiment": "negative",
      "tickers": [],
      "sectors": [],
      "importance": 14.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "AngloGold Ashanti Breaks Below 200-Day Moving Average - Notable for AU",
      "link": "https://www.nasdaq.com/articles/anglogold-ashanti-breaks-below-200-day-moving-average-notable-au",
      "description": "In trading on Monday, shares of AngloGold Ashanti plc (Symbol: AU) crossed below their 200 day moving average of $96.58, changing hands as low as $91.85 per share. AngloGold Ashanti plc shares are currently trading down about 6.2% on…",
      "source": "Nasdaq",
      "image": "",
      "published": "2026-09-28T20:09:57+00:00",
      "published_display": "28.09 20:09",
      "sentiment": "negative",
      "tickers": [],
      "sectors": [],
      "importance": 25.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Natural Resource Partners Breaks Above 200-Day Moving Average - Bullish for NRP",
      "link": "https://www.nasdaq.com/articles/natural-resource-partners-breaks-above-200-day-moving-average-bullish-nrp",
      "description": "In trading on Monday, shares of Natural Resource Partners LP (Symbol: NRP) crossed above their 200 day moving average of $110.23, changing hands as high as $111.80 per share. Natural Resource Partners LP shares are currently trading up…",
      "source": "Nasdaq",
      "image": "",
      "published": "2026-09-28T20:09:49+00:00",
      "published_display": "28.09 20:09",
      "sentiment": "positive",
      "tickers": [],
      "sectors": [],
      "importance": 8.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Bullish Two Hundred Day Moving Average Cross - UMH",
      "link": "https://www.nasdaq.com/articles/bullish-two-hundred-day-moving-average-cross-umh",
      "description": "In trading on Monday, shares of UMH Properties Inc (Symbol: UMH) crossed above their 200 day moving average of $15.55, changing hands as high as $15.68 per share. UMH Properties Inc shares are currently trading up about 1.3% on the day.…",
      "source": "Nasdaq",
      "image": "",
      "published": "2026-09-28T20:09:09+00:00",
      "published_display": "28.09 20:09",
      "sentiment": "positive",
      "tickers": [],
      "sectors": [],
      "importance": 7.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Blue Owl Capital Becomes Oversold",
      "link": "https://www.nasdaq.com/articles/blue-owl-capital-becomes-oversold",
      "description": "The DividendRank formula at Dividend Channel ranks a coverage universe of thousands of dividend stocks, according to a proprietary formula designed to identify those stocks that combine two important characteristics — strong…",
      "source": "Nasdaq",
      "image": "",
      "published": "2026-09-28T20:06:54+00:00",
      "published_display": "28.09 20:06",
      "sentiment": "negative",
      "tickers": [],
      "sectors": [],
      "importance": 10.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "ATI Stock Getting Very Oversold",
      "link": "https://www.nasdaq.com/articles/ati-stock-getting-very-oversold",
      "description": "In trading on Monday, shares of ATI Inc (Symbol: ATI) entered into oversold territory, changing hands as low as $178.26 per share. We define oversold territory using the Relative Strength Index, or RSI, which is a technical analysis…",
      "source": "Nasdaq",
      "image": "",
      "published": "2026-09-28T20:06:27+00:00",
      "published_display": "28.09 20:06",
      "sentiment": "negative",
      "tickers": [],
      "sectors": [],
      "importance": 10.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "AREC Crosses Critical Technical Indicator",
      "link": "https://www.nasdaq.com/articles/arec-crosses-critical-technical-indicator",
      "description": "In trading on Monday, shares of American Resources Corp (Symbol: AREC) entered into oversold territory, changing hands as low as $1.82 per share. We define oversold territory using the Relative Strength Index, or RSI, which is a…",
      "source": "Nasdaq",
      "image": "",
      "published": "2026-09-28T20:06:23+00:00",
      "published_display": "28.09 20:06",
      "sentiment": "negative",
      "tickers": [],
      "sectors": [],
      "importance": 6.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Senate tees up college sports bill aimed at regulating NIL deals",
      "link": "https://www.cnbc.com/2026/09/28/college-sports-bill-senate-nil.html",
      "description": "The Senate is due to vote Monday on the bill, which would create a national framework for name, image and likeness deals in college athletics.",
      "source": "CNBC",
      "image": "",
      "published": "2026-09-28T20:05:55+00:00",
      "published_display": "28.09 20:05",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 10.0,
      "content_type": "macro_context",
      "llm_classified": true
    },
    {
      "title": "Nvidia, Apple Partner TSMC Reveals These Clues On How To Read Charts",
      "link": "https://finance.yahoo.com/m/9d354324-7049-3304-a302-132d423b0a1b/nvidia%2C-apple-partner-tsmc.html?.tsrc=rss",
      "description": "As TSMC stock teases a breakout, it flashes telltale indicators and provides multiple ways to view the chart action.",
      "source": "Yahoo Finance",
      "image": "",
      "published": "2026-09-28T20:04:46+00:00",
      "published_display": "28.09 20:04",
      "sentiment": "positive",
      "tickers": [
        "NVDA",
        "TSM",
        "AAPL"
      ],
      "sectors": [
        "Big Tech",
        "Semiconductors"
      ],
      "importance": 25.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Before you invest in the Oura IPO, understand what you’re buying",
      "link": "https://www.marketwatch.com/story/before-you-invest-in-the-oura-ipo-understand-what-youre-buying-1d88d868?mod=mw_rss_topstories",
      "description": "The health-data company could see a pop in its stock price, but there are plenty of warning signs",
      "source": "MarketWatch",
      "image": "https://images.mktw.net/im-55840874",
      "published": "2026-09-28T20:04:00+00:00",
      "published_display": "28.09 20:04",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 15.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Amazon (AMZN) vs. Alibaba (BABA): Which AI Bet Is Starting to Pay Off?",
      "link": "https://finance.yahoo.com/technology/ai/articles/amazon-amzn-vs-alibaba-baba-200303828.html?.tsrc=rss",
      "description": "Amazon.com, Inc. (NASDAQ:AMZN) and Alibaba Group Holding Limited (NYSE:BABA) have more in common than their e-commerce roots suggest. Both are now making enormous bets on artificial intelligence, and cloud computing is emerging as an…",
      "source": "Yahoo Finance",
      "image": "",
      "published": "2026-09-28T20:03:03+00:00",
      "published_display": "28.09 20:03",
      "sentiment": "neutral",
      "tickers": [
        "AMZN",
        "BABA"
      ],
      "sectors": [
        "Big Tech"
      ],
      "importance": 20.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "October is historically the most volatile month for stocks. But why? These 4 popular theories fail to hold up.",
      "link": "https://www.marketwatch.com/story/october-is-historically-the-most-volatile-month-for-stocks-but-why-these-4-popular-theories-fail-to-hold-up-a47a1830?mod=mw_rss_topstories",
      "description": "Although October historically has been the most volatile month of the year, you shouldn’t bet that it will continue to be in the future.",
      "source": "MarketWatch",
      "image": "https://images.mktw.net/im-05001860",
      "published": "2026-09-28T20:02:00+00:00",
      "published_display": "28.09 20:02",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 10.0,
      "content_type": "macro_context",
      "llm_classified": true
    },
    {
      "title": "AI Can't Save the Stock Market and the S&P 500 Is Paying the Price",
      "link": "https://finance.yahoo.com/m/a0e5a077-d681-3f42-b3ff-2dafe265c478/ai-can%27t-save-the-stock.html?.tsrc=rss",
      "description": "Artificial intelligence stocks finally ran out of steam and major U.S. stock indexes were paying the price on Monday. The Dow Jones Industrial Average fell 347 points, or 0.7%. The S&P 500 dropped 0.8%.",
      "source": "Yahoo Finance",
      "image": "",
      "published": "2026-09-28T20:01:44+00:00",
      "published_display": "28.09 20:01",
      "sentiment": "negative",
      "tickers": [
        "SPY",
        "DJI"
      ],
      "sectors": [
        "ETFs / Indices"
      ],
      "importance": 35.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Meta's splashy new business AI hire offers yet another reason to bank on Zuckerberg",
      "link": "https://www.cnbc.com/2026/09/28/metas-splashy-new-business-ai-hire-offers-yet-another-reason-to-bank-on-zuckerberg.html",
      "description": "By poaching MongoDB's CJ Desai, Mark Zuckerberg shows he's serious about building an enterprise AI business.",
      "source": "CNBC",
      "image": "",
      "published": "2026-09-28T20:01:16+00:00",
      "published_display": "28.09 20:01",
      "sentiment": "positive",
      "tickers": [
        "META"
      ],
      "sectors": [
        "Big Tech"
      ],
      "importance": 20.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Sector Update: Energy Stocks Higher Late Afternoon",
      "link": "https://finance.yahoo.com/energy/articles/sector-energy-stocks-higher-afternoon-195954136.html?.tsrc=rss",
      "description": "Energy stocks advanced late Monday afternoon with the NYSE Energy Sector Index adding 0.5% and the S",
      "source": "Yahoo Finance",
      "image": "",
      "published": "2026-09-28T19:59:54+00:00",
      "published_display": "28.09 19:59",
      "sentiment": "positive",
      "tickers": [],
      "sectors": [],
      "importance": 15.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Sector Update: Tech Stocks Fall Late Afternoon",
      "link": "https://finance.yahoo.com/markets/stocks/articles/sector-tech-stocks-fall-afternoon-195704336.html?.tsrc=rss",
      "description": "Tech stocks were lower late Monday afternoon, with the State Street Technology Select Sector SPDR ET",
      "source": "Yahoo Finance",
      "image": "",
      "published": "2026-09-28T19:57:04+00:00",
      "published_display": "28.09 19:57",
      "sentiment": "negative",
      "tickers": [],
      "sectors": [],
      "importance": 15.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Nvidia’s $235 Billion Buyback Shows Who Is Really Winning the AI Boom",
      "link": "https://finance.yahoo.com/m/67d27dfd-5a8c-391c-94f3-46ffb8b152b3/nvidia%E2%80%99s-%24235-billion-buyback.html?.tsrc=rss",
      "description": "Nvidia stock buybacks allow investors to effectively get future cash flows from the AI boom paid up front.",
      "source": "Yahoo Finance",
      "image": "",
      "published": "2026-09-28T19:57:00+00:00",
      "published_display": "28.09 19:57",
      "sentiment": "positive",
      "tickers": [
        "NVDA"
      ],
      "sectors": [
        "Semiconductors"
      ],
      "importance": 35.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Tesla Postpones Roadster Unveil Ahead Of Q3 Delivery Release; Stock Drops",
      "link": "https://finance.yahoo.com/m/b16a9006-9b4e-3ac4-ba15-a43d8b3fc0fe/tesla-postpones-roadster.html?.tsrc=rss",
      "description": "Tesla was supposed to the showcase the new version of the Roadster this week — almost a decade after it was first announced.",
      "source": "Yahoo Finance",
      "image": "",
      "published": "2026-09-28T19:56:54+00:00",
      "published_display": "28.09 19:56",
      "sentiment": "negative",
      "tickers": [
        "TSLA"
      ],
      "sectors": [
        "Automotive / EV"
      ],
      "importance": 30.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Veteran marketer defends controversial Sydney Sweeney jeans ad campaign: The publicity was 'worth billions'",
      "link": "https://finance.yahoo.com/markets/stocks/article/veteran-marketer-defends-controversial-sydney-sweeney-jeans-ad-campaign-the-publicity-was-worth-billions-195605772.html?.tsrc=rss",
      "description": "Veteran marketer Mark Penn has no regrets about signing off on the viral Sydney Sweeney American Eagle Outfitters jeans ad.",
      "source": "Yahoo Finance",
      "image": "",
      "published": "2026-09-28T19:56:05+00:00",
      "published_display": "28.09 19:56",
      "sentiment": "positive",
      "tickers": [],
      "sectors": [],
      "importance": 10.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Can CoreWeave’s (CRWV) Computing Advantage Become a Lasting Moat?",
      "link": "https://finance.yahoo.com/technology/ai/articles/coreweave-crwv-computing-advantage-become-195220773.html?.tsrc=rss",
      "description": "CoreWeave, Inc. (NASDAQ:CRWV) has become one of the market’s more closely watched infrastructure stocks. Revenue is expected to more than double this year and again next year, yet the company is still losing money and isn’t expected to…",
      "source": "Yahoo Finance",
      "image": "",
      "published": "2026-09-28T19:52:20+00:00",
      "published_display": "28.09 19:52",
      "sentiment": "neutral",
      "tickers": [
        "CRWV"
      ],
      "sectors": [
        "AI Infrastructure"
      ],
      "importance": 15.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Amazon Has a $10 Billion Holiday Catalyst Coming in October",
      "link": "https://finance.yahoo.com/markets/stocks/articles/amazon-10-billion-holiday-catalyst-194457409.html?.tsrc=rss",
      "description": "Adobe expects U.S. consumers to spend $10 billion during Amazon's October Prime Day event as online holiday sales head toward another record.",
      "source": "Yahoo Finance",
      "image": "",
      "published": "2026-09-28T19:44:57+00:00",
      "published_display": "28.09 19:44",
      "sentiment": "positive",
      "tickers": [
        "ADBE",
        "AMZN"
      ],
      "sectors": [
        "Big Tech",
        "Software / Cloud"
      ],
      "importance": 20.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Trump announces plan for $15 billion steel plant, would be largest in U.S. history",
      "link": "https://www.cnbc.com/2026/09/28/trump-steel-plant-iowa.html",
      "description": "Trump's announcement with Mesabi Metallics comes as Americans' souring views of the economy are poised to shape the upcoming midterm election.",
      "source": "CNBC",
      "image": "",
      "published": "2026-09-28T19:37:50+00:00",
      "published_display": "28.09 19:37",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 15.0,
      "content_type": "macro_context",
      "llm_classified": true
    },
    {
      "title": "PepsiCo plans to raise prices on sodas, chips and dip — and that has Wall Street worried",
      "link": "https://www.marketwatch.com/story/pepsico-plans-to-raise-prices-on-sodas-chips-and-dip-and-that-has-wall-street-worried-0ec355bf?mod=mw_rss_topstories",
      "description": "TD Cowen analysts flagged the company’s “shifting narrative on affordability” as a risk.",
      "source": "MarketWatch",
      "image": "https://images.mktw.net/im-52417895",
      "published": "2026-09-28T19:37:00+00:00",
      "published_display": "28.09 19:37",
      "sentiment": "negative",
      "tickers": [
        "PEP"
      ],
      "sectors": [
        "Consumer Goods"
      ],
      "importance": 25.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "IRS hires Joseph Velli to help administer Trump accounts",
      "link": "https://www.cnbc.com/2026/09/28/irs-trump-accounts-joseph-velli.html",
      "description": "Velli previously served on the boards of Paychex, Cognizant and Computershare.",
      "source": "CNBC",
      "image": "",
      "published": "2026-09-28T19:30:50+00:00",
      "published_display": "28.09 19:30",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 8.0,
      "content_type": "macro_context",
      "llm_classified": true
    },
    {
      "title": "‘We lived within our means’: I earned $30,000 as a pastor and still retired comfortably. Why don’t you tell people that?",
      "link": "https://www.marketwatch.com/story/we-lived-within-our-means-i-earned-30-000-as-a-pastor-and-still-retired-comfortably-why-dont-you-tell-people-that-6b9f231e?mod=mw_rss_topstories",
      "description": "“As a country, we have grown dangerously comfortable.”",
      "source": "MarketWatch",
      "image": "https://images.mktw.net/im-57986369",
      "published": "2026-09-28T19:30:00+00:00",
      "published_display": "28.09 19:30",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 5.0,
      "content_type": "macro_context",
      "llm_classified": true
    },
    {
      "title": "Oil prices off highs after reports Saudi pipeline ramping back up",
      "link": "https://www.cnbc.com/2026/09/28/oil-price-today-wti-brent-trump-iran.html",
      "description": "The Saudis shutdown the pipeline earlier this month after it sustained damage in a drone strike launched form Iraq.",
      "source": "CNBC",
      "image": "",
      "published": "2026-09-28T19:12:45+00:00",
      "published_display": "28.09 19:12",
      "sentiment": "negative",
      "tickers": [],
      "sectors": [],
      "importance": 35.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Higher rates will create winners and losers in bonds, says UBS. Where the bank sees opportunity",
      "link": "https://www.cnbc.com/2026/09/28/higher-rates-will-create-winners-and-losers-in-bonds-says-ubs.html",
      "description": "The caliber of bonds matters, especially the higher rates go, UBS says.",
      "source": "CNBC",
      "image": "",
      "published": "2026-09-28T19:09:46+00:00",
      "published_display": "28.09 19:09",
      "sentiment": "neutral",
      "tickers": [
        "UBS"
      ],
      "sectors": [
        "Banking & Finance"
      ],
      "importance": 20.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Dolly Parton planned for her estate. The fight with her nephew shows why that matters.",
      "link": "https://www.marketwatch.com/story/dolly-parton-planned-for-her-estate-the-fight-with-her-nephew-shows-why-that-matters-b7e57c26?mod=mw_rss_topstories",
      "description": "It’s important to have guardrails around your legacy.",
      "source": "MarketWatch",
      "image": "https://images.mktw.net/im-19126269",
      "published": "2026-09-28T18:56:00+00:00",
      "published_display": "28.09 18:56",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 5.0,
      "content_type": "macro_context",
      "llm_classified": true
    },
    {
      "title": "Feds can't withhold counterterrorism funds from states to force election admin changes, judge rules",
      "link": "https://www.cnbc.com/2026/09/28/elections-dhs-counterterrorism.html",
      "description": "The judge said FEMA never explained how the election changes it wanted were \"tied to the goal of shoring up vulnerabilities to terrorist attacks.\"",
      "source": "CNBC",
      "image": "",
      "published": "2026-09-28T18:41:51+00:00",
      "published_display": "28.09 18:41",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 10.0,
      "content_type": "macro_context",
      "llm_classified": true
    },
    {
      "title": "Spending $800 to see my family this Thanksgiving is a financial burden. How can I push for a cheaper flight?",
      "link": "https://www.marketwatch.com/story/spending-800-to-see-my-family-this-thanksgiving-is-a-financial-burden-how-can-i-push-for-a-cheaper-flight-c6dd1fdf?mod=mw_rss_topstories",
      "description": "“My sister always chooses places where it’s cheapest for her to fly.”",
      "source": "MarketWatch",
      "image": "https://images.mktw.net/im-67770957",
      "published": "2026-09-28T18:40:00+00:00",
      "published_display": "28.09 18:40",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 5.0,
      "content_type": "macro_context",
      "llm_classified": true
    },
    {
      "title": "The U.S. and China agree to $60 billion in tariff cuts on products like dolls and fireworks. Rare earths remain a sticking point.",
      "link": "https://www.marketwatch.com/story/the-u-s-and-china-agree-to-60-billion-in-tariff-cuts-on-products-like-dolls-and-fireworks-rare-earths-remain-a-sticking-point-e4667872?mod=mw_rss_topstories",
      "description": "There were no major breakthroughs on big issues including AI, Iran and Taiwan.",
      "source": "MarketWatch",
      "image": "https://images.mktw.net/im-58143024",
      "published": "2026-09-28T18:15:00+00:00",
      "published_display": "28.09 18:15",
      "sentiment": "positive",
      "tickers": [],
      "sectors": [],
      "importance": 45.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Anthropic launches cheaper AI model, its second release since CEO's call for a slowdown",
      "link": "https://www.cnbc.com/2026/09/28/anthropic-sonnet-5-5-launch.html",
      "description": "The company said Sonnet 5.5 doesn't advance the frontier, but that it is better at coding and knowledge work tasks than its predecessor.",
      "source": "CNBC",
      "image": "",
      "published": "2026-09-28T18:00:06+00:00",
      "published_display": "28.09 18:00",
      "sentiment": "positive",
      "tickers": [],
      "sectors": [],
      "importance": 20.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Goldman Sachs brings $100 billion Treasury fund into crypto’s institutional plumbing",
      "link": "https://www.coindesk.com/markets/2026/09/28/goldman-sachs-brings-usd100-billion-treasury-fund-into-crypto-s-institutional-plumbing",
      "description": "The bank is bringing its roughly $100 billion Treasury fund to institutional crypto firms without creating a tokenized version of it.",
      "source": "CoinDesk",
      "image": "https://cdn.sanity.io/images/s3y3vcno/production/60dbe787741b3cbc62bdc5cb2d6cb94fbe3ea9ea-5800x3868.jpg?fm=jpg&w=1920&h=1080&crop=focalpoint&fit=clip",
      "published": "2026-09-28T18:00:00+00:00",
      "published_display": "28.09 18:00",
      "sentiment": "positive",
      "tickers": [
        "GS"
      ],
      "sectors": [
        "Banking & Finance"
      ],
      "importance": 30.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Nearly half the stocks in the S&P 500 are at cross purposes with the rest of the market",
      "link": "https://www.cnbc.com/2026/09/28/nearly-half-of-the-stocks-in-the-sp-500-are-working-against-it.html",
      "description": "Almost half of the stocks in the S&P 500 have a negative beta, evidence of a chasm between the entire index and its individual components.",
      "source": "CNBC",
      "image": "",
      "published": "2026-09-28T17:53:31+00:00",
      "published_display": "28.09 17:53",
      "sentiment": "neutral",
      "tickers": [
        "SPY"
      ],
      "sectors": [
        "ETFs / Indices"
      ],
      "importance": 15.0,
      "content_type": "macro_context",
      "llm_classified": true
    },
    {
      "title": "A key test looms for the AI trade this week. Here's how Mike Khouw is trading it",
      "link": "https://www.cnbc.com/2026/09/28/a-key-test-looms-for-the-ai-trade-this-week-heres-how-mike-khouw-is-trading-it.html",
      "description": "Micron reports after the bell Wednesday.",
      "source": "CNBC",
      "image": "",
      "published": "2026-09-28T17:48:15+00:00",
      "published_display": "28.09 17:48",
      "sentiment": "neutral",
      "tickers": [
        "MU"
      ],
      "sectors": [
        "Semiconductors"
      ],
      "importance": 20.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "‘I’m never selling’: I’m 47 and buy bitcoin with every dollar I earn. Am I crazy?",
      "link": "https://www.marketwatch.com/story/im-never-selling-im-47-and-buy-bitcoin-with-every-dollar-i-earn-am-i-crazy-364d2a64?mod=mw_rss_topstories",
      "description": "“When my paycheck lands, it takes a detour through bitcoin.”",
      "source": "MarketWatch",
      "image": "https://images.mktw.net/im-45716551",
      "published": "2026-09-28T17:30:00+00:00",
      "published_display": "28.09 17:30",
      "sentiment": "neutral",
      "tickers": [
        "BTC"
      ],
      "sectors": [
        "Cryptocurrencies"
      ],
      "importance": 5.0,
      "content_type": "macro_context",
      "llm_classified": true
    },
    {
      "title": "SpaceX sends its Starship rocket to orbit for the first time — but not without some hiccups",
      "link": "https://www.marketwatch.com/story/spacex-is-moments-away-from-monumental-starship-launch-4f34767b?mod=mw_rss_topstories",
      "description": "SpaceX cut the flight short after initially aiming to send it on a nearly 10-hour mission.",
      "source": "MarketWatch",
      "image": "https://images.mktw.net/im-22566383",
      "published": "2026-09-28T17:21:00+00:00",
      "published_display": "28.09 17:21",
      "sentiment": "positive",
      "tickers": [
        "SPCX"
      ],
      "sectors": [
        "Space"
      ],
      "importance": 25.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "The restaking gold rush is over, and top protocols are barely making a profit",
      "link": "https://www.coindesk.com/business/2026/09/28/the-restaking-gold-rush-is-over-and-top-protocols-are-barely-making-a-profit",
      "description": "As restaking yields dried up and smart-contract risks mounted, Ethereum's top liquid restaking protocol walked away from its core business to build a crypto neobank instead.",
      "source": "CoinDesk",
      "image": "https://cdn.sanity.io/images/s3y3vcno/production/7eaf553e8abf889a62ef0301a3a12b6d6e1ddce6-4498x3000.jpg?fm=jpg&w=1920&h=1080&crop=focalpoint&fit=clip",
      "published": "2026-09-28T16:24:51+00:00",
      "published_display": "28.09 16:24",
      "sentiment": "negative",
      "tickers": [
        "ETH"
      ],
      "sectors": [
        "Cryptocurrencies"
      ],
      "importance": 25.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Tether is a ‘lifeline’ for Iranian regime, Senate Dems say in new report",
      "link": "https://www.coindesk.com/policy/2026/09/28/tether-is-a-lifeline-for-iranian-regime-senate-dems-say-in-new-report",
      "description": "Democrats on the Senate's Permanent Subcommittee on Intelligence published a report alleging that USDT had become a key tool for the Iranian government.",
      "source": "CoinDesk",
      "image": "https://cdn.sanity.io/images/s3y3vcno/production/ad8e6630721cca761fc441079ebcd6819e13f93e-8256x5504.jpg?fm=jpg&w=1920&h=1080&crop=focalpoint&fit=clip",
      "published": "2026-09-28T16:16:40+00:00",
      "published_display": "28.09 16:16",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 15.0,
      "content_type": "macro_context",
      "llm_classified": true
    },
    {
      "title": "Ex-Disney CEO Bob Chapek says he raised concerns with the board 'weekly' during Iger power battle",
      "link": "https://www.cnbc.com/2026/09/28/disney-bob-chapek-bob-iger-power-battle-board.html",
      "description": "Former Disney CEO Bob Chapek was ousted from his role as CEO in late 2022, less than three years after taking the post, and replaced by Iger.",
      "source": "CNBC",
      "image": "",
      "published": "2026-09-28T16:02:17+00:00",
      "published_display": "28.09 16:02",
      "sentiment": "neutral",
      "tickers": [
        "DIS"
      ],
      "sectors": [
        "Media / Entertainment"
      ],
      "importance": 8.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "SpaceX launches its massive Starship rocket into orbit for the first time",
      "link": "https://www.cnbc.com/2026/09/28/spacex-prepares-to-send-starship-rocket-to-orbit-for-first-time.html",
      "description": "Elon Musk's SpaceX launched a historic test flight of its massive Starship rocket early Monday.",
      "source": "CNBC",
      "image": "",
      "published": "2026-09-28T16:01:50+00:00",
      "published_display": "28.09 16:01",
      "sentiment": "positive",
      "tickers": [
        "SPCX"
      ],
      "sectors": [
        "Space"
      ],
      "importance": 35.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "B2Gold strikes new Goose gold zone",
      "link": "https://www.mining.com/b2gold-strikes-new-goose-gold-zone/",
      "description": "B2Gold found a new high-grade gold zone at Goose mine in Nunavut, recovering from an April fire.",
      "source": "Mining.com",
      "image": "",
      "published": "2026-09-28T16:01:36+00:00",
      "published_display": "28.09 16:01",
      "sentiment": "positive",
      "tickers": [],
      "sectors": [],
      "importance": 15.0,
      "content_type": "market_signal",
      "llm_classified": true
    }
  ]
};
