// This file is auto-generated by fetch_news.py — do not edit by hand
const NEWS_DATA = {
  "generated_at": "2026-09-24T18:33:55.081721+00:00",
  "generated_at_display": "24.09.2026 18:33",
  "summary": {
    "total": 80,
    "signal_total": 52,
    "macro_total": 28,
    "positive": 28,
    "negative": 17,
    "neutral": 7,
    "top_tickers": [
      {
        "ticker": "UST10Y",
        "count": 8
      },
      {
        "ticker": "SPY",
        "count": 5
      },
      {
        "ticker": "FED",
        "count": 4
      },
      {
        "ticker": "META",
        "count": 4
      },
      {
        "ticker": "QQQ",
        "count": 3
      },
      {
        "ticker": "DJI",
        "count": 3
      }
    ],
    "sectors": [
      "Automotive / EV",
      "Banking & Finance",
      "Big Tech",
      "Bonds / Macro",
      "Consumer Goods",
      "Cryptocurrencies",
      "ETFs / Indices",
      "Semiconductors",
      "Software / Cloud"
    ],
    "source_counts": {
      "CNBC": 30,
      "MarketWatch": 8,
      "Investing.com": 10,
      "Nasdaq": 15,
      "CoinDesk": 9,
      "Mining.com": 4,
      "OilPrice.com": 3,
      "Retail Dive": 1
    }
  },
  "indices": [
    {
      "name": "S&P 500",
      "symbol": "^GSPC",
      "unit": "index",
      "price": 7703.61,
      "change_abs": 65.85,
      "change_pct": 0.86,
      "spark": [
        7690.2998,
        7690.02,
        7682.0801,
        7674.6201,
        7663.1499,
        7666.2598,
        7670.4702,
        7673.0601,
        7671.4399,
        7701.0,
        7706.6401,
        7713.8799,
        7714.0898,
        7702.5298,
        7692.4302,
        7699.5498,
        7700.23,
        7706.5,
        7702.0698,
        7703.6099
      ]
    },
    {
      "name": "Dow Jones",
      "symbol": "^DJI",
      "unit": "index",
      "price": 51367.58,
      "change_abs": -410.46,
      "change_pct": -0.79,
      "spark": [
        51370.0703,
        51328.6406,
        51262.2383,
        51231.4297,
        51125.7617,
        51156.8281,
        51173.3906,
        51182.3086,
        51184.2812,
        51376.3984,
        51400.3516,
        51383.3086,
        51404.8516,
        51321.7188,
        51274.8516,
        51341.0781,
        51370.7617,
        51401.1211,
        51361.4414,
        51367.5781
      ]
    },
    {
      "name": "Nasdaq Composite",
      "symbol": "^IXIC",
      "unit": "index",
      "price": 26918.63,
      "change_abs": 500.33,
      "change_pct": 1.89,
      "spark": [
        26780.6035,
        26809.0352,
        26771.666,
        26741.8691,
        26707.2285,
        26719.834,
        26737.9141,
        26759.8711,
        26742.7129,
        26877.6113,
        26917.5684,
        26957.2988,
        26955.2754,
        26910.0723,
        26860.9902,
        26887.9434,
        26890.0254,
        26922.8887,
        26910.1797,
        26918.6289
      ]
    },
    {
      "name": "Russell 2000",
      "symbol": "^RUT",
      "unit": "index",
      "price": 2833.33,
      "change_abs": -41.3,
      "change_pct": -1.44,
      "spark": [
        2824.6462,
        2829.0188,
        2826.8059,
        2824.5125,
        2819.9573,
        2816.3357,
        2813.4641,
        2812.8728,
        2813.0159,
        2811.7034,
        2830.9277,
        2835.7297,
        2833.6799,
        2834.3862,
        2830.6951,
        2828.0203,
        2830.146,
        2830.5088,
        2832.6309,
        2833.3274
      ]
    },
    {
      "name": "FTSE 100 (UK)",
      "symbol": "^FTSE",
      "unit": "index",
      "price": 10679.99,
      "change_abs": -136.11,
      "change_pct": -1.26,
      "spark": [
        10716.6797,
        10720.5996,
        10713.3896,
        10704.6602,
        10716.3799,
        10719.4102,
        10714.46,
        10716.1602,
        10718.4004,
        10716.3398,
        10724.7305,
        10731.6904,
        10734.3398,
        10728.8301,
        10726.3701,
        10716.2998,
        10701.8496,
        10681.0703,
        10680.4004,
        10679.9902
      ]
    },
    {
      "name": "DAX (Germany)",
      "symbol": "^GDAXI",
      "unit": "index",
      "price": 25266.53,
      "change_abs": -450.18,
      "change_pct": -1.75,
      "spark": [
        25364.6895,
        25358.0996,
        25330.1992,
        25319.9492,
        25366.0391,
        25354.7793,
        25347.0898,
        25353.3691,
        25369.75,
        25385.7109,
        25409.5703,
        25371.8203,
        25389.5898,
        25371.2793,
        25381.6699,
        25334.2305,
        25295.7109,
        25255.6797,
        25256.2793,
        25266.5293
      ]
    },
    {
      "name": "Euro Stoxx 50",
      "symbol": "^STOXX50E",
      "unit": "index",
      "price": 6272.5,
      "change_abs": 36.3,
      "change_pct": 0.58,
      "spark": [
        6292.5801,
        6294.0698,
        6287.8198,
        6282.7002,
        6293.2998,
        6291.8101,
        6288.6401,
        6289.73,
        6291.3101,
        6294.29,
        6299.0098,
        6296.3501,
        6300.4702,
        6296.21,
        6296.8901,
        6288.98,
        6281.7798,
        6272.3398,
        6273.9502,
        6272.5
      ]
    },
    {
      "name": "Nikkei 225 (Japan)",
      "symbol": "^N225",
      "unit": "index",
      "price": 65513.99,
      "change_abs": 2029.89,
      "change_pct": 3.2,
      "spark": [
        66124.0391,
        66059.9922,
        65977.6875,
        66021.6797,
        65885.3516,
        65881.1875,
        65883.4062,
        65780.75,
        65768.0312,
        65653.1875,
        65774.6406,
        65808.6172,
        65859.3594,
        65871.8516,
        65861.7109,
        65796.0391,
        65632.4609,
        65682.0469,
        65647.2734,
        65513.9883
      ]
    },
    {
      "name": "Hang Seng (Hong Kong)",
      "symbol": "^HSI",
      "unit": "index",
      "price": 24761.13,
      "change_abs": 156.84,
      "change_pct": 0.64,
      "spark": [
        24767.4902,
        24750.6992,
        24716.0391,
        24727.9004,
        24703.4004,
        24704.9102,
        24704.75,
        24696.5898,
        24706.3301,
        24719.6895,
        24690.6309,
        24733.9395,
        24764.7109,
        24744.6309,
        24728.2305,
        24760.6309,
        24767.0098,
        24769.0508,
        24763.2305,
        24761.1309
      ]
    },
    {
      "name": "Gold (futures)",
      "symbol": "GC=F",
      "unit": "index",
      "price": 4304.4,
      "change_abs": -79.5,
      "change_pct": -1.81,
      "spark": [
        4302.5,
        4304.6001,
        4302.3999,
        4291.3999,
        4288.0,
        4282.1001,
        4285.3999,
        4289.8999,
        4291.2998,
        4294.0,
        4310.8999,
        4309.6001,
        4308.7002,
        4305.8999,
        4298.5,
        4294.2002,
        4300.1001,
        4304.7998,
        4304.2002,
        4304.3999
      ]
    },
    {
      "name": "WTI Crude Oil (futures)",
      "symbol": "CL=F",
      "unit": "index",
      "price": 94.69,
      "change_abs": -1.09,
      "change_pct": -1.14,
      "spark": [
        94.11,
        94.28,
        94.68,
        95.24,
        95.56,
        95.95,
        96.41,
        96.24,
        96.48,
        96.35,
        94.12,
        93.74,
        94.42,
        94.34,
        94.78,
        95.57,
        95.3,
        94.55,
        94.69,
        94.69
      ]
    },
    {
      "name": "Bitcoin",
      "symbol": "BTC-USD",
      "unit": "index",
      "price": 84347.46,
      "change_abs": 3204.85,
      "change_pct": 3.95,
      "spark": [
        84212.8906,
        84821.0,
        84387.7422,
        83641.1484,
        83872.6328,
        84104.3984,
        84406.4297,
        84392.2188,
        84163.4062,
        84689.4609,
        84524.4766,
        84466.5,
        84464.6719,
        84302.2812,
        84146.9922,
        84095.5078,
        84229.0391,
        84400.6562,
        84357.8984,
        84347.4609
      ]
    },
    {
      "name": "10-Year US Treasury Yield",
      "symbol": "^TNX",
      "unit": "yield_pct",
      "price": 0.52,
      "change_abs": 0.02,
      "change_pct": 3.16,
      "spark": [
        0.5096,
        0.5091,
        0.5106,
        0.5112,
        0.5129,
        0.5141,
        0.5154,
        0.5166,
        0.516,
        0.516,
        0.5137,
        0.5137,
        0.5137,
        0.5139,
        0.5152,
        0.5154,
        0.5158,
        0.5179,
        0.5158,
        0.5156
      ]
    },
    {
      "name": "VIX (Fear Index)",
      "symbol": "^VIX",
      "unit": "index",
      "price": 15.6,
      "change_abs": 0.79,
      "change_pct": 5.33,
      "spark": [
        15.69,
        15.61,
        15.63,
        15.78,
        15.99,
        16.25,
        16.15,
        16.15,
        16.02,
        16.14,
        15.65,
        15.46,
        15.41,
        15.41,
        15.69,
        15.81,
        15.72,
        15.7,
        15.63,
        15.6
      ]
    }
  ],
  "items": [
    {
      "title": "Surging Treasury yields are posing a brand new problem for Kevin Warsh and the Fed",
      "link": "https://www.cnbc.com/2026/09/24/surging-treasury-yields-are-posing-a-brand-new-problem-for-kevin-warsh-and-the-fed.html",
      "description": "Markets expect the central bank will take a firmer hand on inflation. It's not that easy.",
      "source": "CNBC",
      "image": "",
      "published": "2026-09-24T18:30:35+00:00",
      "published_display": "24.09 18:30",
      "sentiment": "neutral",
      "tickers": [
        "UST10Y"
      ],
      "sectors": [
        "Bonds / Macro"
      ],
      "importance": 35.0,
      "content_type": "macro_context",
      "llm_classified": true
    },
    {
      "title": "8% mortgage rates are ‘not an impossibility’ as the 30-year fixed rate surges",
      "link": "https://www.marketwatch.com/story/8-mortgage-rates-are-not-an-impossibility-as-the-30-year-fixed-rate-surges-aa202464?mod=mw_rss_topstories",
      "description": "With the 10-year Treasury up sharply and the outlook for the U.S. economy looking unclear, some say 8% mortgage rates are back on the table.",
      "source": "MarketWatch",
      "image": "https://images.mktw.net/im-48364873",
      "published": "2026-09-24T18:29:00+00:00",
      "published_display": "24.09 18:29",
      "sentiment": "negative",
      "tickers": [
        "UST10Y"
      ],
      "sectors": [
        "Bonds / Macro"
      ],
      "importance": 35.0,
      "content_type": "macro_context",
      "llm_classified": true
    },
    {
      "title": "S&P 500 is little changed as traders weigh rising yields against optimism over Strait of Hormuz reopening: Live updates",
      "link": "https://www.cnbc.com/2026/09/23/stock-market-today-live-updates.html",
      "description": "Stocks fell on Thursday as Treasury yields kept marching higher, with traders anticipating further rate hikes from the Federal Reserve.",
      "source": "CNBC",
      "image": "",
      "published": "2026-09-24T18:28:34+00:00",
      "published_display": "24.09 18:28",
      "sentiment": "neutral",
      "tickers": [
        "UST10Y",
        "FED",
        "SPY"
      ],
      "sectors": [
        "Bonds / Macro",
        "ETFs / Indices"
      ],
      "importance": 30.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "It’s no secret that Social Security and Medicare are on the ropes. Here’s what to do instead of panicking.",
      "link": "https://www.marketwatch.com/story/everyone-knows-social-security-and-medicare-are-on-the-ropes-heres-what-to-do-instead-of-panicking-717ff133?mod=mw_rss_topstories",
      "description": "With midterm elections around the corner, voters are voicing concern about the future of these programs as rising costs imperil household finances",
      "source": "MarketWatch",
      "image": "https://images.mktw.net/im-94887695",
      "published": "2026-09-24T18:24:00+00:00",
      "published_display": "24.09 18:24",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 10.0,
      "content_type": "macro_context",
      "llm_classified": true
    },
    {
      "title": "Bond liquidation wrecks small caps. Here's how bad some traders see it getting",
      "link": "https://www.cnbc.com/2026/09/24/bond-liquidation-wrecks-small-caps-heres-how-bad-some-traders-see-it-getting.html",
      "description": "While the S&P 500 powers through rising bond yields and higher crude oil prices, one section of the U.S. stock market is falling behind.",
      "source": "CNBC",
      "image": "",
      "published": "2026-09-24T18:22:51+00:00",
      "published_display": "24.09 18:22",
      "sentiment": "negative",
      "tickers": [
        "SPY"
      ],
      "sectors": [
        "ETFs / Indices"
      ],
      "importance": 40.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "FAFSA opens early: Why families should apply for college aid now",
      "link": "https://www.cnbc.com/2026/09/24/fafsa-opens-early-college-aid.html",
      "description": "College-bound students and their families can now complete the 2027-28 Free Application for Federal Student Aid, or FAFSA.",
      "source": "CNBC",
      "image": "",
      "published": "2026-09-24T18:19:40+00:00",
      "published_display": "24.09 18:19",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 5.0,
      "content_type": "macro_context",
      "llm_classified": true
    },
    {
      "title": "GM, Ford to see US market-share slide, forecaster predicts",
      "link": "https://www.investing.com/news/stock-market-news/gm-ford-to-see-us-marketshare-slide-forecaster-predicts-4916006",
      "description": "",
      "source": "Investing.com",
      "image": "https://content-media.investing.com/trkd-images/LYNXMPEM8N1OB_L.jpg",
      "published": "2026-09-24T18:18:26",
      "published_display": "24.09 18:18",
      "sentiment": "negative",
      "tickers": [
        "F"
      ],
      "sectors": [
        "Automotive / EV"
      ],
      "importance": 25.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Social Security stopped our checks due to a hacked bank account. We’re relying on our church for help. What can we do?",
      "link": "https://www.marketwatch.com/story/social-security-stopped-our-checks-due-to-a-hacked-bank-account-were-relying-on-our-church-for-help-what-can-we-do-a9464325?mod=mw_rss_topstories",
      "description": "“We are relying on our church for our current needs.”",
      "source": "MarketWatch",
      "image": "https://images.mktw.net/im-79834862",
      "published": "2026-09-24T18:17:00+00:00",
      "published_display": "24.09 18:17",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 5.0,
      "content_type": "macro_context",
      "llm_classified": true
    },
    {
      "title": "Apollo Global Management options see record put volume with 94:1 put/call ratio",
      "link": "https://www.investing.com/news/stock-market-news/apollo-global-management-options-see-record-put-volume-with-941-putcall-ratio-93CH-4916005",
      "description": "",
      "source": "Investing.com",
      "image": "https://content-media.investing.com/news/LYNXMPEM5F17R_1200_L.jpg",
      "published": "2026-09-24T18:16:36",
      "published_display": "24.09 18:16",
      "sentiment": "negative",
      "tickers": [
        "APO"
      ],
      "sectors": [
        "Banking & Finance"
      ],
      "importance": 25.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Everpure options activity points to bullish positioning with long-dated upside bets",
      "link": "https://www.investing.com/news/stock-market-news/everpure-options-activity-points-to-bullish-positioning-with-longdated-upside-bets-93CH-4916002",
      "description": "",
      "source": "Investing.com",
      "image": "https://content-media.investing.com/news/LYNXMPEM531LT_1200_L.jpg",
      "published": "2026-09-24T18:13:27",
      "published_display": "24.09 18:13",
      "sentiment": "positive",
      "tickers": [],
      "sectors": [],
      "importance": 15.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Stocks Retreat as Bond Yields Climb on Inflation Risks",
      "link": "https://www.nasdaq.com/articles/stocks-retreat-bond-yields-climb-inflation-risks",
      "description": "The S&P 500 Index ($SPX ) (SPY ) is down by -0.41% today, the Dow Jones Industrial Average ($DOWI ) (DIA ) is down by -0.58%, and the Nasdaq 100 Index ($IUXX ) (QQQ ) is down -0.68%. December E-mini S&P futures (ESZ26 ) are down -0.48%,…",
      "source": "Nasdaq",
      "image": "",
      "published": "2026-09-24T18:12:32+00:00",
      "published_display": "24.09 18:12",
      "sentiment": "negative",
      "tickers": [
        "SPY",
        "QQQ",
        "DJI"
      ],
      "sectors": [
        "ETFs / Indices"
      ],
      "importance": 30.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Dollar Gains on US Economic Strength and Hawkish Fed Comments",
      "link": "https://www.nasdaq.com/articles/dollar-gains-us-economic-strength-and-hawkish-fed-comments",
      "description": "The dollar index (DXY00 ) extended this week’s rally today to a 1.75-month high and is up by +0.14%. The dollar has support from signs of strength in the US economy after weekly jobless claims unexpectedly fell to a 2-month low,…",
      "source": "Nasdaq",
      "image": "",
      "published": "2026-09-24T18:12:32+00:00",
      "published_display": "24.09 18:12",
      "sentiment": "positive",
      "tickers": [],
      "sectors": [],
      "importance": 25.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Stocks Fall as the 10-Year T-note Yield Soars to a 19-Year High",
      "link": "https://www.nasdaq.com/articles/stocks-fall-10-year-t-note-yield-soars-19-year-high",
      "description": "The S&P 500 Index ($SPX ) (SPY ) closed down by -0.75% on Wednesday, the Dow Jones Industrial Average ($DOWI ) (DIA ) closed down by -0.68%, and the Nasdaq 100 Index ($IUXX ) (QQQ ) closed down -0.85%. December E-mini S&P futures (ESZ26…",
      "source": "Nasdaq",
      "image": "",
      "published": "2026-09-24T18:12:31+00:00",
      "published_display": "24.09 18:12",
      "sentiment": "negative",
      "tickers": [
        "SPY",
        "QQQ",
        "DJI"
      ],
      "sectors": [
        "ETFs / Indices"
      ],
      "importance": 35.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "OpenAI’s former head of data centers joins Nvidia",
      "link": "https://www.investing.com/news/stock-market-news/openais-former-head-of-data-centers-joins-nvidia-4915998",
      "description": "",
      "source": "Investing.com",
      "image": "https://content-media.investing.com/news/moved_LYNXMPEM4I1BN_L.jpg",
      "published": "2026-09-24T18:11:47",
      "published_display": "24.09 18:11",
      "sentiment": "positive",
      "tickers": [
        "NVDA"
      ],
      "sectors": [
        "Semiconductors"
      ],
      "importance": 15.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Here are 3 alternatives for investors looking to dodge the bond-market beatdown",
      "link": "https://www.marketwatch.com/story/here-are-3-alternatives-for-investors-looking-to-dodge-the-bond-market-beatdown-ec8fda43?mod=mw_rss_topstories",
      "description": "U.S. stocks have kept chugging higher this year, but bonds haven’t been able to shake off a five-year slump. That has sent some investors interested in a diversified portfolio searching for alternatives.",
      "source": "MarketWatch",
      "image": "https://images.mktw.net/im-00375297",
      "published": "2026-09-24T18:07:00+00:00",
      "published_display": "24.09 18:07",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 15.0,
      "content_type": "macro_context",
      "llm_classified": true
    },
    {
      "title": "US energy secretary seeks refiners’ help amid narrow options to curb diesel price",
      "link": "https://www.investing.com/news/stock-market-news/us-energy-secretary-seeks-refiners-help-amid-narrow-options-to-curb-diesel-price-4915993",
      "description": "",
      "source": "Investing.com",
      "image": "https://content-media.investing.com/trkd-images/LYNXMPEM8N1NU_L.jpg",
      "published": "2026-09-24T18:06:48",
      "published_display": "24.09 18:06",
      "sentiment": "positive",
      "tickers": [],
      "sectors": [],
      "importance": 25.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Oracle, Facebook lead market cap stock movers on Thursday",
      "link": "https://www.investing.com/news/stock-market-news/oracle-facebook-lead-market-cap-stock-movers-on-thursday-93CH-4915997",
      "description": "",
      "source": "Investing.com",
      "image": "https://content-media.investing.com/news/moved_LYNXMPEH9R17G_L.jpg",
      "published": "2026-09-24T18:05:48",
      "published_display": "24.09 18:05",
      "sentiment": "neutral",
      "tickers": [
        "ORCL",
        "META"
      ],
      "sectors": [
        "Big Tech",
        "Software / Cloud"
      ],
      "importance": 12.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Dry Conditions in West Africa Boost Cocoa Prices",
      "link": "https://www.nasdaq.com/articles/dry-conditions-west-africa-boost-cocoa-prices",
      "description": "December ICE NY cocoa (CCZ26 ) is up +71 (+1.28%) today, and December ICE London cocoa #7 (CAZ26 ) is up +63 (+1.53%). Cocoa prices are climbing for a second session today amid dry conditions in West Africa. Forecasts for below-normal…",
      "source": "Nasdaq",
      "image": "",
      "published": "2026-09-24T18:05:39+00:00",
      "published_display": "24.09 18:05",
      "sentiment": "positive",
      "tickers": [],
      "sectors": [],
      "importance": 20.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Pete Hegseth reports at least $3.1 million in cash, investments and Bitcoin",
      "link": "https://www.cnbc.com/2026/09/24/pete-hegseth-financial-disclosure-cash-investments-bitcoin.html",
      "description": "Defense Secretary Pete Hegseth reported at least $3.1 million in assets as he faces an impeachment push in Congress over his handling of the Iran war.",
      "source": "CNBC",
      "image": "",
      "published": "2026-09-24T18:05:37+00:00",
      "published_display": "24.09 18:05",
      "sentiment": "neutral",
      "tickers": [
        "BTC"
      ],
      "sectors": [
        "Cryptocurrencies"
      ],
      "importance": 10.0,
      "content_type": "macro_context",
      "llm_classified": true
    },
    {
      "title": "White House allows blocked reporters in after judge lifts Trump ban",
      "link": "https://www.cnbc.com/2026/09/24/judge-lifts-trumps-white-house-ban-on-cnn-ms-now-and-politico.html",
      "description": "District Judge Tim Kelly said the three outlets should have their access immediately restored from the ban the president had announced on Sept. 18.",
      "source": "CNBC",
      "image": "",
      "published": "2026-09-24T18:02:17+00:00",
      "published_display": "24.09 18:02",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 8.0,
      "content_type": "macro_context",
      "llm_classified": true
    },
    {
      "title": "Durable goods orders highlight economic data due Friday",
      "link": "https://www.investing.com/news/stock-market-news/durable-goods-orders-highlight-economic-data-due-friday-93CH-4915994",
      "description": "",
      "source": "Investing.com",
      "image": "https://content-media.investing.com/news/SP500StandardandPoors500Index_800x533_L_1657544297.jpg",
      "published": "2026-09-24T18:00:38",
      "published_display": "24.09 18:00",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 25.0,
      "content_type": "macro_context",
      "llm_classified": true
    },
    {
      "title": "Sugar Prices Pressured as Supply Concerns Ease",
      "link": "https://www.nasdaq.com/articles/sugar-prices-pressured-supply-concerns-ease",
      "description": "October NY world sugar #11 (SBV26 ) is down -0.17 (-0.96%) today, and December London ICE white sugar #5 (SWZ26 ) is up +1.60 (+0.32%). Sugar prices are mixed today. Sugar prices are under pressure from Wednesday, when StoneX narrowed…",
      "source": "Nasdaq",
      "image": "",
      "published": "2026-09-24T18:00:33+00:00",
      "published_display": "24.09 18:00",
      "sentiment": "negative",
      "tickers": [],
      "sectors": [],
      "importance": 15.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Crude Prices Surge as Risks to Middle East Crude Supplies Intensify",
      "link": "https://www.nasdaq.com/articles/crude-prices-surge-risks-middle-east-crude-supplies-intensify",
      "description": "November WTI crude oil (CLX26 ) is up +3.70 (+4.01%) today, and November RBOB gasoline (RBX26 ) is up +0.0553 (+1.66%). Crude oil and gasoline prices are moving sharply higher today, with gasoline posting a 4-month high. Crude prices…",
      "source": "Nasdaq",
      "image": "",
      "published": "2026-09-24T18:00:33+00:00",
      "published_display": "24.09 18:00",
      "sentiment": "positive",
      "tickers": [],
      "sectors": [],
      "importance": 45.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Analysis: Higher Treasury yields deliver a reality check on a hot, inflation-prone economy",
      "link": "https://www.cnbc.com/2026/09/24/treasury-yields-warsh-bessent-fed-national-debt-analysis.html",
      "description": "Elevated Treasury yields will complicate both Federal Reserve policy and Treasury financing.",
      "source": "CNBC",
      "image": "",
      "published": "2026-09-24T17:56:42+00:00",
      "published_display": "24.09 17:56",
      "sentiment": "negative",
      "tickers": [
        "UST10Y",
        "FED"
      ],
      "sectors": [
        "Bonds / Macro"
      ],
      "importance": 40.0,
      "content_type": "macro_context",
      "llm_classified": true
    },
    {
      "title": "3 reasons now is the right time to plan your 2027 summer holiday",
      "link": "https://www.cnbc.com/select/why-is-now-the-right-time-to-plan-your-2027-summer-holiday/",
      "description": "Planning ahead can help you maximize travel rewards and take advantage of price changes.",
      "source": "CNBC",
      "image": "",
      "published": "2026-09-24T17:56:24+00:00",
      "published_display": "24.09 17:56",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 3.0,
      "content_type": "macro_context",
      "llm_classified": true
    },
    {
      "title": "Wells Fargo Initiates Coverage of Old National Bancorp - Preferred Stock at Overweight",
      "link": "https://www.nasdaq.com/articles/wells-fargo-initiates-coverage-old-national-bancorp-preferred-stock-overweight",
      "description": "Fintel reports that on September 24, 2026, Wells Fargo initiated coverage of Old National Bancorp - Preferred Stock (NASDAQGS:ONBPP) with a Overweight recommendation. Old National Bancorp, based in the United States, operates primarily…",
      "source": "Nasdaq",
      "image": "",
      "published": "2026-09-24T17:50:12+00:00",
      "published_display": "24.09 17:50",
      "sentiment": "positive",
      "tickers": [
        "WFC"
      ],
      "sectors": [
        "Banking & Finance"
      ],
      "importance": 10.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Stocks Pressured by Rising Crude Prices",
      "link": "https://www.nasdaq.com/articles/stocks-pressured-rising-crude-prices",
      "description": "The S&P 500 Index ($SPX ) (SPY ) is down by -0.36% today, the Dow Jones Industrial Average ($DOWI ) (DIA ) is down by -0.44%, and the Nasdaq 100 Index ($IUXX ) (QQQ ) is down -0.55%. December E-mini S&P futures (ESZ26 ) are down -0.36%,…",
      "source": "Nasdaq",
      "image": "",
      "published": "2026-09-24T17:49:16+00:00",
      "published_display": "24.09 17:49",
      "sentiment": "negative",
      "tickers": [
        "SPY",
        "QQQ",
        "DJI"
      ],
      "sectors": [
        "ETFs / Indices"
      ],
      "importance": 30.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "White House asks AI firms to delay sharing models with UK - report",
      "link": "https://www.investing.com/news/stock-market-news/white-house-asks-ai-firms-to-delay-sharing-models-with-uk--report-4915983",
      "description": "",
      "source": "Investing.com",
      "image": "https://content-media.investing.com/news/moved_LYNXMPEM54006_L.jpg",
      "published": "2026-09-24T17:47:54",
      "published_display": "24.09 17:47",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 15.0,
      "content_type": "macro_context",
      "llm_classified": true
    },
    {
      "title": "A new bill in Congress would lower the retirement age to 60. See who would qualify.",
      "link": "https://www.marketwatch.com/story/a-new-bill-in-congress-would-lower-the-retirement-age-to-60-see-who-would-qualify-10563052?mod=mw_rss_topstories",
      "description": "A new bill calling for lowering Social Security’s full retirement age from 67 to 60 for workers in physically demanding jobs could put additional strain on the trust fund that backs the system and create a two-tiered system among…",
      "source": "MarketWatch",
      "image": "https://images.mktw.net/im-99081604",
      "published": "2026-09-24T17:47:00+00:00",
      "published_display": "24.09 17:47",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 10.0,
      "content_type": "macro_context",
      "llm_classified": true
    },
    {
      "title": "Rising Treasury yields could push car loan rates higher, experts say. What buyers need to know",
      "link": "https://www.cnbc.com/2026/09/24/car-loan-rates-may-rise-as-treasury-yields-climb.html",
      "description": "Bond yields have spiked due to expectations of persistent inflation and further interest rate hikes from the Federal Reserve, which may impact auto loan rates.",
      "source": "CNBC",
      "image": "",
      "published": "2026-09-24T17:45:53+00:00",
      "published_display": "24.09 17:45",
      "sentiment": "negative",
      "tickers": [
        "UST10Y",
        "FED"
      ],
      "sectors": [
        "Bonds / Macro"
      ],
      "importance": 20.0,
      "content_type": "macro_context",
      "llm_classified": true
    },
    {
      "title": "New York sues Polymarket U.S., two months after filing lawsuit against Kalshi",
      "link": "https://www.cnbc.com/2026/09/24/new-york-sues-polymarket-us-two-months-after-filing-suit-against-kalshi-.html",
      "description": "State attorney general Letitia James claims Polymarket has violated the state's gambling laws.",
      "source": "CNBC",
      "image": "",
      "published": "2026-09-24T17:44:32+00:00",
      "published_display": "24.09 17:44",
      "sentiment": "negative",
      "tickers": [],
      "sectors": [],
      "importance": 25.0,
      "content_type": "macro_context",
      "llm_classified": true
    },
    {
      "title": "Coffee Prices Fall as Conab Raises its Brazil Coffee Production Estimate",
      "link": "https://www.nasdaq.com/articles/coffee-prices-fall-conab-raises-its-brazil-coffee-production-estimate",
      "description": "December arabica coffee (KCZ26 ) is down -1.00 (-0.36%) today, and November ICE robusta coffee (RMX26 ) is down -38 (-1.15%). Coffee prices are moving lower today but remain above Wednesday’s 3-month lows. Coffee prices are under…",
      "source": "Nasdaq",
      "image": "",
      "published": "2026-09-24T17:43:26+00:00",
      "published_display": "24.09 17:43",
      "sentiment": "negative",
      "tickers": [],
      "sectors": [],
      "importance": 20.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Ex-Div Reminder for Fifth Third Bancorp's Preferred Stock, Series I",
      "link": "https://www.nasdaq.com/articles/ex-div-reminder-fifth-third-bancorps-preferred-stock-series-i",
      "description": "On 9/28/26, Fifth Third Bancorp's 6.625% Dep Shares Fixed/Float Non-Cumul Pfd Stock, Series I (Symbol: FITB.PRI) will trade ex-dividend, for its quarterly dividend of $0.4922, payable on 9/30/26. As a percentage of FITB.PRI's recent…",
      "source": "Nasdaq",
      "image": "",
      "published": "2026-09-24T17:37:37+00:00",
      "published_display": "24.09 17:37",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 5.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "RedBird Capital to acquire majority stake in Puck at $250 million valuation, memo says",
      "link": "https://www.investing.com/news/stock-market-news/redbird-capital-to-acquire-majority-stake-in-puck-at-250-million-valuation-memo-says-4915973",
      "description": "",
      "source": "Investing.com",
      "image": "https://content-media.investing.com/trkd-images/LYNXMPEM8N1MP_L.jpg",
      "published": "2026-09-24T17:37:35",
      "published_display": "24.09 17:37",
      "sentiment": "positive",
      "tickers": [],
      "sectors": [],
      "importance": 15.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Thursday's ETF with Unusual Volume: INRO",
      "link": "https://www.nasdaq.com/articles/thursdays-etf-unusual-volume-inro",
      "description": "The iShares U.S. Industry Rotation Active ETF is seeing unusually high volume in afternoon trading Thursday, with over 854,000 shares traded versus three month average volume of about 97,000. Shares of INRO were up about 0.1% on the…",
      "source": "Nasdaq",
      "image": "",
      "published": "2026-09-24T17:37:02+00:00",
      "published_display": "24.09 17:37",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 8.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Trump-Xi summit in Washington begins with great fanfare but low expectations",
      "link": "https://www.investing.com/news/stock-market-news/trump-welcomes-xi-to-washington-looking-for-a-trade-win-4914436",
      "description": "",
      "source": "Investing.com",
      "image": "https://content-media.investing.com/trkd-images/LYNXMPEM8N0BG_L.jpg",
      "published": "2026-09-24T17:36:53",
      "published_display": "24.09 17:36",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 35.0,
      "content_type": "macro_context",
      "llm_classified": true
    },
    {
      "title": "Thursday's ETF Movers: ARKG, TAN",
      "link": "https://www.nasdaq.com/articles/thursdays-etf-movers-arkg-tan",
      "description": "In trading on Thursday, the ARK Genomic Revolution ETF is outperforming other ETFs, up about 2.6% on the day. Components of that ETF showing particular strength include shares of Caredx, up about 13.5% and shares of Twist Bioscience, up…",
      "source": "Nasdaq",
      "image": "",
      "published": "2026-09-24T17:36:05+00:00",
      "published_display": "24.09 17:36",
      "sentiment": "positive",
      "tickers": [],
      "sectors": [],
      "importance": 15.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Thursday 9/24 Insider Buying Report: INR, AIAI",
      "link": "https://www.nasdaq.com/articles/thursday-9-24-insider-buying-report-inr-aiai",
      "description": "Bargain hunters are wise to pay careful attention to insider buying, because although there are many various reasons for an insider to sell a stock, presumably the only reason they would use their hard-earned cash to make a purchase, is…",
      "source": "Nasdaq",
      "image": "",
      "published": "2026-09-24T17:35:21+00:00",
      "published_display": "24.09 17:35",
      "sentiment": "positive",
      "tickers": [],
      "sectors": [],
      "importance": 8.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "As bond rout worsens, a trade Wall Street uses to replace them booms in popularity",
      "link": "https://www.cnbc.com/2026/09/24/as-bond-rout-worsens-a-trade-wall-street-uses-to-replace-them-booms-in-popularity.html",
      "description": "The options strategy is known as a \"box spread.\"",
      "source": "CNBC",
      "image": "",
      "published": "2026-09-24T17:30:23+00:00",
      "published_display": "24.09 17:30",
      "sentiment": "neutral",
      "tickers": [
        "MSTR"
      ],
      "sectors": [
        "Cryptocurrencies"
      ],
      "importance": 20.0,
      "content_type": "macro_context",
      "llm_classified": true
    },
    {
      "title": "ROTHSCHILD & CO REDBURN Upgrades Moncler S.p.A. - Depositary Receipt to Buy from Neutral",
      "link": "https://www.nasdaq.com/articles/rothschild-co-redburn-upgrades-moncler-spa-depositary-receipt-buy-neutral",
      "description": "Fintel reports that on September 23, 2026, ROTHSCHILD & CO REDBURN upgraded their outlook for Moncler S.p.A. - Depositary Receipt (OTCPK:MONRY) (DB:MOV0) from Neutral to Buy. This rating action follows a prior action on July 8, 2026,…",
      "source": "Nasdaq",
      "image": "",
      "published": "2026-09-24T17:18:39+00:00",
      "published_display": "24.09 17:18",
      "sentiment": "positive",
      "tickers": [],
      "sectors": [],
      "importance": 12.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "‘We made a bad, bad decision’: I learned the hard way how to manage my aging father’s money",
      "link": "https://www.marketwatch.com/story/we-made-a-bad-bad-decision-i-learned-the-hard-way-how-to-manage-my-aging-fathers-money-c87cabed?mod=mw_rss_topstories",
      "description": "“When my father died, his trust was the Bible.”",
      "source": "MarketWatch",
      "image": "https://images.mktw.net/im-75524086",
      "published": "2026-09-24T17:15:00+00:00",
      "published_display": "24.09 17:15",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 3.0,
      "content_type": "macro_context",
      "llm_classified": true
    },
    {
      "title": "Philadelphia Fed's Anna Paulson says 'modest' rate moves likely ahead to tame inflation",
      "link": "https://www.cnbc.com/2026/09/24/philadelphia-feds-anna-paulson-says-modest-rate-moves-likely-ahead-to-tame-inflation.html",
      "description": "The policymaker said she and her colleagues may need to raise interest rates further to bring inflation back to target.",
      "source": "CNBC",
      "image": "",
      "published": "2026-09-24T17:12:04+00:00",
      "published_display": "24.09 17:12",
      "sentiment": "negative",
      "tickers": [],
      "sectors": [],
      "importance": 30.0,
      "content_type": "macro_context",
      "llm_classified": true
    },
    {
      "title": "Meta nears first new high in a year as Muse success showcases winning AI strategy",
      "link": "https://www.cnbc.com/2026/09/24/meta-nears-first-new-high-in-a-year-as-muse-success-showcases-winning-ai-strategy.html",
      "description": "Meta is transforming into more than a social-media juggernaut in the AI era. Muse is the centerpiece of its strategy.",
      "source": "CNBC",
      "image": "",
      "published": "2026-09-24T17:07:45+00:00",
      "published_display": "24.09 17:07",
      "sentiment": "positive",
      "tickers": [
        "META",
        "MSTR"
      ],
      "sectors": [
        "Big Tech",
        "Cryptocurrencies"
      ],
      "importance": 20.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Soybeans Bouncing Higher on Thursday Morning",
      "link": "https://www.nasdaq.com/articles/soybeans-bouncing-higher-thursday-morning",
      "description": "Soybeans are trading with gains of 4 to 5 ¼ cents across the nearbys at midday. Futures rounded out the Wednesday session with most contracts fractionally to 7 ½ cents higher at the close. Open interest was up 4,380 contracts on…",
      "source": "Nasdaq",
      "image": "",
      "published": "2026-09-24T16:59:39+00:00",
      "published_display": "24.09 16:59",
      "sentiment": "positive",
      "tickers": [],
      "sectors": [],
      "importance": 10.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Student loan borrowers sue Trump administration over forgiven debts on credit reports",
      "link": "https://www.cnbc.com/2026/09/24/student-loan-borrowers-sue-credit-reports-forgiven-loans.html",
      "description": "Student loan holders sued the Education Department on Thursday, claiming they suffered financial damages despite getting their debts forgiven years ago.",
      "source": "CNBC",
      "image": "",
      "published": "2026-09-24T16:49:40+00:00",
      "published_display": "24.09 16:49",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 8.0,
      "content_type": "macro_context",
      "llm_classified": true
    },
    {
      "title": "Oracle sends 'force majeure' notice about data center project — stock sinks 4%",
      "link": "https://www.cnbc.com/2026/09/24/oracle-data-center-force-majeure.html",
      "description": "Oracle is reportedly looking to delay payment on Project Jupiter if it the data center fails to come online in 2028",
      "source": "CNBC",
      "image": "",
      "published": "2026-09-24T16:48:38+00:00",
      "published_display": "24.09 16:48",
      "sentiment": "negative",
      "tickers": [
        "ORCL"
      ],
      "sectors": [
        "Software / Cloud"
      ],
      "importance": 35.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Oracle’s stock is falling as investors fear a data-center setback",
      "link": "https://www.marketwatch.com/story/oracles-stock-is-falling-as-investors-fear-a-data-center-setback-d8105ef9?mod=mw_rss_topstories",
      "description": "A recent report noted that Oracle is looking to protect itself from paying some expenses if a high-profile data-center project gets delayed.",
      "source": "MarketWatch",
      "image": "https://images.mktw.net/im-49193114",
      "published": "2026-09-24T16:42:00+00:00",
      "published_display": "24.09 16:42",
      "sentiment": "negative",
      "tickers": [
        "ORCL"
      ],
      "sectors": [
        "Software / Cloud"
      ],
      "importance": 30.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Do this one thing to help prevent your parents from being scammed",
      "link": "https://www.marketwatch.com/story/do-this-one-thing-to-help-prevent-your-parents-from-being-scammed-27a0ca4b?mod=mw_rss_topstories",
      "description": "“I felt like I was talking to a robot,” said one adviser about a client who was ensnared in a romance scam.",
      "source": "MarketWatch",
      "image": "https://images.mktw.net/im-93049114",
      "published": "2026-09-24T16:36:00+00:00",
      "published_display": "24.09 16:36",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 5.0,
      "content_type": "macro_context",
      "llm_classified": true
    },
    {
      "title": "Hyundai expected to outsell Ford in third quarter as Detroit automakers lack hybrids",
      "link": "https://www.cnbc.com/2026/09/24/hyundai-set-to-outsell-ford-in-q3-as-detroit-automakers-lack-hybrids.html",
      "description": "Cox analysts said Ford and General Motors are seeing sales lag because they don't have many hybrid vehicles.",
      "source": "CNBC",
      "image": "",
      "published": "2026-09-24T16:33:15+00:00",
      "published_display": "24.09 16:33",
      "sentiment": "positive",
      "tickers": [
        "F",
        "GM",
        "HYMTF"
      ],
      "sectors": [
        "Automotive / EV"
      ],
      "importance": 25.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Trump, Xi to talk Taiwan, AI, trade and Iran as DC summit kicks off",
      "link": "https://www.cnbc.com/2026/09/24/trump-xi-meeting-china-washington.html",
      "description": "Trump greeted China's Xi at Joint Base Andrews, marking the U.S. president's first time traveling to the facility to welcome a foreign leader.",
      "source": "CNBC",
      "image": "",
      "published": "2026-09-24T16:26:47+00:00",
      "published_display": "24.09 16:26",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 45.0,
      "content_type": "macro_context",
      "llm_classified": true
    },
    {
      "title": "Darden Restaurants stock falls as Olive Garden reports slower growth",
      "link": "https://www.cnbc.com/2026/09/24/darden-restaurants-dri-q1-2027-earnings.html",
      "description": "Olive Garden's same-store sales growth has slowed in recent quarters.",
      "source": "CNBC",
      "image": "",
      "published": "2026-09-24T16:13:13+00:00",
      "published_display": "24.09 16:13",
      "sentiment": "negative",
      "tickers": [],
      "sectors": [],
      "importance": 25.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "MGM Resorts shares sink 9% after Barry Diller's People Inc. rescinds takeover offer",
      "link": "https://www.cnbc.com/2026/09/24/barry-diller-people-mgm-resorts.html",
      "description": "Barry Diller's People Inc. has rescinded its offer to buy the remaining public shares of MGM Resorts.",
      "source": "CNBC",
      "image": "",
      "published": "2026-09-24T16:06:00+00:00",
      "published_display": "24.09 16:06",
      "sentiment": "negative",
      "tickers": [],
      "sectors": [],
      "importance": 45.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "The 'Magnificent Seven' is bucking the market trend. Why the jump in Treasury yields may be helping",
      "link": "https://www.cnbc.com/2026/09/24/magnificent-seven-rallies-as-treasury-yields-rise.html",
      "description": "The tech giants surged to all-time highs this week, a surprising show of strength given that the group has floundered for much of this year.",
      "source": "CNBC",
      "image": "",
      "published": "2026-09-24T16:05:26+00:00",
      "published_display": "24.09 16:05",
      "sentiment": "positive",
      "tickers": [
        "UST10Y"
      ],
      "sectors": [
        "Bonds / Macro"
      ],
      "importance": 35.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Mark Zuckerberg debuts $1,299 Meta VR Glasses and Muse Charm pendant as part of AI agent push",
      "link": "https://www.cnbc.com/2026/09/23/mark-zuckerberg-1299-meta-vr-glasses-ai-agent.html",
      "description": "At Meta Connect, CEO Mark Zuckerberg revealed new VR Glasses and the Muse Charm gadget for AI agents.",
      "source": "CNBC",
      "image": "",
      "published": "2026-09-24T15:56:24+00:00",
      "published_display": "24.09 15:56",
      "sentiment": "positive",
      "tickers": [
        "META"
      ],
      "sectors": [
        "Big Tech"
      ],
      "importance": 25.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Crypto casino Duelbits goes offline after $7 million hot wallet hack",
      "link": "https://www.coindesk.com/business/2026/09/24/crypto-casino-duelbits-goes-offline-after-usd7m-hot-wallet-hack",
      "description": "Attackers drained Duelbits' hot wallets across four blockchains; about $6 million in stolen funds now sits in a single Ethereum address.",
      "source": "CoinDesk",
      "image": "https://cdn.sanity.io/images/s3y3vcno/production/70172f53cfba9b4db9ca138599dd8ee6f4d188da-1920x1080.png?fm=jpg&w=1920&h=1080&crop=focalpoint&fit=clip",
      "published": "2026-09-24T15:48:20+00:00",
      "published_display": "24.09 15:48",
      "sentiment": "negative",
      "tickers": [
        "ETH"
      ],
      "sectors": [
        "Cryptocurrencies"
      ],
      "importance": 20.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "30-year Treasury yield hits highest level since 2004 as bond market rout continues",
      "link": "https://www.cnbc.com/2026/09/24/us-treasury-yields-bonds-fed-inflation.html",
      "description": "U.S. Treasury yields continued their upward momentum after hitting a 19-year high on Wednesday.",
      "source": "CNBC",
      "image": "",
      "published": "2026-09-24T15:41:37+00:00",
      "published_display": "24.09 15:41",
      "sentiment": "negative",
      "tickers": [
        "UST10Y"
      ],
      "sectors": [
        "Bonds / Macro"
      ],
      "importance": 50.0,
      "content_type": "macro_context",
      "llm_classified": true
    },
    {
      "title": "Bitcoin’s bear markets are getting milder. Bull markets may be next",
      "link": "https://www.coindesk.com/markets/2026/09/24/bitcoin-s-bear-markets-are-getting-milder-the-bull-markets-may-be-next",
      "description": "Bitcoin’s latest bear market was milder than past crashes as ETFs, institutional investors and a maturing market reshape its cycles.",
      "source": "CoinDesk",
      "image": "https://cdn.sanity.io/images/s3y3vcno/production/b18259d0df35543019d1ba0311d7775aec49d301-6000x4000.jpg?fm=jpg&w=1920&h=1080&crop=focalpoint&fit=clip",
      "published": "2026-09-24T15:26:34+00:00",
      "published_display": "24.09 15:26",
      "sentiment": "positive",
      "tickers": [
        "BTC"
      ],
      "sectors": [
        "Cryptocurrencies"
      ],
      "importance": 20.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "An optical stock has been on Josh Brown's list all year. The chart looks explosive",
      "link": "https://www.cnbc.com/2026/09/24/an-optical-stock-has-been-on-josh-browns-list-all-year-the-chart-looks-explosive.html",
      "description": "Sometimes a company is perfectly positioned for a secular change. Josh Brown thinks this optical name is one of them.",
      "source": "CNBC",
      "image": "",
      "published": "2026-09-24T15:09:50+00:00",
      "published_display": "24.09 15:09",
      "sentiment": "positive",
      "tickers": [],
      "sectors": [],
      "importance": 10.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Gold price slides as oil, Fed rate concerns lift dollar",
      "link": "https://www.mining.com/gold-slides-as-oil-fed-rate-concerns-lift-dollar/",
      "description": "As energy prices rise and the Fed looks into raising interest rates, gold pays the price in an uncertain market.",
      "source": "Mining.com",
      "image": "",
      "published": "2026-09-24T15:08:38+00:00",
      "published_display": "24.09 15:08",
      "sentiment": "negative",
      "tickers": [
        "FED"
      ],
      "sectors": [
        "Bonds / Macro"
      ],
      "importance": 30.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "UK’s largest banks complete world’s first interbank transactions using tokenized deposits",
      "link": "https://www.coindesk.com/business/2026/09/24/uk-s-largest-banks-complete-world-s-first-interbank-transactions-using-tokenized-deposits",
      "description": "Barclays, NatWest, and HSBC and others used tokenized deposits for remortgages and a marketplace-payment test, taking bank-issued digital cash beyond a single institution.",
      "source": "CoinDesk",
      "image": "https://cdn.sanity.io/images/s3y3vcno/production/6a55120319f442a7083bbe28359db7f277af29df-5745x3830.jpg?fm=jpg&w=1920&h=1080&crop=focalpoint&fit=clip",
      "published": "2026-09-24T15:07:18+00:00",
      "published_display": "24.09 15:07",
      "sentiment": "positive",
      "tickers": [],
      "sectors": [],
      "importance": 25.0,
      "content_type": "macro_context",
      "llm_classified": true
    },
    {
      "title": "Crypto for Advisors:The hidden costs of holding your own bitcoin",
      "link": "https://www.coindesk.com/coindesk-indices/2026/09/24/crypto-for-advisors-the-hidden-costs-of-holding-your-own-bitcoin",
      "description": "",
      "source": "CoinDesk",
      "image": "https://cdn.sanity.io/images/s3y3vcno/production/4889aa09a0863ef0cebc37a86da760e7c58f0735-2667x4000.jpg?fm=jpg&w=1920&h=1080&crop=focalpoint&fit=clip",
      "published": "2026-09-24T14:49:28+00:00",
      "published_display": "24.09 14:49",
      "sentiment": "neutral",
      "tickers": [
        "BTC"
      ],
      "sectors": [
        "Cryptocurrencies"
      ],
      "importance": 8.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "OceanaGold’s 97-gram hit backs Waihi expansion",
      "link": "https://www.mining.com/oceanagolds-97-gram-hit-backs-waihi-expansion/",
      "description": "OceanaGold plans a 50% expansion of its Waihi plant after discovering rich gold veins in Wharekirauponga.",
      "source": "Mining.com",
      "image": "",
      "published": "2026-09-24T14:43:23+00:00",
      "published_display": "24.09 14:43",
      "sentiment": "positive",
      "tickers": [],
      "sectors": [],
      "importance": 22.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "European stablecoin issuer Qivalis sees transformation of global trade finance",
      "link": "https://www.coindesk.com/business/2026/09/24/european-stablecoin-issuer-qivalis-sees-transformation-of-global-trade-finance",
      "description": "Jan-Oliver Sell, the CEO and founder of Qivalis, said the entire trade finance supply chain is moving into stablecoins.",
      "source": "CoinDesk",
      "image": "https://cdn.sanity.io/images/s3y3vcno/production/3d9afb44b63713bb3ec5799691370b164e6f4a26-991x557.jpg?fm=jpg&w=1920&h=1080&crop=focalpoint&fit=clip",
      "published": "2026-09-24T14:41:05+00:00",
      "published_display": "24.09 14:41",
      "sentiment": "positive",
      "tickers": [],
      "sectors": [],
      "importance": 15.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Here's what happens to the economy when Treasury yields soar like they are now",
      "link": "https://www.cnbc.com/2026/09/23/what-happens-to-the-economy-when-treasury-yields-soar.html",
      "description": "Government debt costs leaped higher Wednesday, the product of multiple factors.",
      "source": "CNBC",
      "image": "",
      "published": "2026-09-24T14:37:14+00:00",
      "published_display": "24.09 14:37",
      "sentiment": "negative",
      "tickers": [
        "UST10Y"
      ],
      "sectors": [
        "Bonds / Macro"
      ],
      "importance": 45.0,
      "content_type": "macro_context",
      "llm_classified": true
    },
    {
      "title": "Family offices double down on stocks and private equity even as inflation spurs worry, Citi survey finds",
      "link": "https://www.cnbc.com/2026/09/24/citi-family-offices-inflation-investing.html",
      "description": "Inflation displaced tariffs as family offices' top investment concern in 2026, per a new Citi Wealth survey.",
      "source": "CNBC",
      "image": "",
      "published": "2026-09-24T14:36:13+00:00",
      "published_display": "24.09 14:36",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 20.0,
      "content_type": "macro_context",
      "llm_classified": true
    },
    {
      "title": "Big business warns Trump against diesel export ban in joint letter",
      "link": "https://www.cnbc.com/2026/09/24/chamber-commerce-business-roundtable-trump-diesel-export-ban-iran-war.html",
      "description": "The national average for a gallon of diesel reached $6.51 on Thursday, nearly $3 more than the same period a year ago, according to data from AAA.",
      "source": "CNBC",
      "image": "",
      "published": "2026-09-24T14:23:33+00:00",
      "published_display": "24.09 14:23",
      "sentiment": "negative",
      "tickers": [],
      "sectors": [],
      "importance": 35.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Goldman predicts this global digital bank that just launched in the U.S. could jump nearly 70%",
      "link": "https://www.cnbc.com/2026/09/24/brazilian-stock-to-get-boost-from-us-expansion-goldman-sachs-says.html",
      "description": "The investment firm has a buy rating on the Brazil-based banking name.",
      "source": "CNBC",
      "image": "",
      "published": "2026-09-24T14:00:49+00:00",
      "published_display": "24.09 14:00",
      "sentiment": "positive",
      "tickers": [],
      "sectors": [],
      "importance": 25.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Kinross Gold cuts output, boosts shareholder payout",
      "link": "https://www.mining.com/kinross-gold-cuts-output-boosts-shareholder-payout/",
      "description": "Kinross cut its 2026-2027 production outlook by 8% due to weather issues in Chile and weaker performance in Nevada.",
      "source": "Mining.com",
      "image": "",
      "published": "2026-09-24T13:52:59+00:00",
      "published_display": "24.09 13:52",
      "sentiment": "negative",
      "tickers": [],
      "sectors": [],
      "importance": 30.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Meta's standoff with Amazon over Muse could be a sign of things to come",
      "link": "https://www.cnbc.com/2026/09/23/metas-standoff-with-amazon-over-muse-comes-ahead-of-meta-connect.html",
      "description": "Meta's new Muse AI personal agent is garnering excitement and shows signs of becoming a hit, but Amazon has blocked the app from its site.",
      "source": "CNBC",
      "image": "",
      "published": "2026-09-24T13:49:39+00:00",
      "published_display": "24.09 13:49",
      "sentiment": "neutral",
      "tickers": [
        "AMZN",
        "META"
      ],
      "sectors": [
        "Big Tech"
      ],
      "importance": 20.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Saudi Oil Export Costs Surge as Red Sea Risks Mount",
      "link": "https://oilprice.com/Latest-Energy-News/World-News/Saudi-Oil-Export-Costs-Surge-as-Red-Sea-Risks-Mount.html",
      "description": "Saudi Arabia’s workaround for the Strait of Hormuz now carries a war-risk insurance bill nearly as expensive as sending tankers through Hormuz itself. Quoted premiums for Saudi-linked tankers calling at the Red Sea port of Yanbu have…",
      "source": "OilPrice.com",
      "image": "",
      "published": "2026-09-24T13:30:00-05:00",
      "published_display": "24.09 13:30",
      "sentiment": "positive",
      "tickers": [],
      "sectors": [],
      "importance": 40.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Rainbow Rare Earths deal with Neo clears path for Phalaborwa study",
      "link": "https://www.mining.com/rainbow-rare-earths-deal-with-neo-clears-path-for-phalaborwa-study/",
      "description": "The partnership advances processing plans as Rainbow moves the South African rare earths project towards financing.",
      "source": "Mining.com",
      "image": "",
      "published": "2026-09-24T13:05:00+00:00",
      "published_display": "24.09 13:05",
      "sentiment": "positive",
      "tickers": [],
      "sectors": [],
      "importance": 12.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Why Are Diesel Prices So High?",
      "link": "https://oilprice.com/Energy/Energy-General/Why-Are-Diesel-Prices-So-High.html",
      "description": "Some claims making the rounds on social media start with an observation that is basically correct: crude oil was more expensive after Russia invaded Ukraine in 2022 than it is today, yet diesel prices are now higher. The conclusion…",
      "source": "OilPrice.com",
      "image": "",
      "published": "2026-09-24T13:00:00-05:00",
      "published_display": "24.09 13:00",
      "sentiment": "negative",
      "tickers": [],
      "sectors": [],
      "importance": 30.0,
      "content_type": "macro_context",
      "llm_classified": true
    },
    {
      "title": "Cathie Wood's ARK teams with Securitize to tokenize venture fund with OpenAI, Anthropic stakes",
      "link": "https://www.coindesk.com/business/2026/09/24/cathie-wood-s-ark-teams-with-securitize-to-tokenize-venture-fund-with-openai-anthropic-stakes",
      "description": "The ARK Venture Fund is bringing exposure to sought-after private tech companies onchain through Securitize, first on Ethereum then potentially expanding to other chains.",
      "source": "CoinDesk",
      "image": "https://cdn.sanity.io/images/s3y3vcno/production/6ccf18504f2934569339f68665f855f679f37378-4312x2426.jpg?fm=jpg&w=1920&h=1080&crop=focalpoint&fit=clip",
      "published": "2026-09-24T13:00:00+00:00",
      "published_display": "24.09 13:00",
      "sentiment": "positive",
      "tickers": [
        "ETH"
      ],
      "sectors": [
        "Cryptocurrencies"
      ],
      "importance": 18.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Solana Foundation hires Binance, Polygon veterans as it ramps up tokenized finance push",
      "link": "https://www.coindesk.com/business/2026/09/24/solana-foundation-hires-binance-polygon-veterans-as-it-ramps-up-tokenized-finance-push",
      "description": "Rachel Conlan and Jamal Raees join as Solana aims to court institutions moving payments and assets onchain.",
      "source": "CoinDesk",
      "image": "https://cdn.sanity.io/images/s3y3vcno/production/be69f7e3e9544b2f09ff312d461acfec072b473d-2047x1323.png?fm=jpg&w=1920&h=1080&crop=focalpoint&fit=clip",
      "published": "2026-09-24T13:00:00+00:00",
      "published_display": "24.09 13:00",
      "sentiment": "positive",
      "tickers": [],
      "sectors": [],
      "importance": 12.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Starbucks to shutter about 250 stores in latest round of cafe closures",
      "link": "https://www.cnbc.com/2026/09/24/starbucks-to-close-250-stores.html",
      "description": "Starbucks will close about 1% of its North American cafes in the latest stage of its turnaround.",
      "source": "CNBC",
      "image": "",
      "published": "2026-09-24T12:40:27+00:00",
      "published_display": "24.09 12:40",
      "sentiment": "negative",
      "tickers": [
        "SBUX"
      ],
      "sectors": [
        "Consumer Goods"
      ],
      "importance": 28.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Crypto investment firm RockawayX is betting $150 million on yield becoming next big use case",
      "link": "https://www.coindesk.com/business/2026/09/23/rockawayx-is-betting-usd150-million-on-yield-becoming-crypto-s-next-big-use-case",
      "description": "The $2 billion digital-asset investment firm rolls out an initiative to back, build and provide liquidity to projects bringing real-world yields into DeFi.",
      "source": "CoinDesk",
      "image": "https://cdn.sanity.io/images/s3y3vcno/production/266337e9aace0244a1ed106e63ef782530f929a4-2560x1440.jpg?fm=jpg&w=1920&h=1080&crop=focalpoint&fit=clip",
      "published": "2026-09-24T12:31:53+00:00",
      "published_display": "24.09 12:31",
      "sentiment": "positive",
      "tickers": [],
      "sectors": [],
      "importance": 25.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Vitol Scoops Up 25 Million Barrels of Discounted Iraqi Crude",
      "link": "https://oilprice.com/Latest-Energy-News/World-News/Vitol-Scoops-Up-25-Million-Barrels-of-Discounted-Iraqi-Crude.html",
      "description": "Vitol has bought at least 25 million barrels of Iraqi crude for September loading, making the world’s largest independent oil trader Iraq’s second-biggest buyer behind ADNOC as Baghdad pays steep discounts to keep barrels moving through…",
      "source": "OilPrice.com",
      "image": "",
      "published": "2026-09-24T12:30:00-05:00",
      "published_display": "24.09 12:30",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 30.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "EU's financial regulator to make AI and tokenization a supervisory priority in 2027",
      "link": "https://www.coindesk.com/policy/2026/09/24/eu-s-financial-regulator-to-make-ai-and-tokenization-a-supervisory-priority-in-2027",
      "description": "European regulators will map how financial firms use the technologies in client-facing products and begin checks on the most affected businesses.",
      "source": "CoinDesk",
      "image": "https://cdn.sanity.io/images/s3y3vcno/production/94e6ebdc0df01fa3450702f6a99a15fd9ae46153-6016x4016.jpg?fm=jpg&w=1920&h=1080&crop=focalpoint&fit=clip",
      "published": "2026-09-24T12:26:43+00:00",
      "published_display": "24.09 12:26",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 20.0,
      "content_type": "macro_context",
      "llm_classified": true
    },
    {
      "title": "Tapestry to sell via Google’s Gemini app, AI Mode",
      "link": "https://www.retaildive.com/news/tapestry-sell-via-google-gemini-app-ai-mode/830890/",
      "description": "Coach and Kate Spade items are now available for purchase in Google’s AI shopping ecosystem.",
      "source": "Retail Dive",
      "image": "https://imgproxy.divecdn.com/QusCgVC0uXIasc1h0NzWuVo5fLwGsBWh2q8hkdIhrfg/g:nowe:52:193/c:3971:2244/rs:fill:1600:900:1/Z3M6Ly9kaXZlc2l0ZS1zdG9yYWdlL2RpdmVpbWFnZS9JTUctNDczOS5qcGc=.webp",
      "published": "2026-09-24T12:16:00-04:00",
      "published_display": "24.09 12:16",
      "sentiment": "positive",
      "tickers": [
        "GOOGL"
      ],
      "sectors": [
        "Big Tech"
      ],
      "importance": 20.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Lowe's is launching a drone delivery service in partnership with DoorDash, Alphabet",
      "link": "https://www.cnbc.com/2026/09/24/lowes-drones-delivery-doordash-alphabet.html",
      "description": "Lowe's is launching a drone delivery service in a partnership with DoorDash and Alphabet's Wing, CNBC has learned exclusively.",
      "source": "CNBC",
      "image": "",
      "published": "2026-09-24T12:00:01+00:00",
      "published_display": "24.09 12:00",
      "sentiment": "positive",
      "tickers": [
        "GOOGL"
      ],
      "sectors": [
        "Big Tech"
      ],
      "importance": 15.0,
      "content_type": "market_signal",
      "llm_classified": true
    }
  ]
};
