// This file is auto-generated by fetch_news.py — do not edit by hand
const NEWS_DATA = {
  "generated_at": "2026-09-29T14:58:39.545319+00:00",
  "generated_at_display": "29.09.2026 14:58",
  "summary": {
    "total": 80,
    "signal_total": 60,
    "macro_total": 20,
    "positive": 30,
    "negative": 13,
    "neutral": 17,
    "top_tickers": [
      {
        "ticker": "NVDA",
        "count": 7
      },
      {
        "ticker": "SPY",
        "count": 6
      },
      {
        "ticker": "META",
        "count": 4
      },
      {
        "ticker": "AMD",
        "count": 4
      },
      {
        "ticker": "DJI",
        "count": 3
      },
      {
        "ticker": "UST10Y",
        "count": 3
      }
    ],
    "sectors": [
      "Automotive / EV",
      "Banking & Finance",
      "Big Tech",
      "Bonds / Macro",
      "Consumer Goods",
      "Cryptocurrencies",
      "Cybersecurity",
      "Defense",
      "ETFs / Indices",
      "Industrials",
      "Media / Entertainment",
      "Oil & Gas",
      "Semiconductors",
      "Software / AI Analytics",
      "Space"
    ],
    "source_counts": {
      "Yahoo Finance": 19,
      "CNBC": 25,
      "Mining.com": 2,
      "Investing.com": 10,
      "Nasdaq": 15,
      "MarketWatch": 7,
      "CoinDesk": 2
    }
  },
  "indices": [
    {
      "name": "S&P 500",
      "symbol": "^GSPC",
      "unit": "index",
      "price": 7682.45,
      "change_abs": -82.19,
      "change_pct": -1.06,
      "spark": [
        7701.2402,
        7717.5298,
        7699.6699,
        7701.04,
        7702.3599,
        7703.7402,
        7698.5,
        7700.27,
        7698.98,
        7688.2402,
        7689.1099,
        7683.52,
        7684.5,
        7680.77,
        7676.52,
        7682.25,
        7682.79,
        7680.9302,
        7684.6499,
        7682.4502
      ]
    },
    {
      "name": "Dow Jones",
      "symbol": "^DJI",
      "unit": "index",
      "price": 51303.88,
      "change_abs": -559.81,
      "change_pct": -1.08,
      "spark": [
        51591.0508,
        51717.2617,
        51594.5703,
        51619.3711,
        51610.8398,
        51615.5195,
        51565.8711,
        51567.8711,
        51551.8281,
        51495.0898,
        51503.8008,
        51493.8789,
        51485.6406,
        51424.5195,
        51368.2695,
        51400.7695,
        51353.8594,
        51303.4102,
        51316.0195,
        51303.8789
      ]
    },
    {
      "name": "Nasdaq Composite",
      "symbol": "^IXIC",
      "unit": "index",
      "price": 26875.79,
      "change_abs": -368.49,
      "change_pct": -1.35,
      "spark": [
        26892.0273,
        26962.6133,
        26891.9355,
        26899.7812,
        26899.877,
        26909.8867,
        26891.8809,
        26900.4902,
        26899.334,
        26845.1523,
        26850.8262,
        26821.0449,
        26822.0938,
        26796.625,
        26807.8887,
        26820.4062,
        26851.7129,
        26865.2617,
        26884.9395,
        26875.791
      ]
    },
    {
      "name": "Russell 2000",
      "symbol": "^RUT",
      "unit": "index",
      "price": 2809.14,
      "change_abs": -80.78,
      "change_pct": -2.8,
      "spark": [
        2821.0896,
        2819.9241,
        2831.4543,
        2825.241,
        2823.8552,
        2824.822,
        2826.6111,
        2825.7686,
        2825.7874,
        2825.7886,
        2820.1587,
        2821.5459,
        2821.0208,
        2818.3816,
        2822.2688,
        2817.3442,
        2817.032,
        2814.3721,
        2809.1479,
        2809.1387
      ]
    },
    {
      "name": "FTSE 100 (UK)",
      "symbol": "^FTSE",
      "unit": "index",
      "price": 10659.53,
      "change_abs": -48.77,
      "change_pct": -0.46,
      "spark": [
        10721.5098,
        10723.29,
        10722.4199,
        10732.6797,
        10729.8701,
        10726.5703,
        10714.5098,
        10714.6504,
        10697.6699,
        10698.0898,
        10711.5801,
        10694.5596,
        10692.5195,
        10671.6299,
        10677.4297,
        10669.2598,
        10679.8701,
        10671.3799,
        10658.54,
        10659.5303
      ]
    },
    {
      "name": "DAX (Germany)",
      "symbol": "^GDAXI",
      "unit": "index",
      "price": 25492.34,
      "change_abs": -86.51,
      "change_pct": -0.34,
      "spark": [
        25526.1797,
        25514.2109,
        25511.5996,
        25554.0703,
        25548.0996,
        25570.3691,
        25564.1191,
        25590.5195,
        25589.2891,
        25548.0,
        25582.2305,
        25539.9707,
        25548.2402,
        25511.4707,
        25502.0293,
        25487.1992,
        25523.0898,
        25509.4297,
        25490.2793,
        25492.3398
      ]
    },
    {
      "name": "Euro Stoxx 50",
      "symbol": "^STOXX50E",
      "unit": "index",
      "price": 6346.07,
      "change_abs": 46.25,
      "change_pct": 0.73,
      "spark": [
        6356.8198,
        6353.71,
        6352.6699,
        6360.1602,
        6357.8398,
        6358.1899,
        6356.9502,
        6361.1699,
        6358.6699,
        6347.5498,
        6351.9502,
        6344.3398,
        6343.9702,
        6336.9902,
        6333.0698,
        6335.9702,
        6341.8101,
        6344.9102,
        6346.6099,
        6346.0698
      ]
    },
    {
      "name": "Nikkei 225 (Japan)",
      "symbol": "^N225",
      "unit": "index",
      "price": 65481.27,
      "change_abs": 462.32,
      "change_pct": 0.71,
      "spark": [
        65196.5117,
        65183.6094,
        65332.4805,
        65215.5391,
        65232.8789,
        65309.6992,
        65307.0,
        65239.2891,
        65106.1602,
        64988.4102,
        64985.8008,
        64996.7109,
        64941.5898,
        64999.3984,
        64953.75,
        64886.3516,
        64967.8086,
        65225.0898,
        65209.3711,
        65481.2695
      ]
    },
    {
      "name": "Hang Seng (Hong Kong)",
      "symbol": "^HSI",
      "unit": "index",
      "price": 24523.57,
      "change_abs": -564.18,
      "change_pct": -2.25,
      "spark": [
        24495.8594,
        24498.75,
        24487.7207,
        24512.4297,
        24521.1191,
        24466.4102,
        24486.5195,
        24486.6309,
        24509.4395,
        24462.4004,
        24493.1992,
        24564.2695,
        24550.7695,
        24568.5703,
        24546.6191,
        24539.75,
        24559.0703,
        24538.6191,
        24502.4492,
        24523.5703
      ]
    },
    {
      "name": "Gold (futures)",
      "symbol": "GC=F",
      "unit": "index",
      "price": 4196.9,
      "change_abs": -101.1,
      "change_pct": -2.35,
      "spark": [
        4181.8999,
        4182.8999,
        4185.6001,
        4188.7998,
        4191.5,
        4183.7002,
        4185.7002,
        4184.6001,
        4187.0,
        4188.6001,
        4183.0,
        4191.2002,
        4186.8999,
        4187.2998,
        4189.7998,
        4198.2002,
        4204.1001,
        4199.5,
        4196.3999,
        4196.8999
      ]
    },
    {
      "name": "WTI Crude Oil (futures)",
      "symbol": "CL=F",
      "unit": "index",
      "price": 91.32,
      "change_abs": -3.29,
      "change_pct": -3.48,
      "spark": [
        92.23,
        92.17,
        91.85,
        91.64,
        91.63,
        91.79,
        91.16,
        91.07,
        90.66,
        90.44,
        90.77,
        90.34,
        90.42,
        90.9,
        90.9,
        91.42,
        91.21,
        91.09,
        91.37,
        91.32
      ]
    },
    {
      "name": "Bitcoin",
      "symbol": "BTC-USD",
      "unit": "index",
      "price": 83838.3,
      "change_abs": -196.62,
      "change_pct": -0.23,
      "spark": [
        84125.1016,
        83991.9297,
        84000.9062,
        83987.5078,
        84033.6875,
        84241.6172,
        84325.5,
        84294.0078,
        84188.9922,
        84332.3516,
        84309.2109,
        84384.3672,
        84334.9609,
        84167.6562,
        84189.3516,
        83905.5078,
        83907.7031,
        83848.6484,
        83837.0,
        83838.2969
      ]
    },
    {
      "name": "10-Year US Treasury Yield",
      "symbol": "^TNX",
      "unit": "yield_pct",
      "price": 0.52,
      "change_abs": 0.01,
      "change_pct": 2.64,
      "spark": [
        0.5247,
        0.5234,
        0.5234,
        0.5232,
        0.5226,
        0.5238,
        0.5242,
        0.5238,
        0.524,
        0.5219,
        0.5224,
        0.5236,
        0.5234,
        0.5255,
        0.5257,
        0.5251,
        0.5251,
        0.5245,
        0.5247,
        0.5249
      ]
    },
    {
      "name": "VIX (Fear Index)",
      "symbol": "^VIX",
      "unit": "index",
      "price": 15.94,
      "change_abs": 0.76,
      "change_pct": 5.01,
      "spark": [
        16.06,
        16.06,
        16.04,
        15.93,
        15.91,
        15.84,
        15.89,
        15.8,
        15.77,
        15.85,
        15.84,
        15.88,
        15.82,
        15.81,
        15.97,
        15.94,
        15.85,
        15.9,
        15.93,
        15.94
      ]
    }
  ],
  "items": [
    {
      "title": "Tesla Q3 deliveries preview, as Roadster delayed",
      "link": "https://finance.yahoo.com/markets/stocks/article/tesla-q3-deliveries-preview-as-roadster-delayed-145514238.html?.tsrc=rss",
      "description": "Tesla will release highly-anticipated third quarter delivery numbers at end of the week. The report comes after the company delayed its Roadster EV reveal.",
      "source": "Yahoo Finance",
      "image": "",
      "published": "2026-09-29T14:55:14+00:00",
      "published_display": "29.09 14:55",
      "sentiment": "neutral",
      "tickers": [
        "TSLA"
      ],
      "sectors": [
        "Automotive / EV"
      ],
      "importance": 30.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "OpenAI DevDay live updates: Altman faces safety questions, Meta AI chief pokes fun at rival",
      "link": "https://www.cnbc.com/2026/09/29/openai-devday-2026-live-updates.html",
      "description": "Follow CNBC’s live coverage of OpenAI DevDay 2026, including Sam Altman’s 12 p.m. ET interview, keynote and developer announcements.",
      "source": "CNBC",
      "image": "",
      "published": "2026-09-29T14:54:51+00:00",
      "published_display": "29.09 14:54",
      "sentiment": "neutral",
      "tickers": [
        "META"
      ],
      "sectors": [
        "Big Tech"
      ],
      "importance": 15.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "MongoDB Dropped by 25% Over The Last Month: A Large, Influential Wall Street Bank Predicts 70% Gains From Here",
      "link": "https://247wallst.com/investing/2026/09/29/mongodb-dropped-by-25-over-the-last-month-a-large-influential-wall-street-bank-predicts-70-gains-from-here/?.tsrc=rss",
      "description": "A surprise CEO departure sent MongoDB tumbling 25% in a month while its database rivals barely flinched, and now one major Wall Street bank sees a setup that could reward patient investors.",
      "source": "Yahoo Finance",
      "image": "",
      "published": "2026-09-29T14:51:17+00:00",
      "published_display": "29.09 14:51",
      "sentiment": "positive",
      "tickers": [],
      "sectors": [],
      "importance": 35.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Copper holds above $14,400 as Chile strike risk grows",
      "link": "https://www.mining.com/copper-holds-above-14400-as-chile-strike-risk-grows/",
      "description": "A rejected wage offer at Antofagasta’s Centinela has added to supply concerns as the metal heads for a third straight monthly gain.",
      "source": "Mining.com",
      "image": "",
      "published": "2026-09-29T14:50:47+00:00",
      "published_display": "29.09 14:50",
      "sentiment": "positive",
      "tickers": [],
      "sectors": [],
      "importance": 35.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Putin orders army expansion as Zelenskyy warns Russia preparing to deploy 10,000 North Korean troops",
      "link": "https://www.cnbc.com/2026/09/29/putin-russia-army-ukraine-zelenskyy-north-korea.html",
      "description": "The decree marks the fourth increase in Russia’s military staffing levels this year as the war in Ukraine continues into a fifth winter.",
      "source": "CNBC",
      "image": "",
      "published": "2026-09-29T14:41:19+00:00",
      "published_display": "29.09 14:41",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 15.0,
      "content_type": "macro_context",
      "llm_classified": true
    },
    {
      "title": "Shell backs $23 billion LNG Canada expansion in boost to Carney's ‘energy superpower’ push",
      "link": "https://www.cnbc.com/2026/09/29/shell-canada-lng-carney-oil-gas-energy.html",
      "description": "The investment puts Canada on course to become a leading LNG exporter as global supply disruptions sharpen focus on energy security.",
      "source": "CNBC",
      "image": "",
      "published": "2026-09-29T14:41:03+00:00",
      "published_display": "29.09 14:41",
      "sentiment": "positive",
      "tickers": [
        "SHEL"
      ],
      "sectors": [
        "Oil & Gas"
      ],
      "importance": 35.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "US CDC confirms two measles-related deaths in 2026",
      "link": "https://www.investing.com/news/stock-market-news/us-cdc-confirms-two-measlesrelated-deaths-in-2026-4922699",
      "description": "",
      "source": "Investing.com",
      "image": "https://content-media.investing.com/news/LYNXNPEB6J0AJ_M.jpg",
      "published": "2026-09-29T14:37:30",
      "published_display": "29.09 14:37",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 10.0,
      "content_type": "macro_context",
      "llm_classified": true
    },
    {
      "title": "Interesting UCO Put And Call Options For September 2027",
      "link": "https://www.nasdaq.com/articles/interesting-uco-put-and-call-options-september-2027",
      "description": "Investors in ProShares Ultra Bloomberg Crude Oil (Symbol: UCO) saw new options begin trading today, for the September 2027 expiration. One of the key inputs that goes into the price an option buyer is willing to pay, is the time value,…",
      "source": "Nasdaq",
      "image": "",
      "published": "2026-09-29T14:37:24+00:00",
      "published_display": "29.09 14:37",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 5.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Dan Ives: Physical AI is the 'holy grail' for Nvidia",
      "link": "https://finance.yahoo.com/video/dan-ives-physical-ai-holy-143722023.html?.tsrc=rss",
      "description": "Yorkville Ives Partner and Senior Managing Director Dan Ives joins Yahoo Finance Executive Editor Brian Sozzi to discuss Nvidia's (NVDA) future and how more spending will come with the expansion of physical AI and robotics.",
      "source": "Yahoo Finance",
      "image": "",
      "published": "2026-09-29T14:37:22+00:00",
      "published_display": "29.09 14:37",
      "sentiment": "positive",
      "tickers": [
        "NVDA"
      ],
      "sectors": [
        "Semiconductors"
      ],
      "importance": 20.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "HALO May 2027 Options Begin Trading",
      "link": "https://www.nasdaq.com/articles/halo-may-2027-options-begin-trading",
      "description": "Investors in Halozyme Therapeutics Inc (Symbol: HALO) saw new options become available today, for the May 2027 expiration. One of the key data points that goes into the price an option buyer is willing to pay, is the time value, so with…",
      "source": "Nasdaq",
      "image": "",
      "published": "2026-09-29T14:37:18+00:00",
      "published_display": "29.09 14:37",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 5.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Spotify down for thousands of users in US, Downdetector shows",
      "link": "https://www.investing.com/news/stock-market-news/spotify-down-for-thousands-of-users-in-us-downdetector-shows-4923039",
      "description": "",
      "source": "Investing.com",
      "image": "https://content-media.investing.com/trkd-images/LYNXMPEM8S1AV_L.jpg",
      "published": "2026-09-29T14:37:12",
      "published_display": "29.09 14:37",
      "sentiment": "negative",
      "tickers": [],
      "sectors": [],
      "importance": 15.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Alaska Airlines unveils massive premium cabin overhaul in high-end travel race",
      "link": "https://www.cnbc.com/2026/09/29/alaska-airlines-hawaiian-new-cabins.html",
      "description": "Alaska Airlines is overhauling its Alaska and Hawaiian cabins to include brand-new top-tier suites, a premium economy class and other features.",
      "source": "CNBC",
      "image": "",
      "published": "2026-09-29T14:37:09+00:00",
      "published_display": "29.09 14:37",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 15.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Trump’s municipal bond portfolio reaches as much as $1 billion as policy overlaps mount",
      "link": "https://www.cnbc.com/2026/09/29/trump-municipal-bond-portfolio.html",
      "description": "President Donald Trump disclosed municipal bond holdings worth $300 million to $1 billion, including debt tied to issuers affected by federal policy.",
      "source": "CNBC",
      "image": "",
      "published": "2026-09-29T14:37:07+00:00",
      "published_display": "29.09 14:37",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 15.0,
      "content_type": "macro_context",
      "llm_classified": true
    },
    {
      "title": "September 2027 Options Now Available For VFC",
      "link": "https://www.nasdaq.com/articles/september-2027-options-now-available-vfc",
      "description": "Investors in VF Corp. (Symbol: VFC) saw new options become available today, for the September 2027 expiration. One of the key inputs that goes into the price an option buyer is willing to pay, is the time value, so with 353 days until…",
      "source": "Nasdaq",
      "image": "",
      "published": "2026-09-29T14:37:06+00:00",
      "published_display": "29.09 14:37",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 5.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Consumer optimism slides sharply as fears escalate over rising prices and jobs",
      "link": "https://www.cnbc.com/2026/09/29/consumer-optimism-slides-sharply-as-fears-escalate-over-rising-prices-and-jobs.html",
      "description": "The Conference Board's Consumer Confidence Index tumbled to 81.9, a decline of 6.7 points and a reading well below the forecast for 89.",
      "source": "CNBC",
      "image": "",
      "published": "2026-09-29T14:36:47+00:00",
      "published_display": "29.09 14:36",
      "sentiment": "negative",
      "tickers": [],
      "sectors": [],
      "importance": 45.0,
      "content_type": "macro_context",
      "llm_classified": true
    },
    {
      "title": "Arm and Carnival Corp among market cap stock movers on Tuesday",
      "link": "https://www.investing.com/news/stock-market-news/arm-and-carnival-corp-among-market-cap-stock-movers-on-tuesday-93CH-4923033",
      "description": "",
      "source": "Investing.com",
      "image": "https://content-media.investing.com/news/wallmart_1_M_1440049023.jpg",
      "published": "2026-09-29T14:35:51",
      "published_display": "29.09 14:35",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 18.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Nvidia has built a Sentry to watch over AI agents that act up",
      "link": "https://finance.yahoo.com/video/nvidia-built-sentry-watch-over-143528070.html?.tsrc=rss",
      "description": "In The Loop host Ejaaz Ahamadeen discusses Nvidia's (NVDA) new plans to use its Sentry chip to monitor and quarantine AI agents that go rogue. This comes in the wake of major data breaches and reports of AI agents escaping their…",
      "source": "Yahoo Finance",
      "image": "",
      "published": "2026-09-29T14:35:28+00:00",
      "published_display": "29.09 14:35",
      "sentiment": "positive",
      "tickers": [
        "NVDA"
      ],
      "sectors": [
        "Semiconductors"
      ],
      "importance": 22.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Nvidia vs. AMD: Which AI Chip Stock Has More Room to Run After AMD's Surge Past $1 Trillion?",
      "link": "https://www.fool.com/investing/2026/09/29/nvidia-vs-amd-which-ai-chip-stock-has-more-room-to/?.tsrc=rss",
      "description": "AMD stock has nearly tripled this year, propelling the company into the $1 trillion club.",
      "source": "Yahoo Finance",
      "image": "",
      "published": "2026-09-29T14:35:00+00:00",
      "published_display": "29.09 14:35",
      "sentiment": "positive",
      "tickers": [
        "NVDA",
        "AMD"
      ],
      "sectors": [
        "Semiconductors"
      ],
      "importance": 30.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "SpaceX faces \"an unprecedented set of AI and space\" opportunities: TD Cowen",
      "link": "https://finance.yahoo.com/technology/ai/articles/spacex-faces-unprecedented-set-ai-143331108.html?.tsrc=rss",
      "description": "Investing.com -- TD Cowen started coverage of SpaceX (NASDAQ: SPCX) with a Buy rating and a $200 price target in a note Tuesday, telling investors that leasing AI computing power will drive growth in the near term, with larger…",
      "source": "Yahoo Finance",
      "image": "",
      "published": "2026-09-29T14:33:31+00:00",
      "published_display": "29.09 14:33",
      "sentiment": "positive",
      "tickers": [
        "SPCX"
      ],
      "sectors": [
        "Space"
      ],
      "importance": 28.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Cattle Slip Lower into Monday’s Close",
      "link": "https://www.nasdaq.com/articles/cattle-slip-lower-mondays-close-0",
      "description": "Live cattle futures posted modest losses of 57 cents to $1.42 at the Monday close. Open interest was down 2,287 contracts on Monday. Cash trade has yet to be reported this week, with Monday mostly compiling showlists, as trade has been…",
      "source": "Nasdaq",
      "image": "",
      "published": "2026-09-29T14:32:53+00:00",
      "published_display": "29.09 14:32",
      "sentiment": "negative",
      "tickers": [],
      "sectors": [],
      "importance": 10.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Hogs Look to Tuesday Following Monday Losses",
      "link": "https://www.nasdaq.com/articles/hogs-look-tuesday-following-monday-losses",
      "description": "Lean hog futures were mostly lower on Monday, with October up a tick and the rest of the board down 55 cents to $1.27. Open interest was up just 723 contracts on Monday. USDA’s national base hog price was up 54 cents in the Monday PM…",
      "source": "Nasdaq",
      "image": "",
      "published": "2026-09-29T14:32:53+00:00",
      "published_display": "29.09 14:32",
      "sentiment": "negative",
      "tickers": [],
      "sectors": [],
      "importance": 10.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Soybeans Posting Early Rebound on Tuesday",
      "link": "https://www.nasdaq.com/articles/soybeans-posting-early-rebound-tuesday",
      "description": "Soybeans are showing 5 to 6 cent gains so far on Tuesday AM trade. Futures rounded out the bloody Monday session with contracts down 17 to 30 ¾ cents across the board. Long liquidation was noted, with a drop of 19,381 contracts in open…",
      "source": "Nasdaq",
      "image": "",
      "published": "2026-09-29T14:32:53+00:00",
      "published_display": "29.09 14:32",
      "sentiment": "positive",
      "tickers": [],
      "sectors": [],
      "importance": 12.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Corn Starting Turnaround Tuesday with a Bounce",
      "link": "https://www.nasdaq.com/articles/corn-starting-turnaround-tuesday-bounce",
      "description": "Corn prices are showing an early Tuesday bounce, with contracts up 2 to 2 ½ cents. Futures posted losses of 1 to 5 ½ cents across the board on Monday, pulling off some of the early lows at the close. Open interest was down 5,437…",
      "source": "Nasdaq",
      "image": "",
      "published": "2026-09-29T14:32:53+00:00",
      "published_display": "29.09 14:32",
      "sentiment": "positive",
      "tickers": [],
      "sectors": [],
      "importance": 10.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Cotton Falling Back on Tuesday Morning",
      "link": "https://www.nasdaq.com/articles/cotton-falling-back-tuesday-morning-1",
      "description": "Cotton price action is down 166 to 224 points across the front months on Tuesday morning. Futures were up 4 to 71 points across the board at the close. Crude oil was up 88 cents per barrel on the session, with the US dollar index $0.232…",
      "source": "Nasdaq",
      "image": "",
      "published": "2026-09-29T14:32:52+00:00",
      "published_display": "29.09 14:32",
      "sentiment": "negative",
      "tickers": [],
      "sectors": [],
      "importance": 12.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Stocks Settle Lower on Rising Bond Yields",
      "link": "https://www.nasdaq.com/articles/stocks-settle-lower-rising-bond-yields-0",
      "description": "The S&P 500 Index ($SPX ) (SPY ) closed down by -0.77% on Monday, the Dow Jones Industrial Average ($DOWI ) (DIA ) closed down by -0.67%, and the Nasdaq 100 Index ($IUXX ) (QQQ ) closed down -1.08%. December E-mini S&P futures (ESZ26 )…",
      "source": "Nasdaq",
      "image": "",
      "published": "2026-09-29T14:32:52+00:00",
      "published_display": "29.09 14:32",
      "sentiment": "negative",
      "tickers": [
        "SPY",
        "QQQ",
        "DJI"
      ],
      "sectors": [
        "ETFs / Indices"
      ],
      "importance": 30.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "New AI-powered government website uses Gemini, Grok, Trump official Gebbia says",
      "link": "https://www.cnbc.com/2026/09/29/trump-ai-gemini-grok.html",
      "description": "Trump called the new website, America.gov, \"a restoration of America's founding promise.\"",
      "source": "CNBC",
      "image": "",
      "published": "2026-09-29T14:32:15+00:00",
      "published_display": "29.09 14:32",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 8.0,
      "content_type": "macro_context",
      "llm_classified": true
    },
    {
      "title": "Why is Arm stock rallying today?",
      "link": "https://www.investing.com/news/stock-market-news/why-is-arm-stock-rallying-today-93CH-4923030",
      "description": "",
      "source": "Investing.com",
      "image": "https://content-media.investing.com/news/LYNXNPEB6U08A_M.jpg",
      "published": "2026-09-29T14:31:09",
      "published_display": "29.09 14:31",
      "sentiment": "positive",
      "tickers": [],
      "sectors": [],
      "importance": 25.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "RTX’s Collins Aerospace to expand Iowa plant that makes engine components",
      "link": "https://www.investing.com/news/stock-market-news/rtxs-collins-aerospace-to-expand-iowa-plant-that-makes-engine-components-4923028",
      "description": "",
      "source": "Investing.com",
      "image": "https://content-media.investing.com/trkd-images/LYNXMPEM8S185_L.jpg",
      "published": "2026-09-29T14:30:52",
      "published_display": "29.09 14:30",
      "sentiment": "positive",
      "tickers": [
        "RTX"
      ],
      "sectors": [
        "Defense"
      ],
      "importance": 15.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Why Boeing Stock Just Bounced Back",
      "link": "https://www.fool.com/investing/2026/09/29/why-boeing-stock-just-bounced-back/?.tsrc=rss",
      "description": "Boeing's 737 MAX 10 may be grounded, but Starliner is ready to fly again.",
      "source": "Yahoo Finance",
      "image": "",
      "published": "2026-09-29T14:30:27+00:00",
      "published_display": "29.09 14:30",
      "sentiment": "positive",
      "tickers": [
        "BA"
      ],
      "sectors": [
        "Defense"
      ],
      "importance": 18.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Cloudflare, Deutsche Telekom Collaborating on Enterprise Security in Europe",
      "link": "https://finance.yahoo.com/technology/articles/cloudflare-deutsche-telekom-collaborating-enterprise-143007984.html?.tsrc=rss",
      "description": "Cloudflare (NET) and Deutsche Telekom said Tuesday they are collaborating to strengthen digital inf",
      "source": "Yahoo Finance",
      "image": "",
      "published": "2026-09-29T14:30:07+00:00",
      "published_display": "29.09 14:30",
      "sentiment": "positive",
      "tickers": [
        "NET"
      ],
      "sectors": [
        "Cybersecurity"
      ],
      "importance": 15.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Are Meta, AMD, and Micron to thank for the September rally?",
      "link": "https://finance.yahoo.com/video/meta-amd-micron-thank-september-143000810.html?.tsrc=rss",
      "description": "Yahoo Finance Executive Editor Brian Sozzi takes a closer look at how Big Tech companies like Meta Platforms (META), Advanced Micro Devices (AMD), and Micron Technology (MU) may be running the late September market rally.",
      "source": "Yahoo Finance",
      "image": "",
      "published": "2026-09-29T14:30:00+00:00",
      "published_display": "29.09 14:30",
      "sentiment": "positive",
      "tickers": [
        "MU",
        "AMD",
        "META"
      ],
      "sectors": [
        "Big Tech",
        "Semiconductors"
      ],
      "importance": 30.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "monday.com Elevate ‘26 Puts AI Agents to Work: Every Attendee Gets to Build an Agent",
      "link": "https://finance.yahoo.com/technology/ai/articles/monday-com-elevate-26-puts-143000836.html?.tsrc=rss",
      "description": "NEW YORK & TEL AVIV, Israel, September 29, 2026--monday.com Ltd. (NASDAQ: MNDY) today announced the full program for Elevate ‘26, its flagship annual conference, taking place October 28-29, 2026 at the Javits Center in New York City.",
      "source": "Yahoo Finance",
      "image": "",
      "published": "2026-09-29T14:30:00+00:00",
      "published_display": "29.09 14:30",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 10.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "3 Stocks to Buy Before the End of September",
      "link": "https://247wallst.com/investing/2026/09/29/3-stocks-to-buy-before-the-end-of-september/?.tsrc=rss",
      "description": "The biggest profits in AI infrastructure hide in three chokepoints that most investors walk right past, and two of them are priced as if the boom is already over.",
      "source": "Yahoo Finance",
      "image": "",
      "published": "2026-09-29T14:30:00+00:00",
      "published_display": "29.09 14:30",
      "sentiment": "positive",
      "tickers": [],
      "sectors": [],
      "importance": 20.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Mike Wilson says S&P 500 correction could benefit the market",
      "link": "https://qz.com/morgan-stanley-mike-wilson-sp500-correction-bond-yields-092926?.tsrc=rss",
      "description": "The Morgan Stanley strategist's comments come as the 30-year Treasury yield hits a 22-year high and the 10-year reaches a 19-year record",
      "source": "Yahoo Finance",
      "image": "",
      "published": "2026-09-29T14:29:01+00:00",
      "published_display": "29.09 14:29",
      "sentiment": "positive",
      "tickers": [
        "MS",
        "UST10Y",
        "SPY"
      ],
      "sectors": [
        "Banking & Finance",
        "Bonds / Macro",
        "ETFs / Indices"
      ],
      "importance": 40.0,
      "content_type": "macro_context",
      "llm_classified": true
    },
    {
      "title": "Craig-Hallum Upgrades Rezolute to Buy from Hold",
      "link": "https://www.nasdaq.com/articles/craig-hallum-upgrades-rezolute-buy-hold",
      "description": "Fintel reports that on September 29, 2026, Craig-Hallum upgraded their outlook for Rezolute (NASDAQCM:RZLT) (DB:6HV1) from Hold to Buy.Prior to this rating action, the stock closed at $4.18 on September 28, 2026. This latest close of…",
      "source": "Nasdaq",
      "image": "",
      "published": "2026-09-29T14:25:33+00:00",
      "published_display": "29.09 14:25",
      "sentiment": "positive",
      "tickers": [],
      "sectors": [],
      "importance": 12.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Apple Could Keep Every iPhone Sale Yet Lose Discovery Referral, BofA Warns — Says Muse Concerns Are Overdone",
      "link": "https://stocktwits.com/news-articles/markets/equity/apple-could-keep-every-iphone-sale-yet-lose-discovery-referral-bof-a-warns-says-muse-concerns-are-overdone/cZMZ2VURBgp?.tsrc=rss",
      "description": "Bank of America said Meta Muse concerns are overdone even as it poses new risks around how consumers discover and initiate transactions, according to TheFly.",
      "source": "Yahoo Finance",
      "image": "",
      "published": "2026-09-29T14:25:29+00:00",
      "published_display": "29.09 14:25",
      "sentiment": "negative",
      "tickers": [
        "AAPL",
        "META",
        "BAC"
      ],
      "sectors": [
        "Banking & Finance",
        "Big Tech"
      ],
      "importance": 25.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Nasdaq 100 Movers: CDNS, HONIV",
      "link": "https://www.nasdaq.com/articles/nasdaq-100-movers-cdns-honiv",
      "description": "In early trading on Tuesday, shares of Honeywell International topped the list of the day's best performing components of the Nasdaq 100 index, trading up 7.5%. Year to date, Honeywell International registers a 42.2% gain. And the worst…",
      "source": "Nasdaq",
      "image": "",
      "published": "2026-09-29T14:24:51+00:00",
      "published_display": "29.09 14:24",
      "sentiment": "positive",
      "tickers": [
        "HON",
        "QQQ"
      ],
      "sectors": [
        "ETFs / Indices",
        "Industrials"
      ],
      "importance": 35.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Stocks are little changed as traders watch Treasury yield moves: Live updates",
      "link": "https://www.cnbc.com/2026/09/28/stock-market-today-live-updates.html",
      "description": "The major indexes bounced back after higher Treasury yields dragged stocks lower to start the week.",
      "source": "CNBC",
      "image": "",
      "published": "2026-09-29T14:24:40+00:00",
      "published_display": "29.09 14:24",
      "sentiment": "neutral",
      "tickers": [
        "UST10Y"
      ],
      "sectors": [
        "Bonds / Macro"
      ],
      "importance": 20.0,
      "content_type": "macro_context",
      "llm_classified": true
    },
    {
      "title": "Trump to host Anthropic’s Amodei, Nvidia’s Huang, other AI execs, as fears mount",
      "link": "https://www.investing.com/news/stock-market-news/trump-to-host-zuckerberg-anthropics-amodei-and-other-ai-titans-tuesday-4922037",
      "description": "",
      "source": "Investing.com",
      "image": "https://content-media.investing.com/trkd-images/LYNXMPEM8S0QU_L.jpg",
      "published": "2026-09-29T14:24:28",
      "published_display": "29.09 14:24",
      "sentiment": "neutral",
      "tickers": [
        "NVDA"
      ],
      "sectors": [
        "Semiconductors"
      ],
      "importance": 30.0,
      "content_type": "macro_context",
      "llm_classified": true
    },
    {
      "title": "2 S&P 500 Stocks to Consider Right Now and 1 We Question",
      "link": "https://finance.yahoo.com/markets/stocks/articles/2-p-500-stocks-consider-142402680.html?.tsrc=rss",
      "description": "While the S&P 500 (^GSPC) includes industry leaders, not every stock in the index is a winner. Some companies are past their prime, weighed down by poor execution, weak financials, or structural headwinds.",
      "source": "Yahoo Finance",
      "image": "",
      "published": "2026-09-29T14:24:02+00:00",
      "published_display": "29.09 14:24",
      "sentiment": "neutral",
      "tickers": [
        "SPY"
      ],
      "sectors": [
        "ETFs / Indices"
      ],
      "importance": 15.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Why AMD's World Labs deal just turned up the heat in the AI chip race",
      "link": "https://finance.yahoo.com/video/why-amds-world-labs-deal-142400010.html?.tsrc=rss",
      "description": "Yahoo Finance Executive Editor and Sozzi Unleashed host Brian Sozzi breaks down why AMD (AMD)is acquiring World Labs in a deal valued at $8.2 billion. As part of the deal, World Labs co-founder Fei-Fei Li will join AMD, adding to the…",
      "source": "Yahoo Finance",
      "image": "",
      "published": "2026-09-29T14:24:00+00:00",
      "published_display": "29.09 14:24",
      "sentiment": "positive",
      "tickers": [
        "AMD"
      ],
      "sectors": [
        "Semiconductors"
      ],
      "importance": 50.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Can You Justify Buying Palantir Stock Today?",
      "link": "https://www.trefis.com/articles/616946/can-you-justify-buying-palantir-stock-today/2026-09-29?.tsrc=rss",
      "description": "Palantir Technologies (PLTR) stock trades at 73 times its sales over the last twelve months, against about 3 times for the S&P 500. Revenue is growing fast, but buyers at this price are paying for years of profit Palantir has not earned…",
      "source": "Yahoo Finance",
      "image": "",
      "published": "2026-09-29T14:23:40+00:00",
      "published_display": "29.09 14:23",
      "sentiment": "negative",
      "tickers": [
        "PLTR",
        "SPY"
      ],
      "sectors": [
        "ETFs / Indices",
        "Software / AI Analytics"
      ],
      "importance": 20.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Wells Fargo upgrades S&P 500 Industrials to favorable",
      "link": "https://www.investing.com/news/stock-market-news/wells-fargo-upgrades-sp-500-industrials-to-favorable-4923008",
      "description": "",
      "source": "Investing.com",
      "image": "https://content-media.investing.com/news/LYNXNPEC8C0PB_M.jpg",
      "published": "2026-09-29T14:20:42",
      "published_display": "29.09 14:20",
      "sentiment": "positive",
      "tickers": [
        "WFC",
        "SPY"
      ],
      "sectors": [
        "Banking & Finance",
        "ETFs / Indices"
      ],
      "importance": 25.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Apple (AAPL): 1 Number That Proves Its AI Strategy Is Different From the Hyperscalers'",
      "link": "https://www.fool.com/investing/2026/09/29/apple-aapl-1-number-ai-strategy-hyperscalers/?.tsrc=rss",
      "description": "The company is standing on the sidelines and watching its peers spend aggressively on the latest technological craze.",
      "source": "Yahoo Finance",
      "image": "",
      "published": "2026-09-29T14:20:00+00:00",
      "published_display": "29.09 14:20",
      "sentiment": "neutral",
      "tickers": [
        "AAPL",
        "MSTR"
      ],
      "sectors": [
        "Big Tech",
        "Cryptocurrencies"
      ],
      "importance": 15.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "S&P 500 Movers: FICO, CCL",
      "link": "https://www.nasdaq.com/articles/sp-500-movers-fico-ccl",
      "description": "In early trading on Tuesday, shares of Carnival topped the list of the day's best performing components of the S&P 500 index, trading up 11.6%. Year to date, Carnival has lost about 19.1% of its value. And the worst performing S&P 500…",
      "source": "Nasdaq",
      "image": "",
      "published": "2026-09-29T14:19:12+00:00",
      "published_display": "29.09 14:19",
      "sentiment": "positive",
      "tickers": [
        "SPY"
      ],
      "sectors": [
        "ETFs / Indices"
      ],
      "importance": 30.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Waldron long seen as next Goldman CEO. The question is when",
      "link": "https://www.investing.com/news/stock-market-news/goldmans-board-has-discussed-plan-to-name-john-waldron-as-next-ceo-wsj-reports-4921367",
      "description": "",
      "source": "Investing.com",
      "image": "https://content-media.investing.com/trkd-images/LYNXMPEM8R1U1_L.jpg",
      "published": "2026-09-29T14:19:08",
      "published_display": "29.09 14:19",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 25.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Trinet Group About To Put More Money In Your Pocket (TNET)",
      "link": "https://www.nasdaq.com/articles/trinet-group-about-put-more-money-your-pocket-tnet",
      "description": "Looking at the universe of stocks we cover at Dividend Channel, on 10/1/26, Trinet Group Inc. (Symbol: TNET) will trade ex-dividend, for its quarterly dividend of $0.29, payable on 10/26/26. As a percentage of TNET's recent stock price…",
      "source": "Nasdaq",
      "image": "",
      "published": "2026-09-29T14:19:01+00:00",
      "published_display": "29.09 14:19",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 8.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Anthropic’s IPO prospectus sharpens focus on AI valuations",
      "link": "https://www.investing.com/news/stock-market-news/anthropics-ipo-prospectus-sharpens-focus-on-ai-valuations-4923003",
      "description": "",
      "source": "Investing.com",
      "image": "https://content-media.investing.com/trkd-images/LYNXMPEM8S19B_L.jpg",
      "published": "2026-09-29T14:18:51",
      "published_display": "29.09 14:18",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 30.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Why is Equifax stock sliding to a new 52-week low today?",
      "link": "https://www.investing.com/news/stock-market-news/why-is-equifax-stock-sliding-to-a-new-52week-low-today-93CH-4922999",
      "description": "",
      "source": "Investing.com",
      "image": "https://content-media.investing.com/news/LYNXNPEB8506G_M.jpg",
      "published": "2026-09-29T14:18:48",
      "published_display": "29.09 14:18",
      "sentiment": "negative",
      "tickers": [],
      "sectors": [],
      "importance": 25.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Reminder - Granite Point Mortgage Trust (GPMT) Goes Ex-Dividend Soon",
      "link": "https://www.nasdaq.com/articles/reminder-granite-point-mortgage-trust-gpmt-goes-ex-dividend-soon",
      "description": "Looking at the universe of stocks we cover at Dividend Channel, on 10/1/26, Granite Point Mortgage Trust Inc (Symbol: GPMT) will trade ex-dividend, for its quarterly dividend of $0.01, payable on 10/15/26. As a percentage of GPMT's…",
      "source": "Nasdaq",
      "image": "",
      "published": "2026-09-29T14:17:37+00:00",
      "published_display": "29.09 14:17",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 6.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Dow Movers: WMT, HONIV",
      "link": "https://www.nasdaq.com/articles/dow-movers-wmt-honiv-0",
      "description": "In early trading on Tuesday, shares of Honeywell International topped the list of the day's best performing Dow Jones Industrial Average components, trading up 7.5%. Year to date, Honeywell International registers a 42.2% gain. And the…",
      "source": "Nasdaq",
      "image": "",
      "published": "2026-09-29T14:17:32+00:00",
      "published_display": "29.09 14:17",
      "sentiment": "positive",
      "tickers": [
        "WMT",
        "HON",
        "DJI"
      ],
      "sectors": [
        "Consumer Goods",
        "ETFs / Indices",
        "Industrials"
      ],
      "importance": 20.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Hassett: 'We're still working our way out from' Biden Covid spending",
      "link": "https://www.cnbc.com/2026/09/29/hassett-trump-economy-biden-covid.html",
      "description": "President Donald Trump regularly defends his administration's record by contrasting it favorably with the Biden era, or other blaming the former president.",
      "source": "CNBC",
      "image": "",
      "published": "2026-09-29T14:15:52+00:00",
      "published_display": "29.09 14:15",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 8.0,
      "content_type": "macro_context",
      "llm_classified": true
    },
    {
      "title": "Stock Market Today: Dow Dips But Nvidia Hits A Buy Point; These Chip Plays Shine, Oil Stocks Lag (Live Coverage)",
      "link": "https://finance.yahoo.com/m/8757314c-41ab-383f-89ee-51177c4ae956/stock-market-today%3A-dow-dips.html?.tsrc=rss",
      "description": "Stock Market Today: The Dow Jones index dropped Tuesday as oil prices tumbled, and Treasury yields reversed higher. Nvidia hit a buy point.",
      "source": "Yahoo Finance",
      "image": "",
      "published": "2026-09-29T14:14:41+00:00",
      "published_display": "29.09 14:14",
      "sentiment": "positive",
      "tickers": [
        "NVDA",
        "UST10Y",
        "DJI"
      ],
      "sectors": [
        "Bonds / Macro",
        "ETFs / Indices",
        "Semiconductors"
      ],
      "importance": 35.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "A closer look at Anthropic's 2025 losses, Dan Ives discusses AI safety risks",
      "link": "https://finance.yahoo.com/video/closer-look-anthropics-2025-losses-141434926.html?.tsrc=rss",
      "description": "Yahoo Finance Executive Editor Brian Sozzi takes on the biggest stories as the trading day kicks off, weighing in on Anthropic's (ANTH.PVT) leaked IPO prospectus and Advanced Micro Devices' (AMD) deal to acquire World Labs. Yorkville…",
      "source": "Yahoo Finance",
      "image": "",
      "published": "2026-09-29T14:14:34+00:00",
      "published_display": "29.09 14:14",
      "sentiment": "positive",
      "tickers": [
        "AMD"
      ],
      "sectors": [
        "Semiconductors"
      ],
      "importance": 30.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "The No. 1 mistake beginners make with travel cards, according to The Points Guy",
      "link": "https://www.marketwatch.com/story/the-no-1-mistake-beginners-make-with-travel-cards-according-to-the-points-guy-3502e859?mod=mw_rss_topstories",
      "description": "The Points Guy’s Brian Kelly gave me a crash course in annual fees and redemptions to offset rising travel costs",
      "source": "MarketWatch",
      "image": "https://images.mktw.net/im-41556362",
      "published": "2026-09-29T14:13:00+00:00",
      "published_display": "29.09 14:13",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 5.0,
      "content_type": "macro_context",
      "llm_classified": true
    },
    {
      "title": "Democrats killed the Clarity Act",
      "link": "https://www.coindesk.com/opinion/2026/09/29/democrats-killed-the-clarity-act",
      "description": "Democrats should remember the people they represent and do what's best for them, not what's best for their political calculus, consultants, and special interests, writes Sen. Tim Scott (R-S.C.).",
      "source": "CoinDesk",
      "image": "https://cdn.sanity.io/images/s3y3vcno/production/29ec77135a680bab694339ef3ded4f33fbd2e35f-4686x3124.jpg?fm=jpg&w=1920&h=1080&crop=focalpoint&fit=clip",
      "published": "2026-09-29T14:08:18+00:00",
      "published_display": "29.09 14:08",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 10.0,
      "content_type": "macro_context",
      "llm_classified": true
    },
    {
      "title": "Rep. James Comer expands House investigation into prediction market insider trading",
      "link": "https://www.cnbc.com/2026/09/29/comer-house-prediction-market-insider-trading.html",
      "description": "House Oversight Committee Chair James Comer, R-Ky., announced an expanded investigation into prediction market insider trading.",
      "source": "CNBC",
      "image": "",
      "published": "2026-09-29T14:00:01+00:00",
      "published_display": "29.09 14:00",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 12.0,
      "content_type": "macro_context",
      "llm_classified": true
    },
    {
      "title": "Junk bonds are heading for worst month since 2022 after punishing global selloff",
      "link": "https://www.marketwatch.com/story/junk-bonds-are-heading-for-worst-month-since-2022-after-punishing-global-selloff-12b70a3e?mod=mw_rss_topstories",
      "description": "U.S. junk bonds are getting badly bruised in September, with their high yields so far failing to provide enough cushion this month to withstand heightened market volatility without losses.",
      "source": "MarketWatch",
      "image": "https://images.mktw.net/im-34174989",
      "published": "2026-09-29T14:00:00+00:00",
      "published_display": "29.09 14:00",
      "sentiment": "negative",
      "tickers": [],
      "sectors": [],
      "importance": 45.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Smart ring maker Oura postpones IPO due to market 'uncertainty'",
      "link": "https://www.cnbc.com/2026/09/29/smart-ring-maker-oura-postpones-ipo-due-to-market-uncertainty.html",
      "description": "Oura said the delay comes despite \"strong demand\" and a strengthenthing of the business since the start of the IPO process.",
      "source": "CNBC",
      "image": "",
      "published": "2026-09-29T13:50:01+00:00",
      "published_display": "29.09 13:50",
      "sentiment": "negative",
      "tickers": [],
      "sectors": [],
      "importance": 18.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Before you invest in the Oura IPO, understand what you’re buying",
      "link": "https://www.marketwatch.com/story/before-you-invest-in-the-oura-ipo-understand-what-youre-buying-1d88d868?mod=mw_rss_topstories",
      "description": "The health-data company could see a pop in its stock price, but there are plenty of warning signs.",
      "source": "MarketWatch",
      "image": "https://images.mktw.net/im-55840874",
      "published": "2026-09-29T13:45:00+00:00",
      "published_display": "29.09 13:45",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 10.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Two stock picks from a money manager who expects small-caps to roar in 2027",
      "link": "https://www.marketwatch.com/story/two-stock-picks-from-a-money-manager-who-expects-small-caps-to-roar-in-2027-70de9c4d?mod=mw_rss_topstories",
      "description": "Calamos Investments manager Brandon Nelson’s four-star fund is betting on financial services apps.",
      "source": "MarketWatch",
      "image": "https://images.mktw.net/im-79041298",
      "published": "2026-09-29T13:39:00+00:00",
      "published_display": "29.09 13:39",
      "sentiment": "positive",
      "tickers": [],
      "sectors": [],
      "importance": 15.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "House Speaker Johnson says he hopes AI guardrails are 'voluntary' amid Congress inaction",
      "link": "https://www.cnbc.com/2026/09/29/ai-safety-regulation-mike-johnson-congress.html",
      "description": "House Speaker Mike Johnson is scheduled for lunch Tuesday with President Trump and AI industry executives.",
      "source": "CNBC",
      "image": "",
      "published": "2026-09-29T13:37:49+00:00",
      "published_display": "29.09 13:37",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 12.0,
      "content_type": "macro_context",
      "llm_classified": true
    },
    {
      "title": "The warning signs your debt may be a problem, according to a credit counselor — and what to do first",
      "link": "https://www.cnbc.com/select/warning-signs-your-debt-is-a-problem-and-what-to-do-first/",
      "description": "There's no dollar amount that makes debt \"a problem.\" Here's what actually signals trouble.",
      "source": "CNBC",
      "image": "",
      "published": "2026-09-29T13:37:45+00:00",
      "published_display": "29.09 13:37",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 8.0,
      "content_type": "macro_context",
      "llm_classified": true
    },
    {
      "title": "Investors who have shunned diversification face maybe the best buying opportunity for bonds in decades",
      "link": "https://www.cnbc.com/2026/09/29/investors-who-have-shunned-diversification-face-maybe-the-best-buying-opportunity-for-bonds-in-decades.html",
      "description": "No diversification needed: The 10-year total return stocks minus bonds is near the highest in history.",
      "source": "CNBC",
      "image": "",
      "published": "2026-09-29T13:22:56+00:00",
      "published_display": "29.09 13:22",
      "sentiment": "positive",
      "tickers": [],
      "sectors": [],
      "importance": 25.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Nvidia's record buyback shows chipmaker's stock is too cheap for CEO Huang to resist",
      "link": "https://www.cnbc.com/2026/09/29/nvidia-buyback-shows-chipmaker-stock-is-too-cheap-for-huang-to-resist.html",
      "description": "Nvidia is looking to spend hundreds of billions of dollars buying its stock at a time when it's historically cheap based on earnings expectations.",
      "source": "CNBC",
      "image": "",
      "published": "2026-09-29T13:09:30+00:00",
      "published_display": "29.09 13:09",
      "sentiment": "positive",
      "tickers": [
        "NVDA"
      ],
      "sectors": [
        "Semiconductors"
      ],
      "importance": 35.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Some wealthy Americans are spending up to $250,000 a year on longevity care. Here's what doctors say about the practice",
      "link": "https://www.cnbc.com/2026/09/29/longevity-clinic-costs.html",
      "description": "The wealthy and ultra-wealthy are spending more on longevity care than ever before. Should you invest your money into similar therapeutics? Experts weigh in.",
      "source": "CNBC",
      "image": "",
      "published": "2026-09-29T13:09:15+00:00",
      "published_display": "29.09 13:09",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 8.0,
      "content_type": "macro_context",
      "llm_classified": true
    },
    {
      "title": "Coinbase Ventures and CMCC Global close strategic funding round with trading firm Raven",
      "link": "https://www.cnbc.com/2026/09/29/coinbase-ventures-and-cmcc-global-close-strategic-funding-round-with-raven.html",
      "description": "Raven is an institutional market-maker for prediction markets, generating constant buy and sell orders on contracts.",
      "source": "CNBC",
      "image": "",
      "published": "2026-09-29T13:05:06+00:00",
      "published_display": "29.09 13:05",
      "sentiment": "positive",
      "tickers": [
        "COIN"
      ],
      "sectors": [
        "Cryptocurrencies"
      ],
      "importance": 12.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Jim Cramer's top 10 things to watch in the stock market Tuesday",
      "link": "https://www.cnbc.com/2026/09/29/jim-cramers-top-10-things-to-watch-in-the-stock-market-.html",
      "description": "Reuters got a look at Anthropic's IPO filing, and OpenAI scrapped a model release over safety concerns.",
      "source": "CNBC",
      "image": "",
      "published": "2026-09-29T13:02:41+00:00",
      "published_display": "29.09 13:02",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 15.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "These private and public colleges have the best return on investment, according to The Princeton Review",
      "link": "https://www.cnbc.com/2026/09/29/private-public-colleges-best-roi-return-on-investment-the-princeton-review.html",
      "description": "With increasing emphasis on the return on investment, The Princeton Review's new college ranking measures academics, affordability and career outcomes.",
      "source": "CNBC",
      "image": "",
      "published": "2026-09-29T13:00:01+00:00",
      "published_display": "29.09 13:00",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 8.0,
      "content_type": "macro_context",
      "llm_classified": true
    },
    {
      "title": "Meta launches Muse for Small Business as Zuckerberg pushes beyond consumer AI market",
      "link": "https://www.cnbc.com/2026/09/29/meta-launches-muse-for-small-business-zuckerberg-pushes-enterprise-ai.html",
      "description": "Following the success of its Muse personal AI agent, Meta is introducing a specialized version for small businesses.",
      "source": "CNBC",
      "image": "",
      "published": "2026-09-29T12:43:08+00:00",
      "published_display": "29.09 12:43",
      "sentiment": "positive",
      "tickers": [
        "META"
      ],
      "sectors": [
        "Big Tech"
      ],
      "importance": 18.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Dolly Parton planned for her estate. The fight with her nephew shows why that matters.",
      "link": "https://www.marketwatch.com/story/dolly-parton-planned-for-her-estate-the-fight-with-her-nephew-shows-why-that-matters-b7e57c26?mod=mw_rss_topstories",
      "description": "It’s important to have guardrails around your legacy.",
      "source": "MarketWatch",
      "image": "https://images.mktw.net/im-19126269",
      "published": "2026-09-29T12:42:00+00:00",
      "published_display": "29.09 12:42",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 5.0,
      "content_type": "macro_context",
      "llm_classified": true
    },
    {
      "title": "Jamie Dimon has a plan to revive the West: A 'big, beautiful' deal with Europe",
      "link": "https://www.cnbc.com/2026/09/29/jamie-dimon-europe-trade.html",
      "description": "\"Many of the current disputes between Europe and the U.S. are minor compared with this agreement's size and benefits,\" the JPMorgan boss wrote this week.",
      "source": "CNBC",
      "image": "",
      "published": "2026-09-29T12:39:14+00:00",
      "published_display": "29.09 12:39",
      "sentiment": "neutral",
      "tickers": [
        "JPM"
      ],
      "sectors": [
        "Banking & Finance"
      ],
      "importance": 15.0,
      "content_type": "macro_context",
      "llm_classified": true
    },
    {
      "title": "Here are Tuesday's biggest analyst calls: Nvidia, SpaceX, Apple, Netflix, Kroger, AutoZone & more",
      "link": "https://www.cnbc.com/2026/09/29/biggest-stocks-by-analyst-calls-tuesday.html",
      "description": "Here are Tuesday's biggest calls on Wall Street.",
      "source": "CNBC",
      "image": "",
      "published": "2026-09-29T12:16:35+00:00",
      "published_display": "29.09 12:16",
      "sentiment": "neutral",
      "tickers": [
        "NVDA",
        "AAPL",
        "NFLX",
        "SPCX"
      ],
      "sectors": [
        "Big Tech",
        "Media / Entertainment",
        "Semiconductors",
        "Space"
      ],
      "importance": 12.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "IRS sends notices on Saver's Match to taxpayers who might qualify for new benefit, worth up to $2,000",
      "link": "https://www.cnbc.com/2026/09/29/savers-match-irs-retirement-benefit.html",
      "description": "The new program, which will give eligible savers a federal match for contributions to their retirement accounts, starts in 2027 and replaces the saver's credit.",
      "source": "CNBC",
      "image": "",
      "published": "2026-09-29T12:15:01+00:00",
      "published_display": "29.09 12:15",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 10.0,
      "content_type": "macro_context",
      "llm_classified": true
    },
    {
      "title": "‘We lived within our means’: I earned $30,000 as a pastor and still retired comfortably. Why don’t you tell people that?",
      "link": "https://www.marketwatch.com/story/we-lived-within-our-means-i-earned-30-000-as-a-pastor-and-still-retired-comfortably-why-dont-you-tell-people-that-6b9f231e?mod=mw_rss_topstories",
      "description": "“As a country, we have grown dangerously comfortable.”",
      "source": "MarketWatch",
      "image": "https://images.mktw.net/im-57986369",
      "published": "2026-09-29T12:15:00+00:00",
      "published_display": "29.09 12:15",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 5.0,
      "content_type": "macro_context",
      "llm_classified": true
    },
    {
      "title": "Taking Ozempic and worried about vision loss? This test can help you understand your risk.",
      "link": "https://www.marketwatch.com/story/taking-ozempic-a-routine-eye-exam-could-help-you-understand-your-risk-for-vision-loss-3392c1a0?mod=mw_rss_topstories",
      "description": "Some research suggests that GLP-1 drugs may raise the risk of a rare eye disease that causes full or partial vision loss.",
      "source": "MarketWatch",
      "image": "https://images.mktw.net/im-76876726",
      "published": "2026-09-29T12:03:00+00:00",
      "published_display": "29.09 12:03",
      "sentiment": "negative",
      "tickers": [],
      "sectors": [],
      "importance": 25.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Polymarket taps Goldman Sachs veteran Lisa Mantil to attract Wall Street liquidity",
      "link": "https://www.cnbc.com/2026/09/29/polymarket-lisa-mantil-institutional-growth.html",
      "description": "Lisa Mantil, after a nearly three-decade run at Goldman, will join the prediction market's team to attract institutional traders.",
      "source": "CNBC",
      "image": "",
      "published": "2026-09-29T12:00:33+00:00",
      "published_display": "29.09 12:00",
      "sentiment": "positive",
      "tickers": [
        "GS"
      ],
      "sectors": [
        "Banking & Finance"
      ],
      "importance": 15.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Rinehart’s rare earth stakes take $478M paper hit",
      "link": "https://www.mining.com/rineharts-rare-earth-stakes-take-478m-paper-hit/",
      "description": "Hancock’s rare earth portfolio has shed millions in value over a year as MP Materials and Lynas shares pulled back.",
      "source": "Mining.com",
      "image": "",
      "published": "2026-09-29T11:37:00+00:00",
      "published_display": "29.09 11:37",
      "sentiment": "negative",
      "tickers": [],
      "sectors": [],
      "importance": 30.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Bitcoin beats gold, surge to $100,000 in play",
      "link": "https://www.coindesk.com/daybook-us/2026/09/29/bitcoin-outperforms-gold-usd100-000-surge-in-play",
      "description": "Your day-ahead look for Sept. 29, 2026",
      "source": "CoinDesk",
      "image": "https://cdn.sanity.io/images/s3y3vcno/production/2a77c714f950490d92fe6afe133dc6a75706c94e-5760x3840.jpg?fm=jpg&w=1920&h=1080&crop=focalpoint&fit=clip",
      "published": "2026-09-29T11:34:55+00:00",
      "published_display": "29.09 11:34",
      "sentiment": "positive",
      "tickers": [
        "BTC"
      ],
      "sectors": [
        "Cryptocurrencies"
      ],
      "importance": 35.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Higher rates are wreaking havoc on these two ETFs. Traders see one bouncing back",
      "link": "https://www.cnbc.com/2026/09/29/higher-rates-are-wreaking-havoc-on-these-two-etfs-traders-see-one-bouncing-back.html",
      "description": "The relentless surge in rates is breaking the back of two key macro trades that had been holding firm.",
      "source": "CNBC",
      "image": "",
      "published": "2026-09-29T11:28:27+00:00",
      "published_display": "29.09 11:28",
      "sentiment": "negative",
      "tickers": [],
      "sectors": [],
      "importance": 30.0,
      "content_type": "market_signal",
      "llm_classified": true
    }
  ]
};
